### ISSUE TITLE
New jenkins jobs have to run twice in order for parameters to be recognized

### ISSUE THREAD

**Issue by ivanskodje** [jenkinsci/generic-webhook-trigger-plugin#100]
**Jenkinsfile:**
```
node {
 properties([
  pipelineTriggers([
   [$class: 'GenericTrigger',
    genericVariables: [
     [key: 'reference', value: '$.ref'],
     [
      key: 'before',
      value: '$.before',
      expressionType: 'JSONPath',
      regexpFilter: '', 
      defaultValue: '' 
     ],
     [key: 'repo_id', value: '$.repository.id'],
     [key: 'repo_name', value: '$.repository.full_name']
    ],
    genericRequestVariables: [],
    genericHeaderVariables: [
     [key: 'X-GitHub-Event', regexpFilter: '']
    ],
    printContributedVariables: true,
    printPostContent: true,
    regexpFilterText: '$repo_name',
    regexpFilterExpression: '^(SomethingSomething/jenkins-test)$'
   ]
  ])
 ])

 stage("build") {
  echo "Variables from shell:"
  echo "reference $reference"
  echo "before $before"
  echo "repo id: $repo_id"
  echo "repo name: $repo_name"
  echo "X_GitHub_Event $X_GitHub_Event"
 }
}
```

**What happens:**
1. Creates a new Jenkins Job with the following Pipeline script. 
2 The project is empty besides the fundamental git project setup. Does not manually insert the parameters specified in the pipeline script.
3. Pushes a change to trigger webhook on the project.
4. Project fails to build because it is unable to find the variables that the generic webhook trigger plugin is supposed to setup.

In order for me to make this "work", I have to build  the project twice.
During the first run, it managed to setup the generic webhook variables, but fail to use them in the same run.
In the second run it works because it managed to setup the variables due to the previous run. This is shown by opening the config, showing you that it has populated the GUI fields (Variable, Expression, and so on) that also was specified in the pipeline script.

Any suggestions for how to solve this are more than welcome.  
![](https://i.imgur.com/JCla7oW.png)

**Comment by tomasbjerre** [comment]
This is explained in the README.md. Check the **Pipeline** headline.
