### ISSUE TITLE
bitbucket server tag feature also trigger for commits

### ISSUE THREAD

**Issue by vishwanathcs** [jenkinsci/generic-webhook-trigger-plugin#101]
I integrated jenkins and bitbucket server v 5.10.0 with generic webhook plugin and its working fine when i commit the code.But i want to trigger the job only when tag is pushed into bitbucket.
So I followed the blog:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/bitbucket-server/bitbucket-server-tag.feature
But this configuration also trigger for commits.
I want to trigger only on tag push not for commits. Is it possible?

**Comment by tomasbjerre** [comment]
Pay attention to the issue template.
