### ISSUE TITLE
Customized parameters to be passed in the request

### ISSUE THREAD

**Issue by anandpatil** [jenkinsci/generic-webhook-trigger-plugin#102]
I am trying to pass custom parameters to feed  the pipeline which allows it make decision based on these parameters.
I tried to pass these as part of the url <jenkinsurl>token=1234&env=dev&org=myorg but could not get these in jenkins. In the past I have used "Parameterized Builds for Jenkins"-https://marketplace.atlassian.com/apps/1213179/parameterized-builds-for-jenkins?hosting=server&tab=overview but its not supported anymore, this plugin allows to post the custom parameters which came handy for automation. Is there any plan to add such capability? or any suggestions? 

Thanks!

**Comment by tomasbjerre** [comment]
This is a terrible problem description: "but could not get these in jenkins". Impossible to investigate this. Read the issue template next time.
