### ISSUE TITLE
Ability to extract Url parameters or post the parameters from the Bitbucket

### ISSUE THREAD

**Issue by anandpatil** [jenkinsci/generic-webhook-trigger-plugin#103]
I am trying to pass custom parameters to feed the pipeline which allows it make decision based on these parameters. 
I tried to pass these as part of https://<jenkinsurl>/jenkins/generic-webhook-trigger/invoke? token=1234&env=dev&org=myorg but could not get the parameters(env&org) passed in the url  in Jenkins pipeline script. 

In the past I have used "Parameterized Builds for Jenkins"-https://marketplace.atlassian.com/apps/1213179/parameterized-builds-for-jenkins?hosting=server&tab=overview but its not supported anymore, this plugin allows to post the custom parameters which came handy for automation. Is there any plan to add the capability to post the parameters from the Bitbucket side? 

Thanks!

**Comment by tomasbjerre** [comment]
This issue is missing json content received, the pipeline script used and the job configuration used.

**Comment by anandpatil** [comment]
I am able to extract the payload JSON in Jenkins & parse it & use repo name,branch,user etc no issues with that. But I want to be able send some more custom data specific to the app from the Bitbucket hook setup either through POST or through url in the least. For eg I should be able to set the "env" parameter in the Bitbucket webhook so it can be used in the Pipeline script to deploy to specific env.This "env" would differ for each app(repo) as they are deployed to different cloud environments. With the bitbucket plugin "Parameterized Builds for Jenkins"  this has been achieved but the plugin is not supported anymore .So we cannot use "Parameterized Builds for Jenkins"  due to organization policy hence looking for an alternative solution.  Hope this clarifies the requirement, below are the requested details 

Details  -
Jenkins version - Jenkins ver. 2.89.2
Obscured JSON-
{
  "eventKey": "repo:refs_changed",
  "date": "2019-01-25T01:47:16-0800",
  "actor": {
    "name": "TESTNAME",
    "emailAddress": "TESTNAME@g.com",
    "id": 8063422,
    "displayName": "TESTNAME",
    "active": true,
    "slug": "test",
    "type": "NORMAL"
  },
  "repository": {
    "slug": "test-app",
    "id": 2269809,
    "name": "test-app",
    "scmId": "git",
    "state": "AVAILABLE",
    "statusMessage": "Available",
    "forkable": true,
    "project": {
      "key": "TESTPRG",
      "id": 185888888,
      "name": "TEST Projects",
      "description": " All the projects for my group",
      "public": false,
      "type": "NORMAL"
    },
    "public": false
  },
  "changes": [
    {
      "ref": {
        "id": "refs/heads/master",
        "displayId": "master",
        "type": "BRANCH"
      },
      "refId": "refs/heads/master",
      "fromHash": "0f57aeae024cfwerer3443434ba5152642d5ad250a1256",
      "toHash": "7dd1db8cda0218e4343434343434e01d6bebb92ff909927",
      "type": "UPDATE"
    }
  ]
The Pipeline script looks like this 
node('linux') {
              stage('build') {
                  if (task.contains("build")) {
                    //build the artifact
                  }
              }//stage Build
             stage('Unit Tests') {
                 if (task.contains("build")) {
                  //run unit tests
                 }
              }
              stage('Deploy') {
                  if (env == 'dev')) {
                  // deploy to dev
                  } else
                 if (env == 'test')) {
                //  deploy to QAT
                 }
              }
              ....
              ....
    }

**Comment by tomasbjerre** [comment]
Still missing the job configuration used. No information about how you configured this plugin.

**Comment by anandpatil** [comment]
The plugin is installed in the Jenkins like below
![image](https://user-images.githubusercontent.com/3199427/51927779-5cdb1500-23c2-11e9-87ba-d066e14bb530.png)
On Bitbucket side the webhook is setup like below
![image](https://user-images.githubusercontent.com/3199427/51927871-94e25800-23c2-11e9-87b0-f59a8e0f2297.png)
I am able to extract the standard json payload elements & use them in my pipeline script.

**Comment by tomasbjerre** [comment]
None of these screenshots show how you are passing the env parameter. Perhaps you added it as a request parameter in the url.

If so, you need to configure that request parameter. It is explained in the readme.

**Comment by anandpatil** [comment]
![image](https://user-images.githubusercontent.com/3199427/51932564-69b13600-23cd-11e9-9b27-9e59aa543ccf.png)

This is how I am passing the parameters, the Readme is pointing to the curl command samples not the Bitbucket setup . Is there something that you can suggest for Bitbucket webhook setup?

**Comment by tomasbjerre** [comment]
You need to configure this plugin to consume the "env" request parameter. Add a "Request parameter" named "env".
