### ISSUE TITLE
Ability to specify token parameter name

### ISSUE THREAD

**Issue by MKletz** [jenkinsci/generic-webhook-trigger-plugin#104]
Some services have mandatory secret names. Webex teams for example will only supply a token under the parameter name 'X-Spark-Signature' in the header. Is it possible to get it configurable to take alternate parameter names aside from 'token'?

**Comment by tomasbjerre** [comment]
What you can do now is:

 1. Use a `token` that you specify in the job
 1. Point the webhook to Jenkins like `generic-webhook-trigger/invoke?token=abc123`
 1. Configure a header parameter `X-Spark-Signature`
 1. Configure regexp filter with text `$x_spark_signature` and regexp `^whatever correct value of the header$`
 1. Use the "silent response" feature to avoid showing the regexp in the response of the HTTP call.

**Comment by tomasbjerre** [comment]
`X-Spark-Signature` is HMAC right? You can configure this verification in the global admin page now. #139
