### ISSUE TITLE
Support for Github Webhook's Shared Secret?

### ISSUE THREAD

**Issue by pselden** [jenkinsci/generic-webhook-trigger-plugin#105]
What's the recommended way to use Github's Secret field with webhooks?

I've got a very generic job-seeder script that can potentially execute arbitrary commands and want to make sure I can verify the authenticity of the request.

**Comment by tomasbjerre** [comment]
I found this: https://developer.github.com/webhooks/securing/

I never used it. But it looks like if you add it you will get a `header` named `X-Hub-Signature` so you need to configure a header in this plugin with that name. And you will get a variable named `x_hub_signature` contributed.

You can get the original post content by specifying `Json Path`as just `$`.

Then just do the verification as described in the Github docs.
