### ISSUE TITLE
JasonPath with rexex

### ISSUE THREAD

**Issue by masics** [jenkinsci/generic-webhook-trigger-plugin#106]
The "Post-Receive WebHooks" for Bitbucket sends changes in format:
```json
{
    "refChanges": [{
        "refId": "refs/heads/master",
        "fromHash": "3e8682c49a7e8b61c6b931874510319a41f2d94f",
        "toHash": "01395b430bb63c88ad496abddda53a24ec3d2aba",
        "type": "UPDATE"
    }, {
        "refId": "refs/tags/tag10",
        "fromHash": "0000000000000000000000000000000000000000",
        "toHash": "942d24adc62920be8ce9d1dba0794652cc330200",
        "type": "ADD"
    }],
}
```

I want to process tags only. There is no other indication about type of change but to parse the `refId`.
I tried to use `$.refChanges[?(@.refId=~/tags/)].refId` but it won't work.
What I'm missing?

P.S. How to define filter so job will trigger on tags only?

**Comment by tomasbjerre** [comment]
Does this work?

`$.refChanges[?(@.refId =~ /^refs\/tags\/.*/i)].refId`

**Comment by masics** [comment]
No:

[image: image.png]

**Comment by tomasbjerre** [comment]
And regarding the filtering.

If you assign the above to a variable named `tagRefId`.

With filter text as `$tagRefId`.
With a filter regexp as `^(refs/tags/.+)$`.

**Comment by tomasbjerre** [comment]
Guess something went wrong when attaching that image.

**Comment by masics** [comment]
There could be multiple refs. So I don't think this expression will work.

**Comment by masics** [comment]
Here is the image:
![image](https://user-images.githubusercontent.com/6566150/54662319-ba255400-4b31-11e9-8bd5-af51b14ff4ba.png)

**Comment by tomasbjerre** [comment]
Ok in a String you need to escape the `\` like: `$.refChanges[?(@.refId =~ /^refs\\/tags\\/.*/i)].refId`

Ok the regexp should probably be something like `.*refs/tags/.*` https://jex.im/regulex/#!flags=&re=.*refs%2Ftags%2F.*

**Comment by masics** [comment]
I did not work.
```json
    "refChanges": [{
        "refId": "refs/heads/master",
        "fromHash": "830d2658a6efe5ac9d3ad8ff437352206f0844c5",
        "toHash": "4390d37be847e3704eae8edf2a5fc3075a5d6e65",
        "type": "UPDATE"
    }, {
        "refId": "refs/tags/tag13",
        "fromHash": "0000000000000000000000000000000000000000",
        "toHash": "1ca5768b3c92501a6b51a38dd60ae0882e634693",
        "type": "ADD"
    }],
```
![image](https://user-images.githubusercontent.com/6566150/54662629-bc3be280-4b32-11e9-9c67-4a3e682d4e1c.png)

I have a feeling that regex is not working at all.

**Comment by tomasbjerre** [comment]
The response of the plugin should give you a clear description of what happened. See curl commands in the readme.

**Comment by masics** [comment]
For some reason it started working after I user a curl. I don't know why it did not work before.
Thank you for your help.
P.S. I used `.+tags.+` expression for the filter. In fact testing that `refId` is not equal to `[]` should be enough.

**Comment by tomasbjerre** [comment]
ok great!
