### ISSUE TITLE
Question - Can a PR be triggered based on changed files?

### ISSUE THREAD

**Issue by ilyache** [jenkinsci/generic-webhook-trigger-plugin#108]
I'm wondering if a use-case we're having can be solved by using this plugin, so appologies in advance if this isn't the correct place to list this question. 

---

Can this plugin be used to trigger PRs based on the files changed in each PR? To better clarify what I mean, let's assume I have the following project structure:
```
root
   |___projA
   |___projB
```

I'd like to build a setup which will allow me to trigger PRs based on the files changed in them, so in the exmaple above, given a PR that has file changed in `projA` - I'd like to trigger the relevant PR job. However, if the changed files are from `projB` - do nothing. 

From the documentaiton available here:
https://developer.github.com/v3/activity/events/types/#pullrequestevent

It does not seem like there's a `changed_files` field in the webhook sent for synchornized PRs, so I'd like to verify there's no other workaround using this plugin that can be done.

Thanks in advance,
Ilya

**Comment by tomasbjerre** [comment]
Looks like it is not possible.

But you can trigger a job for any pull request. And have that job trigger another job. So that the first job would do whatever it needs to do to determine what files were changed and decide if the second job should be triggered.
