### ISSUE TITLE
OK to use GenericTrigger.

### ISSUE THREAD

**Issue by chrahunt** [jenkinsci/generic-webhook-trigger-plugin#111]
First, thank you for this plugin - I really like the built-in ability to map request details to build parameters.

I am working on a Jenkins plugin [here](https://github.com/chrahunt/jenkins-websub-trigger-plugin) for subscribing and maintaining subscriptions to WebSub endpoints and want similar behavior.

By default the plugin would populate the set of build variables with:

1. Notification content
2. Notification topic URL
3. User-provided id for the subscription
4. Optionally, headers serialized in a convenient way (or as a data structure for Pipelines, if possible)

To get the same parameter-mapping-to-build-variable behavior I was considering the following: When a job is invoked with a notification and it has an associated `GenericTrigger` trigger with token `plugin:websub-trigger`, then we could parse the request and pass the details to (associated GenericTrigger) `t.trigger(...)`, optionally augmenting the headers or params map with plugin-specific information.

What are your thoughts on this approach?

**Comment by tomasbjerre** [comment]
If it works for you, thats great!

Just be careful with the token as it allows requests without any other credentials. And also disable need for using crumb.

**Comment by chrahunt** [comment]
That's a good point. If a user is using WebSub they have the ability to enable checks that would ensure only authenticated requests get through to trigger the job - depending how common the case of parameter extraction is we wouldn't want to give up that property. I will keep this in mind.

Thank you for the feedback!
