### ISSUE TITLE
regexpFilterExpression is being ignored

### ISSUE THREAD

**Issue by diversys** [jenkinsci/generic-webhook-trigger-plugin#112]
Hi!

I'm trying to configure the plugin to only trigger on commits to `develop` branch.
However job gets triggered when I push to 'test_branch'. I'm not sure what I'm doing wrong. Please advise!

 * Plugin version 1.52.
 * Jenkins ver. 2.150.3

```
pipeline {
    agent any
    triggers {
        GenericTrigger( causeString: 'Changes detected in $repoName ( $branchName ), change type $changeType',
                genericVariables: [
                        [key: 'eventKey', value: '$.eventKey'],
                        [key: 'date', value: '$.date'],
                        [key: 'repoName', value: '$.repository.name'],
                        [key: 'repoLink', value: '$.repository.links.clone[1].href'],
                        [key: 'refId', value: '$.changes[0].refId'],
                        [key: 'ref', value: '$.ref'],
                        [key: 'changeType', value: '$.changes[0].type'],
                        [key: 'refType', value: '$.changes[0].ref.type'],
                        [key: 'branchName', value: '$.changes[0].ref.displayId'],
                ],
                printContributedVariables: true,
                printPostContent: true,
                regexpFilterExpression: '^refs/heads/develop',
                regexpFilterText: '$ref',
                token: 'ur93q47rygftkq8qwerty')
    }
```

```
Changes detected in service-address ( test_branch ), change type UPDATE
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
GenericWebhookEnvironmentContributor
 Received:

{"eventKey":"repo:refs_changed","date":"2019-04-19T20:52:29+0300","actor":{"name":"username","emailAddress":"username@domain.com","id":4484,"displayName":"User Name","active":true,"slug":"username","type":"NORMAL","links":{"self":[{"href":"https://stash.domain.com/stash/users/username"}]}},"repository":{"slug":"service-address","id":416,"name":"service-address","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":false,"project":{"key":"RTD","id":310,"name":"RTD","description":"Real Time dealing project","public":false,"type":"NORMAL","links":{"self":[{"href":"https://stash.domain.com/stash/projects/RTD"}]}},"public":false,"links":{"clone":[{"href":"ssh://git@stash.domain.com/rtd/service-address.git","name":"ssh"},{"href":"https://stash.domain.com/stash/scm/rtd/service-address.git","name":"http"}],"self":[{"href":"https://stash.domain.com/stash/projects/RTD/repos/service-address/browse"}]}},"changes":[{"ref":{"id":"refs/heads/test_branch","displayId":"test_branch","type":"BRANCH"},"refId":"refs/heads/test_branch","fromHash":"dd20ca964917acc557197c4a0343d8e78804b9bd","toHash":"e48eedc487fea3451526c70c1627fb2b1b242237","type":"UPDATE"}]}


Contributing variables:

    branchName = test_branch
    changeType = UPDATE
    date = 2019-04-19T20:52:29+0300
    eventKey = repo:refs_changed
    refId = refs/heads/test_branch
    refType = BRANCH
    repoLink = https://stash.domain.com/stash/scm/rtd/service-address.git
    repoName = service-address
```

**Comment by tomasbjerre** [comment]
Also notice that _Contributing variables:_ does not print the `ref` variable.

Could it be that you have not run it twice? See explanation in _readme_ in the **Pipeline** section.

**Comment by diversys** [comment]
It looks like it was it, thanks! Question: do I need `regexpFilterText` set to `$ref` for `regexpFilterExpression` to work?

**Comment by diversys** [comment]
Hmm, it seems I was too fast. Now it doesn't get triggered at all when pushing to `develop` branch.

**Comment by tomasbjerre** [comment]
Yes, you need to set it to ref in your case.

What response do you get from the plugin?

**Comment by diversys** [comment]
Just this:
```
Apr 20, 2019 1:57:18 PM org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver doInvoke
INFO: Triggering Experimental/webhook_test_pipeline

```

If I comment out `regexpFilterText` it starts to work again, obviously ignoring `regexpFilterExpression`.

**Comment by tomasbjerre** [comment]
I mean what response do you get when invoking the plugin? There are curl examples in the readme if you cannot see it in your git service.

**Comment by diversys** [comment]
`curl -vs curl -vs http://jenkins/generic-webhook-trigger/invoke?token=ur93q47rygftkq8qwerty 2>&1`

`{"status":"ok","data":{"triggerResults":{"Experimental/webhook_test_pipeline":{"id":0,"regexpFilterExpression":"^refs/heads/develop","regexpFilterText":"$ref","resolvedVariables":{},"triggered":false,"url":""}}}}`

**Comment by tomasbjerre** [comment]
Ok. You need to send the post content to enable the plugin to resolve ref.

**Comment by diversys** [comment]
`curl -vs -H "Content-Type: application/json" -X POST -d '{ "app":{ "name":"some value" }}' http://jenkins/generic-webhook-trigger/invoke?token=ur93q47rygftkq8qwerty 2>&1`

`{"status":"ok","data":{"triggerResults":{"Experimental/webhook_test_pipeline":{"id":0,"regexpFilterExpression":"^refs/heads/test_branch","regexpFilterText":"$ref","resolvedVariables":{},"triggered":false,"url":""}}}}`

I'm not sure what to use as content, please advise.

**Comment by tomasbjerre** [comment]
Use this but replace the branch name:

{"eventKey":"repo:refs_changed","date":"2019-04-19T20:52:29+0300","actor":{"name":"username","emailAddress":"username@domain.com","id":4484,"displayName":"User Name","active":true,"slug":"username","type":"NORMAL","links":{"self":[{"href":"https://stash.mvideo.ru/stash/users/username"}]}},"repository":{"slug":"service-address","id":416,"name":"service-address","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":false,"project":{"key":"RTD","id":310,"name":"RTD","description":"Real Time dealing project","public":false,"type":"NORMAL","links":{"self":[{"href":"https://stash.domain.ru/stash/projects/RTD"}]}},"public":false,"links":{"clone":[{"href":"ssh://git@stash.domain.com/rtd/service-address.git","name":"ssh"},{"href":"https://stash.domain.com/stash/scm/rtd/service-address.git","name":"http"}],"self":[{"href":"https://stash.domain.ru/stash/projects/RTD/repos/service-address/browse"}]}},"changes":[{"ref":{"id":"refs/heads/test_branch","displayId":"test_branch","type":"BRANCH"},"refId":"refs/heads/test_branch","fromHash":"dd20ca964917acc557197c4a0343d8e78804b9bd","toHash":"e48eedc487fea3451526c70c1627fb2b1b242237","type":"UPDATE"}]}

**Comment by diversys** [comment]
`curl -vs -H "Content-Type: application/json" -X POST -d '{"eventKey":"repo:refs_changed","date":"2019-04-19T20:52:29+0300","actor":{"name":"username","emailAddress":"username@domain.com","id":4484,"displayName":"User Name","active":true,"slug":"username","type":"NORMAL","links":{"self":[{"href":"https://stash.mvideo.ru/stash/users/username"}]}},"repository":{"slug":"service-address","id":416,"name":"service-address","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":false,"project":{"key":"RTD","id":310,"name":"RTD","description":"Real Time dealing project","public":false,"type":"NORMAL","links":{"self":[{"href":"https://stash.domain.ru/stash/projects/RTD"}]}},"public":false,"links":{"clone":[{"href":"ssh://git@stash.domain.com/rtd/service-address.git","name":"ssh"},{"href":"https://stash.domain.com/stash/scm/rtd/service-address.git","name":"http"}],"self":[{"href":"https://stash.domain.ru/stash/projects/RTD/repos/service-address/browse"}]}},"changes":[{"ref":{"id":"refs/heads/develop","displayId":"develop","type":"BRANCH"},"refId":"refs/heads/develop","fromHash":"dd20ca964917acc557197c4a0343d8e78804b9bd","toHash":"e48eedc487fea3451526c70c1627fb2b1b242237","type":"UPDATE"}]}' http://enkins/generic-webhook-trigger/invoke?token=ur93q47rygftkq8qwerty 2>&1
`

Response:



`{"status":"ok","data":{"triggerResults":{"Experimental/webhook_test_pipeline":{"id":0,"regexpFilterExpression":"^refs/heads/develop","regexpFilterText":"$ref","resolvedVariables":{"branchName":"develop","changeType":"UPDATE","date":"2019-04-19T20:52:29+0300","eventKey":"repo:refs_changed","refId":"refs/heads/develop","refType":"BRANCH","repoLink":"https://stash.domain.com/stash/scm/rtd/service-address.git","repoName":"service-address"},"triggered":false,"url":""}}}}`

**Comment by tomasbjerre** [comment]
Change the regexpFilterText to $refId not $ref.

**Comment by diversys** [comment]
Ok, after I changed it to `$refId` job is triggered no matter which branch I push to:

```
Changes detected in service-address ( test_branch2 ), change type UPDATE
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
GenericWebhookEnvironmentContributor
 Received:

{"eventKey":"repo:refs_changed","date":"2019-04-20T15:34:32+0300","actor":{"name":"user","emailAddress":"user@jdomain.net","id":4484,"displayName":"Name","active":true,"slug":"user","type":"NORMAL","links":{"self":[{"href":"https://stash.domain.ru/stash/users/user"}]}},"repository":{"slug":"service-address","id":416,"name":"service-address","scmId":"git","state":"AVAILABLE","statusMessage":"Available","forkable":false,"project":{"key":"RTD","id":310,"name":"RTD","description":"Real Time dealing project","public":false,"type":"NORMAL","links":{"self":[{"href":"https://stash.domain.ru/stash/projects/RTD"}]}},"public":false,"links":{"clone":[{"href":"ssh://git@stash.domain.ru:7999/rtd/service-address.git","name":"ssh"},{"href":"https://stash.domain.ru/stash/scm/rtd/service-address.git","name":"http"}],"self":[{"href":"https://stash.domain.ru/stash/projects/RTD/repos/service-address/browse"}]}},"changes":[{"ref":{"id":"refs/heads/test_branch2","displayId":"test_branch2","type":"BRANCH"},"refId":"refs/heads/test_branch2","fromHash":"9f58e8ea0a710304ff52cf7e2efae8b484bedd3b","toHash":"967cc24ddeaffa5f28f8ea8b60f81b69de5a3b1c","type":"UPDATE"}]}


Contributing variables:

    branchName = test_branch2
    changeType = UPDATE
    date = 2019-04-20T15:34:32+0300
    eventKey = repo:refs_changed
    refId = refs/heads/test_branch2
    refType = BRANCH
    repoLink = https://stash.domain.ru/stash/scm/rtd/service-address.git
    repoName = service-address
```

**Comment by tomasbjerre** [comment]
And what is the response of the curl command now with another branch?

**Comment by diversys** [comment]
Odd, it works now! I probably didn't rebuild (although I swear I did that, tho). Thanks a lot for your help :)
