### ISSUE TITLE
How do I customize the content of response?

### ISSUE THREAD

**Issue by daronz** [jenkinsci/generic-webhook-trigger-plugin#113]
Hello, this plugin is very useful, but its response cannot be customized, so I cannot return the required result to the requested system. For security reasons, this system will not open the interface. Any help would be appreciated, thanks !

**Comment by tomasbjerre** [comment]
What do you want to include in the response?

**Comment by daronz** [comment]
> What do you want to include in the response?

Simple string value

**Comment by tomasbjerre** [comment]
Containing what?

**Comment by daronz** [comment]
> Containing what?

For example, "There is something wrong with the data A"

**Comment by tomasbjerre** [comment]
Sounds like it is not static? You want it to vary depending on some condition?

**Comment by daronz** [comment]
The result of verifying the json parameter.

**Comment by daronz** [comment]
> Sounds like it is not static? You want it to vary depending on some condition?

Yes, after I receive the json data, I verify the correctness of the data and return the validation result.

**Comment by RenatIsin** [comment]
Hello. I am need this feature too.
I am try to trigger job from slack bot, and need to reply with specific param from request body.
`{
    "token": "Jhj5dZrVaK7ZwHHjRyZWjbDl",
    "challenge": "3eZbrw1aBm2rZgRNFdxV2595E9CY3gmdALWMmHkvFXO7tYXAYM8P",
    "type": "url_verification"
}`
Slack app send body like above, and I need add challenge param to response.

Is it possible to add custom script evaluation to prepare response body. 
Or maybe set custom body as string value that I can generate by groovy pipeline.

**Comment by tomasbjerre** [comment]
If you resolve it to a variable with the jsonpath expression `$.challange` it will be in the response. But I guess you want the response to also have another structure?

**Comment by RenatIsin** [comment]
@tomasbjerre thanks, it's works as need.
