### ISSUE TITLE
Blank parameter trigger the job even if you specified a filter

### ISSUE THREAD

**Issue by oriolete** [jenkinsci/generic-webhook-trigger-plugin#115]
Hi,

I've specified a job trigger filter but if parameter used is blank it triggers when not have to do. Information extracted form bitbucket:

"BCP_FSC/validar_feature": {
        "id": 1575,
        **"regexpFilterExpression": "^feature",
        "regexpFilterText": "",**
        "resolvedVariables": {
          "branch": "",
          "branch_destino": "",
          "x_event_key": "repo:push",
          "x_event_key_0": "repo:push"
        },
        **"triggered": true,**
        "url": "queue/item/1575/"
      },

I've last versions of plugin and Jenkins.

Thanks in advance.

**Comment by tomasbjerre** [comment]
Releasing 1.54 now with a fix!

Open issue again if not working.
