### ISSUE TITLE
if several requests arrive within a short span of time, the events get squashed into one job invocation

### ISSUE THREAD

**Issue by juanpablo-santos** [jenkinsci/generic-webhook-trigger-plugin#116]
We are using latest Jenkins LTS and latest webhook plugin, and we've noticed that, when several post requests are sent within a short span of time (maybe a couple of seconds?) instead of having one job invocation per request, we end up with one job request, which has received all the posts, i.e.:

```
generic webhook cause parameter for post # 1
generic webhook cause parameter for post # 2
generic webhook cause parameter for post # 3
```

The body posted on this job invocation only contains the variables associated to the last post. The issue can be easily reproduced, just setup one job managed by the webhook plugin and make some posts to it in a very short span of time (we suspect that it maybe within a second or a couple of seconds). In our case, the git repo manager has some webhooks to a webhook-managed jenkins job to perform some tasks (update labels, close PRs, etc.) and we noticed that, under high load we lose some events.

**Comment by tomasbjerre** [comment]
Did you try setting quiet period to 0? See also https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/64

**Comment by juanpablo-santos** [comment]
Hi @tomasbjerre,

thanks for the prompt response!

indeed, it is the same issue, apologies for the noise. In our case, unchecking the `Do not allow concurrent builds` option + setting the `Quiet period` to `0` was enough. Perhaps this should be added to the plugin documentation?


best regards,
juan pablo
