### ISSUE TITLE
JSONPath fail to match in Jenkins. Work on test page.

### ISSUE THREAD

**Issue by Lukas238** [jenkinsci/generic-webhook-trigger-plugin#117]
Hi,

I want to trigger a Job only when a specific branch is pushed.

As per the documentation, I added a JSONPath to match the variable I need from the posted JSON payload (posted by the bitbucket webhook).

I manage to capture the actual webhook post payload, and tested my JSONPath against, successfully.

But when the webhook is triggered on Jenkins, the JSONPath fail to match anything, and returns empty.

- **JsonPath match**: `$.refChanges.[0].refId`

- [hook_payload.txt](https://github.com/jenkinsci/generic-webhook-trigger-plugin/files/3193063/hook_payload.txt)
- [jenkins_response.txt](https://github.com/jenkinsci/generic-webhook-trigger-plugin/files/3193064/jenkins_response.txt)

---

**I'm using**:
- Jenkins ver. 2.150.3
- Generic Webhook Trigger Plugin 1.54

Thanks!

**Comment by tomasbjerre** [comment]
This part of the `jenkins_response.txt` tells me there is no filter configured in the job:
```
        "regexpFilterExpression": "",
        "regexpFilterText": "",
```
