### ISSUE TITLE
Pipeline Multibranch Job is Not Triggering .

### ISSUE THREAD

**Issue by Saurabh240991** [jenkinsci/generic-webhook-trigger-plugin#119]
Hi Team, 

I'm trying to do Webhook for  Multibranch Branch.

As a Example we have two branch :- 

1) developer 
2) master 

We are using Jenkinsfile.

This is below code I'm using for develop branch Jenkinsfile.

  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: 'refs/heads/develop'],
      [key: 'repository', regexpFilter: '[^a-z_-]', value: 'test-projec']
     ],
     causeString: 'Triggered on $ref', 
     token: 'asdfghjkl',
     regexpFilterExpression: 'generic $ref',
     regexpFilterText: '$repository refs/heads/' + BRANCH_NAME,
     printContributedVariables: true,
     printPostContent: true
    )
  }

on First run i have build manually and added webhook token to Bitbucket webhook. 

Now when ever i push the code. 

Job is not getting triggered. 

Could you please help me for this. 

Regards
Saurabh

**Comment by tomasbjerre** [comment]
The `regexpFilterExpression` should be a regular expression. Variables, like `$ref` is not resolved here. Use variables in `regexpFilterText`.

The value here is not a valid JSONPath: `[key: 'ref', value: 'refs/heads/develop'],`. Same with `[key: 'repository', regexpFilter: '[^a-z_-]', value: 'test-projec']`

It may help you to have a look at the examples here:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/tree/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd

Also check the **Pipeline**-section in the README.md. To see how you check what configuration has been applied.

Also see the **Troubleshooting**-section of the README.md.

**Comment by Saurabh240991** [comment]
I agree 

Please Correct me if i'm wrong, 

triggers {
GenericTrigger(
genericVariables: [
[key: 'ref', value: 'refs/heads/develop'],
[key: 'repository', regexpFilter: '[^a-z_-]', value: 'test-projec']
],
causeString: 'Triggered on $ref',
token: 'asdfghjkl',
regexpFilterExpression: 'generic $ref',
regexpFilterText: '$repository refs/heads/' + BRANCH_NAME,
printContributedVariables: true,
printPostContent: true
)
}

************** 

I have modified  the code 

  triggers {
    GenericTrigger(
     causeString: 'Triggered on refs/heads/develop', 
     token: 'asdfghjkl',
     regexpFilterText: 'generic refs/heads/develop',
     regexpFilterText: 'test-projec refs/heads/' + BRANCH_NAME,
     printContributedVariables: true,
     printPostContent: true
    )
  }
 
I have gone through Readme Docs, but unable to get. 

Still I'm getting error. 

Please correct me
