### ISSUE TITLE
RegExFilterText Not Evaluating Variable?

### ISSUE THREAD

**Issue by AmarettoSlim** [jenkinsci/generic-webhook-trigger-plugin#122]
Hi @tomasbjerre, I'm banging my head at trying to get the RegExFilterText to work and I'm hoping you might be able to help me ...

Below is a screenshot of my call via Postman:

![image](https://user-images.githubusercontent.com/6744436/59791034-3cdbbd80-929f-11e9-8755-52c400fffad6.png)

It looks as though my variables are being populated correctly and I think my regex expression and text is correct but it's not triggering. I've built the job a couple times manually and then attempted to call it via a POST and I've been unsuccessful.

If I change the text to be hardcoded as master, it works. Is the issue that the variable $PR_TO_BRANCH isn't being evaluated?

![image](https://user-images.githubusercontent.com/6744436/59791288-c1c6d700-929f-11e9-9bba-7692a9fbe801.png)

I'm running:

Jenkins 2.164.3
Generic Webhook Trigger Plugin 1.54

Any idea what's going on?

Thank you for your time, I appreciate you reading this!

**Comment by tomasbjerre** [comment]
Remove the `$` from the variable names in "post content parameters". Your second screenshot.

**Comment by AmarettoSlim** [comment]
Ugh, silly mistake on my part, that worked, thanks Tomas!
