### ISSUE TITLE
Webhook Issue with regexpfiltertext for multiple parameters

### ISSUE THREAD

**Issue by Saurabh240991** [jenkinsci/generic-webhook-trigger-plugin#123]
Hello, 

I have Created Jenkins Webhook Job. 

This Job I have created Manually 

![image](https://user-images.githubusercontent.com/28196459/60322093-3edb0600-999c-11e9-8ea4-13736818a966.png)

Optional filter :-  ^(test)*?$
Text:- $refsb$refsbc

This Job Run Perfect Fine. 

Below is logs 

{
   "status": "ok",
   "data": {
      "triggerResults": {
         "me/TestDevOps": {
            "id": 2708,
            "regexpFilterExpression": "^(test)*?$",
            "regexpFilterText": "test",
            "resolvedVariables": {
               "refsb": "",
               "refsbc": "test"
            },
            "triggered": true,
            "url": "queue/item/2708/"
         }
      }
   }
}

But Same things I did from Jenkinsfile. 

  triggers {
    GenericTrigger(
     genericVariables: [
     [
      key: 'refsb',
      value: '$.changes[0].ref.id',
      expressionType: 'JSONPath', 
      regexpFilter: '^(refs/heads/|refs/remotes/origin/)'
     ],
     [
      key: 'refsbc',
      value: '$.pullRequest.toRef.id',
      expressionType: 'JSONPath', 
      regexpFilter: '^(refs/heads/|refs/remotes/origin/)'
     ]
	 ],      
     causeString: 'Triggered on $refsb',     
     token: 'xxxxxxxxxxxxxxxxxxxxx',     
     printContributedVariables: true,
     printPostContent: true,     
     silentResponse: false,    
     regexpFilterText: '$refsb$refsbc',
     regexpFilterExpression: '^(test)*?$'
    )
  }

but for this logs: 

         "me/me/test": {
            "id": 0,
            "regexpFilterExpression": "^(test)*?$",
            "regexpFilterText": "$refsb test",
            "resolvedVariables": {
               "refsbc": "test"
            },
            "triggered": false,
            "url": ""
         }

the point is here, 

Via Jenkinsfile same configuration then why it resolved Variables have only "refsbc" but it should be "refsbc" and "refsb "

*************************************************************
         "me/me/test": {
            "id": 0,
            "regexpFilterExpression": "^(test)*?$",
            "regexpFilterText": "$refsb test",
            "resolvedVariables": {
               "refsbc": "test"
            },
***********************************************************
            "regexpFilterExpression": "^(test)*?$",
            "regexpFilterText": "test",
            "resolvedVariables": {
               "refsb": "",
               "refsbc": "test"
            },

Looking for your support. 

Regards
Saurabh

**Comment by Saurabh240991** [comment]
Through Jenkinsfile it's treating both as Same variables, which shouln't be case. 

It Should treat both different variables. 

Please suggest me

**Comment by Saurabh240991** [comment]
regexpFilterText: '$refsb$refsbc' from Optional Filter Considering both as single Variable which seems like bugs through Jenkinsfile 

and but if do through GUI it's taking two Variable. 

Please let me know what can be the best option to Avoid this ?

**Comment by Saurabh240991** [comment]
@tomasbjerre  Could you please able to help me for this. 

Not Sure Why it considering 2 separate Variable as Single Vairable through jenkinsfile pipeline. 

Please help me for this

**Comment by tomasbjerre** [comment]
You should respect the issue template and provide the information that it asks for. In this case the **post content received** would help.

**Comment by Saurabh240991** [comment]
@tomasbjerre , 

Yes Sure, I will do.

Please find the Post 

**Current Output**

{
   "status": "ok",
   "data": {
      "triggerResults": {
             "me/me/test": {
             "id": 0,
             "regexpFilterExpression": "^(test)*?$",
             "regexpFilterText": "$refsb test",
             "resolvedVariables": {
             "refsbc": "test"
        },
            "triggered": false,
            "url": ""
         }
      }
   }
}

**Expected Output** 

{
   "status": "ok",
   "data": {
      "triggerResults": {
             "me/me/test": {
             "id": 0,
        "regexpFilterExpression": "^(test)*?$",
        "regexpFilterText": "test",
        "resolvedVariables": {
           "refsb": "",
           "refsbc": "test"
        },        
           "triggered": false,
            "url": ""
         }
      }
   }
}


In resolvedVariables Variable there should both optional filter but it's not coming, through Jenkinsfile Pipeline.

**Comment by tomasbjerre** [comment]
By **post content received** I mean the post content sent to the plugin.

**Comment by Saurabh240991** [comment]
@tomasbjerre 

I apologize, 



{
   "eventKey": "repo:refs_changed",
   "date": "2019-06-28T11:05:24+0000",
   "actor": {
      "name": "xxxxxxx",
      "emailAddress": "xxxxxxxxxxxxxxxxxx",
      "id": 563,
      "displayName": "xxxxxxxxxxxxxxxxx",
      "active": true,
      "slug": "xxxxxxx",
      "type": "NORMAL",
      "links": {
         "self": [
            {
               "href": "https://xxxxxxxxxxxxxxxxxxxxxx"
            }
         ]
      }
   },
   "repository": {
      "slug": "xxxxx-xxxx",
      "id": 80,
      "name": "xxx-xxxxx",
      "scmId": "git",
      "state": "AVAILABLE",
      "statusMessage": "Available",
      "forkable": true,
      "project": {
         "key": "xxx",
         "id": 128,
         "name": "xxxx",
         "description": "A Bitbucket t.",
         "public": false,
         "type": "NORMAL",
         "links": {
            "self": [
               {
                  "href": "https://xxxxxxxxxxxxxx"
               }
            ]
         }
      },
      "public": false,
      "links": {
         "clone": [
            {
               "href": "xxxxxxxxxxxxxxxxxx",
               "name": "http"
            },
            {
               "href": "xxxxxxxxxxxxxxxxxx",
               "name": "ssh"
            }
         ],
         "self": [
            {
               "href": "xxxxxxxxxxx"
            }
         ]
      }
   },
   "changes": [
      {
         "ref": {
            "id": "refs/heads/test",
            "displayId": "test",
            "type": "BRANCH"
         },
         "refId": "refs/heads/test",
         "fromHash": "xxxxxxxxxxxxxx",
         "toHash": "xxxxxxxxxxxxxxxxx",
         "type": "UPDATE"
      }
   ]
}

What I'm trying to do, whenever push request or merge or update happen webhook should triggered.

**Comment by tomasbjerre** [comment]
See: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/bitbucket-server/bitbucket-server-refs_changed.feature

You have your text set to `$refsb$refsbc`. `refsb` resolves to `test` and `refsbc` resolved to empty string. The rendered text, `$refsb$refsbc`. First `$refsbc` is rendered and we have `$refsb`. Then `$refsb` is rendered and we have `test`.

The issue template asks for version of the plugin, which would have helped determine if you encountered an old bug or not.

This might also be an issue with the jenkinsfile properties not having been applied to the job. That is explained in the pipeline section in the readme.

**Comment by Saurabh240991** [comment]
Yes Sure @tomasbjerre 

Please find the Version Below :- 

generic-webhook-trigger :- 1.54
Bitbucket :-  5.16.0
Jenkins:- 2.150.1

Post Content from BitBucket different for Commit and Pull Open Request. 

I'm trying to do if pull open request or Commit happen to Test branch webhook should trigger. 

**This might also be an issue with the jenkinsfile properties not having been applied to the job. That is explained in the pipeline section in the readme.** --> How to Achieve this things ?
