### ISSUE TITLE
Trouble With Webhook From BitBucket

### ISSUE THREAD

**Issue by warren5236** [jenkinsci/generic-webhook-trigger-plugin#124]
Hello,
Thanks for Jenkins and this plugin!  We're having trouble getting this plugin to work with a webhook from bitbucket.  I copied the configuration directly from your readme into our Jenkinsfile and it doesn't fire off a build.  However if I change regexpFilterText and regexpFilterExpression to both be '' it runs but for every push even if it's not the branch were adding this to.  Is there part of the configuration I missed?

 * Plugin version used - 1.54
 * Jenkins version used -  2.176.1
 * Pipeline
```
triggers {
    GenericTrigger(
        genericVariables: [
            [key: 'ref', value: '$.ref']
        ],
        
        causeString: 'Triggered on $ref',
        
        token: '<removed>',
        
        printContributedVariables: true,
        printPostContent: true,
        
        silentResponse: false,
        
        regexpFilterText: '$ref',
        regexpFilterExpression: 'refs/heads/' + BRANCH_NAME
    )
}
```
 
 * A `curl` command and its response.
```
curl -vs -X POST http://URL:8080/generic-webhook-trigger/invoke?token=<removed> -d '{
  "before": "1848f1236ae15769e6b31e9c4477d8150b018453",
  "after": "5cab18338eaa83240ab86c7b775a9b27b51ef11d",
  "ref": "refs/heads/feature/jenkins"
}'
```
Response
```
{"status":"ok","data":{"triggerResults":{"aes/feature%2Fjenkins":{"regexpFilterExpression":"refs/heads/feature/jenkins","triggered":false,"resolvedVariables":{},"regexpFilterText":"$ref","id":0,"url":""}}}}
```

**Comment by tomasbjerre** [comment]
Have the configuration from the pipeline been applied to the job? See the pipeline section https://github.com/jenkinsci/generic-webhook-trigger-plugin#pipeline

**Comment by warren5236** [comment]
I created the pipeline using Blue Ocean it doesn't have any options for the Generic Webhook Trigger Plugin.    It's set to pull the settings from the Jenkinsfile.

**Comment by tomasbjerre** [comment]
You need the json header:

```shell
curl -vs -X POST http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=abc123 -H "Content-Type: application/json" -d '{
  "before": "1848f1236ae15769e6b31e9c4477d8150b018453",
  "after": "5cab18338eaa83240ab86c7b775a9b27b51ef11d",
  "ref": "refs/heads/feature/jenkins"
}'
```

**Comment by tomasbjerre** [comment]
If you do not have any filter, it will fire for every invokation. Check the readme to see how the filter works.

"it doesn't fire off a build" Exactly when does it not fire off a build? With what configuration? With what invokation?

**Comment by warren5236** [comment]
I figured out the problem.  

For anyone looking for this in the future the requests from BitBucket look like this (I removed a bunch of junk):
```
{
  "push": {
    "changes": [
      {
        "forced": false,
        "old": {
          "name": "feature/jenkins",
        }
      }
    ]
  }
}
```

And don't contain a `$.ref` element.

I had to make this line:

    [key: 'ref', value: '$.ref']

this

    [key: 'ref', value: '$.push.changes[0].old.name']
