### ISSUE TITLE
Trigger newly created branch or PR

### ISSUE THREAD

**Issue by jarspi** [jenkinsci/generic-webhook-trigger-plugin#128]
From the README:

```This is a Jenkins plugin that can:

 1. Receive any HTTP request, `JENKINS_URL/generic-webhook-trigger/invoke`
 2. Extract values

  * From `POST` content with [JSONPath](https://github.com/json-path/JsonPath) or [XPath](https://www.w3schools.com/xml/xpath_syntax.asp)
  * From the `query` parameters
  * From the `headers`

 3. Trigger a build with those values contribute as variables
```

Do I understand it right that the job configuration must already exist in Jenkins in order for the plugin to be able to trigger a new build?

We have the following use case:
1. Repository with multi-branch pipeline stored as a code in Jenkinsfile
2. Create a new branch and push it to GitHub
3. GitHub sends webhook to Jenkins
4. Jenkins should build the new branch

This can be achieved with [GitHub Branch Source Plugin](https://wiki.jenkins.io/display/JENKINS/GitHub+Branch+Source+Plugin) but if I understand it right, the Generic Webhook trigger plugin is not able to discover a new branch. Is that correct?

**Comment by tomasbjerre** [comment]
Yes, the job has to exist. And it will exist after a scan. And a scan can be triggered with: https://github.com/jenkinsci/multibranch-scan-webhook-trigger-plugin

**Comment by jarspi** [comment]
Yes, I saw that plugin but it relies on a manually created token to trigger the correct job. That's not something we can rely on, having hundreds of repositories in the organisation.

With the currently available plugins, I think the only way to trigger job on a GitHub webhook and have branches auto-discovered is to use the [GitHub plugin](https://wiki.jenkins.io/display/JENKINS/GitHub+Plugin). That one, however, doesn't expose the webhook payload as nicely as your plugin does.

Anyway, thanks for your answer. This question can be closed.

**Comment by tomasbjerre** [comment]
You can use Job DSL to create the multibranch pipelines. And set the token of each multibranch pipeline to the name of the git repository. Using a rest-call from the Groovy in Job DSL to find all repositories, and loop them.

The webhooks in github can also be automated with some script if you know that the token is the name of the repository.
