### ISSUE TITLE
Generic Webhook hook stops working on  v1.15

### ISSUE THREAD

**Issue by iugostang** [jenkinsci/generic-webhook-trigger-plugin#13]
After updating to v1.15, our webhook that used to work no longer works.  Jenkins logs spits out:

`INFO: Did not find any jobs to trigger! The user invoking /generic-webhook-trigger/invoke must have read permission to any jobs that should be triggered.`

The webhook looks like this:

`https://jenkins_user:jenkins_password@jenkins.myhost.com/generic-webhook-trigger/invoke`

After rolling back to v1.14, everything works again.

**Comment by tomasbjerre** [comment]
Most likely this change: https://github.com/jenkinsci/generic-webhook-trigger-plugin/commit/8a98d57c06952fa

Do you use a token-parameter?
Whar version of Jenkins is this?

**Comment by iugostang** [comment]
I do not use a token parameter.  This is on Jenkins 2.60.2

**Comment by tomasbjerre** [comment]
I'm releasing a possible fix for this in 1.16 now. Should be available within a few hours.

**Comment by iugostang** [comment]
Thank you for the quick turnaround, sir!
