### ISSUE TITLE
Multibranch pipeline no jobs configured

### ISSUE THREAD

**Issue by mlaythe** [jenkinsci/generic-webhook-trigger-plugin#131]
* Plugin version used.
1.5.7
 * Jenkins version used.
2.176.2
 * Your configuration.
   * Pipeline script (See Pipeline section in README)
  Used example code provided in README for scripted Jenkinsfile
 * A `curl` command and its response.
`{"status":"ok","data":{"triggerResults":{"ANY":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@jenkins/generic-webhook... "}}}`
 * Expected result and actual result.
Added webhook in GitHub:`http://username:password@jenkins_url/generic-webhook-trigger/invoke`. And added example code provided in README for scripted Jenkinsfile. Was expecting for it to build on Jenkins. Do I need to setup something else for a multibranch pipeline?

**Comment by tomasbjerre** [comment]
Did you configure the job with a token? Did you supply that token in your
curl command?

Den tis 27 aug. 2019 18:51Michael Laythe <notifications@github.com> skrev:

**Comment by tomasbjerre** [comment]
Can you provide the pipeline script used?
Can you provide the curl command?
Can you provide a screenshot of a job configuration created by multibranch? One that you expect to be triggered.
