### ISSUE TITLE
Multiple filters on same variable ?

### ISSUE THREAD

**Issue by Bobillot** [jenkinsci/generic-webhook-trigger-plugin#132]
Hi ! 
I was wondering if it was possible to perform multiple filters on a single variable of a JSON input ?

I am working with the 1.51 version of the plugin, and I am experiencing some issue with the filters I set up when there are some "\n" in the variables I am working on :

Here is the field I want to get from my JSON : 
`"message": "Merge pull request #97 from Blabla/feature\n\nUpdate setup.py"`
I set up some rules on Jenkins to avoid triggering it when the value of this field is "Jenkins" (which I set from Jenkins, so I need to ignore it to avoid autotrigger but whatever). My rule is : 
`[$class: 'GenericTrigger',
    genericVariables: [
     [key: 'head', value: '$.message', regexpFilter: '.*Jenkins.*', defaultValue: 'Jenkins']
    ],
    regexpFilterText :'$head',
    regexpFilterExpression: '^(?!Jenkins).*'
   ]
  ])
 ])`

It works all the time except when there is a "\n" character in the "message" field, so I'm trying to resolve this issue by setting a second filter on the "message" field (which I don't know how to do).
So here is my question : 
Is there a way from my pipeline to keep my filter this way (ignore when "Jenkins" is in "message" field), and to add a rule that deletes "\n" when it finds some in the "message" field ?
I tried this :  
`  [key: 'head', value: '$.head_commit.message', regexpFilter: '.*Jenkins.*', defaultValue: 'Jenkins']
     [key: 'newhead', value: '$head', regexpFilter: '.*\\n.*', defaultValue: 'I don't care']`
which didn't work
I'm quite new to Jenkins and to your plugin, so I'm not really aware of what is possible and what's not, sorry if I am telling inconsistent stuff ..
I hope I provided enough informations for you to be able to help me, else just tell me !
Thank you so much in advance !

**Comment by tomasbjerre** [comment]
Perhaps this test case helps? https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/filter-with-variables.feature#L68

I create a `messageFiltered`-variable that removes newlines, `regexpFilter` like `[\r\n] `. And I create filter with `$text` like `$messageFiltered` and `expression` like `^(?!.*(Jenkins)).*`.

**Comment by Bobillot** [comment]
Thank you so much !
