### ISSUE TITLE
Ability to add more optional filters to run the job based on OR operations of two AND operations.

### ISSUE THREAD

**Issue by avatsyain** [jenkinsci/generic-webhook-trigger-plugin#136]
I have two variables action and merged.

possible values of action ^(reopened|opened|closed|synchronize)$
possible value of merged ^(true|false)$

I want the job to be triggered only when
1. {"action": "opened", "merged":false}
2. {"action": "reopened", "merged":false}
3. {"action": "synchronize", "merged":false}
4. {"action": "closed", "merged":true}

The job shouldn't be triggered except above scenarios.

**Comment by tomasbjerre** [comment]
This should work:

Filter text: `$action $merged`
Filter regexp: `(opened false)|(reopened false)|(synchronize false)|(closed true)`

https://jex.im/regulex/#!flags=&re=(opened%20false)%7C(reopened%20false)%7C(synchronize%20false)%7C(closed%20true)
