### ISSUE TITLE
Make HMAC Authentication independent of requiring an IP.

### ISSUE THREAD

**Issue by bkruger99** [jenkinsci/generic-webhook-trigger-plugin#141]
It appears that if you want to use HMAC on any IP that makes contact is not possible.  This is difficult in cases where you may be using a service that using AWS (for example) that isn't using static IP addresses or may not provide a hostname to match against.

If you leave the host/IP blank, it just causes a null exception in the Jenkins log.

**Comment by tomasbjerre** [comment]
Would it solve the problem if **Hostname or IP** is put inside an optional block, just like **Verify with HMAC** is?

**Comment by tomasbjerre** [comment]
Actually, a better solution might be the change the **Hostname or IP** to a regular expression. That would be backward compatible and in your case you could just set it to `.*` or empty.

**Comment by bkruger99** [comment]
Either would do the trick.  So long as it isn't a static entry.

**Comment by AbsoluteOther** [comment]
My env isn't setup to build/test/run this yet, but what about CIDR notation? (Could do ranges too, but it's late and the [GitHub WebHook API List](https://api.github.com/meta) uses CIDR; no hostnames available.)

Here's what I have so far (using both [Google guava]() and [commons-api-math](https://github.com/jgonian/commons-ip-math) libs to support ipv4/ipv6 and CIDR):

##### src/main/java/org/jenkinsci/plugins/gwt/whitelist/WhitelistVerifier.java:
```java
import com.google.guava;
import com.github.jgonian;

// ...
  /**
    Returns true if whitelistHost CIDR block contains remoteHost; supports
    ipv4/ipv6.
   */
  static boolean verifyCIDR(
    final String remoteHost,
    final String whitelistHostCIDR,
    final String whitelistHostIP)
    throws WhitelistException {
    Boolean isMatched = false;
    AbstractIpRange whitelistHostRange;

    int whitelistHostLength = InetAddresses.forString(whitelistHostIP).getAddress().length;
    if (whitelistHostLength === 4) {
      whitelistHostRange = Ipv4Range.parse(whitelistHost);
    } else if (whitelistHostLength === 16) {
      whitelistHostRange = Ipv6Range.parse(whitelistHost);
    }

    return whitelistHostRange.contains(remoteHost);
  }

  /**
    Returns true if whitelistHost is equal to remoteHost; supports ipv4/ipv6.
   */
  static boolean verifyIP(
    final String remoteHost,
    final String whitelistHost)
    throws WhitelistException {
    Boolean isMatched = false;
    AbstractIP whitelistIP;

    int whitelistHostLength = InetAddresses.forString(whitelistHost).getAddress().length;
    if (whitelistHostLength === 4) {
      whitelistIP = Ipv4.parse(whitelistHost);
    } else if (whitelistHostLength === 16) {
      whitelistIP = Ipv6.parse(whitelistHost);
    }

    return whitelistIP.contains(remoteHost);
  }

  // TODO: Add tests and CIDR/IP range notation validation to input fields.
  static void whitelistVerify(
    final String remoteHost,
    final WhitelistItem whitelistItem,
    final Map<String, List<String>> headers,
    final String postContent)
    throws WhitelistException {

    String whitelistHost = whitelistItem.getHost();

    boolean isRemoteHostMatched = false;
    if (whitelistHost.equalsIgnoreCase(remoteHost)) {
      isRemoteHostMatched = true;
    } else {
      // TODO: Add support for IP ranges. E.g. 1.2.3.4-1.2.3.5.
      String[] hostParts = whitelistHost.split("/");

      if (hostParts.length == 2) {
        String whitelistHostIP = hostParts[0];
        isRemoteHostMatched = verifyCIDR(remoteHost, whitelistHost, whitelistHostIP)
      } else {
        isRemoteHostMatched = verifyIP(remoteHost, whitelistHost)
      }
    }

    if (isRemoteHostMatched) {
      if (whitelistItem.isHmacEnabled()) {
        // ... HMAC verification
        return;
      }
      return;
    }
    throw new WhitelistException(
        "Sending host \"" + remoteHost + "\" was not matched by whitelist.");
  }
// ...
```

A less generic fork specifically focused on a service like GitHub might be useful, even if just to grok that meta url; simplifying this to just the HMAC settings.

**Comment by tomasbjerre** [comment]
Looks promising @AbsoluteOther are you planning a pull request?

**Comment by AbsoluteOther** [comment]
@tomasbjerre I should have time soon; if not this weekend, next week.

**Comment by tomasbjerre** [comment]
https://github.com/jenkinsci/generic-webhook-trigger-plugin/pull/143

**Comment by tomasbjerre** [comment]
@TheTekton @AbsoluteOther @bkruger99 
Releasing this now as 1.63.

@bkruger99 I moved the logic to its own class and added some more informative responses: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/whitelist/HostVerifier.java

I saw you started working on validation for the input-field, but I removed that for now as I dont want dead code in the code base.
