### ISSUE TITLE
Resolve multiple variables

### ISSUE THREAD

**Issue by vajda** [jenkinsci/generic-webhook-trigger-plugin#142]
Hi,

Great plugin!

I have the following workflow. In single repository, I have multiple projects where each project is in one  directory. Then I trigger some 'router' job to determine in which directories are changes. And for each change I send request to generic webhook. This request contains gitlab info, in order for my downstream job to know where to add a note on successful/failed build.

My question is, I'm sending json as POST body in this request that has a lot of `gitlab*` variables.
JSON looks like:
```
{
"gitlabSourceBranch":"..",
"gitlabTargetBranch":"...",
...
}
```
Is there a way to resolve all those variables within the job with single expression and single variable name?
I know I can do it one by one, but is a bit bothersome.

**Comment by tomasbjerre** [comment]
Yes. That expression just: $

**Comment by vajda** [comment]
But that way I cannot reference the variable in git configuration.
For example, I cannot have branch specifier defined as: `origin/${gitlabSourceBranch}`

**Comment by tomasbjerre** [comment]
Yoy will need to figure out what name the variable gets that holds that
value. And use that variable with the git plugin.

Perhaps this example helps:

https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/jsonpath.feature#L34

Den tors 7 nov. 2019 16:30Vladimir Vajda <notifications@github.com> skrev:

**Comment by vajda** [comment]
Oh, I haven't noticed that variables are actually expanded with `_`.
That is great!
Thanks @tomasbjerre !
