### ISSUE TITLE
How to pick up a newly created branch

### ISSUE THREAD

**Issue by allidev** [jenkinsci/generic-webhook-trigger-plugin#148]
Great plugin! I wonder if it is possible to automatically pick up a newly created feature branch. This is my current configuration in Jenkinsfile:
```
        pipelineTriggers([
            [$class: 'GenericTrigger', genericVariables: [
                [key: 'ref', value: '$.ref'],
            ],
            causeString: 'Triggered by $ref',
            token: 'test1234',
            regexpFilterExpression: "^refs/heads/" + env.BRANCH_NAME + "\$",
            regexpFilterText: '$ref',
            printContributedVariables: false,
            printPostContent: false
            ],
        ])
```
The current setup will be triggered for existing branches, however, if I create a new branch, nothing will happen.
Generic-Webhook-Trigger version is `1.63`
Jenkins version is `2.190.1`

**Comment by tomasbjerre** [comment]
Im guessing you are using multibranch pipeline. And you need to trigger a scan to detect the new branch?

**Comment by allidev** [comment]
I am using Github Organization plugin now and it does not provide access to payload from webhook. Our current use cases requires us to have access to payload from within Jenkinsfile so that I can customize the job. Generic Webhook Trigger provides great support for payload access. 
However, in GO set up, a newly created branch will be picked up automatically and I don't need to scan the repo. I would like to see if I can replicate the behavior in Generic Webhook Trigger setting.

**Comment by tomasbjerre** [comment]
What you can do with this plugin is to use it with multibranch pipeline. It is described in the readme.

**Comment by tomasbjerre** [comment]
Also note that you can create an ordinary pipeline job, not multibranch, and trigger that same job from any number of repositories. And you do not need the `regexpFilterExpression` and `regexpFilterText` unless that is your use case.
