### ISSUE TITLE
How to specify a specific branch？

### ISSUE THREAD

**Issue by xuliugen** [jenkinsci/generic-webhook-trigger-plugin#15]
Hello!
When I use this plugin，And I want to specify a specific branch! But I don't know how to set up!

Generic Webhook Trigger |  
  | Post content parameters | 
  | Header parameters | 
  | Request parameters | 
Optional filter
  | Expression |  
  | Text |  

Can you write any document to help us? Thanks!

**Comment by tomasbjerre** [comment]
Maby the response in #14 can help you?

**Comment by xuliugen** [comment]
Thanks!  @tomasbjerre
