### ISSUE TITLE
How to prevent logging of received payload by default

### ISSUE THREAD

**Issue by ORESoftware** [jenkinsci/generic-webhook-trigger-plugin#153]
I see this noise in the Jenkins console for a job:

![Screen Shot 2020-01-21 at 1 52 32 PM](https://user-images.githubusercontent.com/11139560/72846453-78839f00-3c55-11ea-8693-684d317bede5.png)

is there any way to tell the plugin not to log that?

**Comment by tomasbjerre** [comment]
Yes there is an option to print poat content that you have enabled. Just set it to falsenor uncheck if using gui.
