### ISSUE TITLE
How do i filter from a JSONArray

### ISSUE THREAD

**Issue by avatsyain** [jenkinsci/generic-webhook-trigger-plugin#154]
My case is I get labels on PR as JSONArray. I need to check for unavailability of a particular label. if it is not present then only trigger.

I went through the feature files. I do not see any example of this. Please guide.

The job should trigger when,
1. "labels" is empty array.
2. "labels" array do not have any JSON object having "name": "documentation"

{
    "labels": [
        {
            "id": 144,
            "node_id": "MD",
            "url": "https://api.github.com/repos/",
            "name": "bug",
            "color": "d73",
            "default": true,
            "description": "Something isn't working"
        },
        {
            "id": 147,
            "node_id": "MDU",
            "url": "https://api.github.com/repos/",
            "name": "documentation",
            "color": "007a",
            "default": true,
            "description": "Improvements or additions to documentation"
        }
    ]
}

**Comment by tomasbjerre** [comment]
Like this? https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/array-without-attribute-and-avalue.feature

**Comment by avatsyain** [comment]
Yep. Thanks for the help again.
One quick question if it is matching why is it giving [7]? What is the logic behind it?

**Comment by tomasbjerre** [comment]
There are 7 attributes in the object. Looks strange but should work as we
only need to check if the filtered list is empty or not.

Den fre 24 jan. 2020 08:30avatsyain <notifications@github.com> skrev:

**Comment by avatsyain** [comment]
This suffice my purpose. Thanks.
