### ISSUE TITLE
No JSON Response in v1.66

### ISSUE THREAD

**Issue by emillerccb** [jenkinsci/generic-webhook-trigger-plugin#155]
I just upgraded Jenkins and the Generic Webhook Trigger Plugin. My plugin version went from 1.52 to 1.66. I am able to successfully trigger jobs with a curl, but I'm no longer receiving a JSON response...is this expected? I've since gone through several cycles of downgrading and upgrading the plugin (with no other changes to Jenkins), and 1.52 consistently returns a payload, but 1.66 does not.

 * Plugin version - 1.66 (previously 1.52)
 * Jenkins version - 2.204.1
 * I'm running a webhook called Test Job with almost no configuration:
   * Token is configured and in use
   * Everything else is set to the default configuration (of note, silentResponse is **false**. I verified this in the job and in the config.xml, and even tried turning it off and on with no effect)

The curl I'm making (in essence):
  curl -X POST -H "token: abc123" -H "Content-Type: application/json" "https://myjenkinsserver.example.com/generic-webhook-trigger/invoke"

In 1.52, I receive the following response:
`{
   "status":"ok",
   "data":{
      "triggerResults":{
         "Test Job":{
            "regexpFilterExpression":"",
            "triggered":true,
            "resolvedVariables":{},
            "regexpFilterText":"",
            "id":307912,
            "url":"queue/item/307912/"
         }
      }
   }
}`

In 1.66, I don't receive any response body (just a 200)

In both cases, the job is successfully triggered and run.

I've tried all other forms of the curl (passing in Authorization Bearer or Token in the headers) to no avail.

Maybe I'm doing something wrong, or this feature changed since we last updated, but I don't see any documentation that says it should have changed. The JSON response was an important part of the way we communicate status to our CI/CD system, any help would be appreciated!

Eric

**Comment by tomasbjerre** [comment]
I tried Jenkins 2.150.1 and 2.204.1. In both cases:
```bash
curl -X POST -H "token: abc123" -H "Content-Type: application/json" "http://localhost:8080/jenkins/generic-webhook-trigger/invoke" --verbose
* Expire in 0 ms for 6 (transfer 0x562f0e4b35c0)
* Expire in 1 ms for 1 (transfer 0x562f0e4b35c0)
...
* Expire in 0 ms for 1 (transfer 0x562f0e4b35c0)
* Expire in 0 ms for 1 (transfer 0x562f0e4b35c0)
* Expire in 0 ms for 1 (transfer 0x562f0e4b35c0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x562f0e4b35c0)
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /jenkins/generic-webhook-trigger/invoke HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.0
> Accept: */*
> token: abc123
> Content-Type: application/json
> 
< HTTP/1.1 200 OK
< Date: Wed, 29 Jan 2020 05:01:42 GMT
< X-Content-Type-Options: nosniff
< Stapler-Trace-001: -> evaluate(<hudson.model.Hudson@5ebd6ee9> :hudson.model.Hudson,"/generic-webhook-trigger/invoke")
< Stapler-Trace-002: -> evaluate(((StaplerProxy)<hudson.model.Hudson@5ebd6ee9>).getTarget(),"/generic-webhook-trigger/invoke")
< Stapler-Trace-003: -> evaluate(<hudson.model.Hudson@5ebd6ee9>.getDynamic("generic-webhook-trigger",...),"/invoke")
< Stapler-Trace-004: -> evaluate(<org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver@375d6e70> :org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver,"/invoke")
< Stapler-Trace-005: -> <org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver@375d6e70>.doInvoke(...)
< Content-Type: application/json;charset=utf-8
< Content-Length: 326
< Server: Jetty(9.4.5.v20170502)
< 
* Connection #0 to host localhost left intact
{"jobs":{"Generic Job Example":{"regexpFilterExpression":"aRegExp","triggered":false,"resolvedVariables":{"VARIABLE_FROM_POST":""},"regexpFilterText":"","id":0,"url":""},"asd":{"regexpFilterExpression":"","triggered":true,"resolvedVariables":{},"regexpFilterText":"","id":1,"url":"queue/item/1/"}},"message":"Triggered jobs."}
```

Perhaps you can find some hint in the changelog:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/CHANGELOG.md

You can also manually install other versions to pinpoint when this happens:
https://updates.jenkins.io/download/plugins/generic-webhook-trigger/

**Comment by emillerccb** [comment]
Thanks for the response @tomasbjerre. It appears that 1.66 introduced the breaking change for me, because 1.65 works. I'm curious, are you testing with Java 8 or 11? I'm on Java 8 but I notice you've got the JAXB dependency listed so maybe you are testing with Java 11?

Looking through the commit, I can't determine what the problem is or what I might change to get it working again, but it appears that my instance of Jenkins is not handling the new JSON response properly.

**Comment by tomasbjerre** [comment]
I made these test, seems to work for me. Can you repeat it in Docker?

With java11 jenkins 2.204.2:
`docker run -p 8080:8080 jenkins/jenkins:lts-jdk11`

```
curl -X POST -H "token: abc123" -H "Content-Type: application/json" "http://localhost:8080/generic-webhook-trigger/invoke" --verbose
* Expire in 0 ms for 6 (transfer 0x559f3888c5c0)
* Expire in 1 ms for 1 (transfer 0x559f3888c5c0)
...
* Expire in 0 ms for 1 (transfer 0x559f3888c5c0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x559f3888c5c0)
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /generic-webhook-trigger/invoke HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.0
> Accept: */*
> token: abc123
> Content-Type: application/json
> 
< HTTP/1.1 200 OK
< Date: Wed, 29 Jan 2020 17:40:55 GMT
< X-Content-Type-Options: nosniff
< Content-Type: application/json;charset=utf-8
< Content-Length: 168
< Server: Jetty(9.4.z-SNAPSHOT)
< 
* Connection #0 to host localhost left intact
{"jobs":{"asdasd":{"regexpFilterExpression":"","triggered":true,"resolvedVariables":{},"regexpFilterText":"","id":1,"url":"queue/item/1/"}},"message":"Triggered jobs."}
```

With java 8, jenkins 2.190.1
`docker run -p 8080:8080 jenkins/jenkins:lts`

```bash
curl -X POST -H "token: abc123" -H "Content-Type: application/json" "http://localhost:8080/generic-webhook-trigger/invoke" --verbose
* Expire in 0 ms for 6 (transfer 0x562833cfd5c0)
* Expire in 1 ms for 1 (transfer 0x562833cfd5c0)
...
* Expire in 0 ms for 1 (transfer 0x562833cfd5c0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x562833cfd5c0)
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /generic-webhook-trigger/invoke HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.0
> Accept: */*
> token: abc123
> Content-Type: application/json
> 
< HTTP/1.1 200 OK
< Date: Wed, 29 Jan 2020 17:46:26 GMT
< X-Content-Type-Options: nosniff
< Content-Type: application/json;charset=utf-8
< Content-Length: 170
< Server: Jetty(9.4.z-SNAPSHOT)
< 
* Connection #0 to host localhost left intact
{"jobs":{"adasdasd":{"regexpFilterExpression":"","triggered":true,"resolvedVariables":{},"regexpFilterText":"","id":1,"url":"queue/item/1/"}},"message":"Triggered jobs."}
```

**Comment by tomasbjerre** [comment]
Did you figure this out?

**Comment by Roland0511** [comment]
i have the same issue after upgrade to v1.66

**Comment by tomasbjerre** [comment]
And can you repeat it in docker containers, as I described above?

**Comment by amzuko** [comment]
BTW, thank you @tomasbjerre for making this plugin available.

I've reproduced this with ```docker run -p 8080:8080 jenkins/jenkins:lts-jdk11```. I recently added the plugin to our jenkins master, so have not tested versions below 1.67.

I've configured one job to take one variable:
![image](https://user-images.githubusercontent.com/601612/82067161-30194280-9685-11ea-96e9-9722545efafb.png)

And a token:
![image](https://user-images.githubusercontent.com/601612/82067189-3d363180-9685-11ea-9dd0-f20a18cd38df.png)



When I curl against this job, I see that no variables have been extracted, and similarly see nothing in the job logs:
```
amzuko@LAPTOP-4LISPK38:/mnt/c/WINDOWS/system32$ curl -vs -H "Content-Type: application/json" -X POST -d '{"foo":"bar"}' http://localhost:8080/generic-webhook-trigger/invoke?token=TokenTime
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /generic-webhook-trigger/invoke?token=TokenTime HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 13
>
* upload completely sent off: 13 out of 13 bytes
< HTTP/1.1 200 OK
< Date: Fri, 15 May 2020 15:21:23 GMT
< X-Content-Type-Options: nosniff
< Content-Type: application/json;charset=utf-8
< Content-Length: 174
< Server: Jetty(9.4.27.v20200227)
<
* Connection #0 to host localhost left intact
{"jobs":{"ajob":{"regexpFilterExpression":"","triggered":true,"resolvedVariables":{"Foo":""},"regexpFilterText":"","id":8,"url":"queue/item/8/"}},"message":"Triggered jobs."}
```

Logs:
```
Generic Cause
Running as SYSTEM
[EnvInject] - Loading node environment variables.
Building in workspace /var/jenkins_home/workspace/ajob
GenericWebhookEnvironmentContributor
 Received:

{"foo":"bar"}


Contributing variables:

    Foo = 


Finished: SUCCESS
```

Any ideas?

**Comment by amzuko** [comment]
I should amend this to say that the primary issue I’m seeing is extracting variables from the post body correctly.

**Comment by amzuko** [comment]
Ah -- I'm a fool. The trailing '.' on my jsonpath queries seems to have been making trouble.

**Comment by tomasbjerre** [comment]
@amzuko sounds like you solved it! I'm closing this issue because of no response from original author.
