### ISSUE TITLE
PR job is processed under the same job for a branch

### ISSUE THREAD

**Issue by modernNeo** [jenkinsci/generic-webhook-trigger-plugin#156]
I was able to finally get the plugin working so that I could print the json payload from github in jenkins but now I have a new issue.

In my environment, there is the main repo which has the branch `do_not_merge`. This was the first branch that was pushed to after the webhook got changed from `/github-webhook` to `/generic-webhook-trigger/invoke`.

Then, I was testing something else out which required me to fork the main repo to my own account, and then open a PR to the main repo's master branch from my own fork's master.

However, on Jenkins, i noticed that instead of creating a new job in the multibranch pipeline job for the main repo under "Pull Requests", it instead processed the trigger from the PR under the job `do_not_merge` that is used for the branch `do_not_merge`.

However, when I look at the value of the json that is getting printed when it is processing the push to the PR, it is indeed the correct value but it is still making Jenkins checkout the wrong branch.

The Jenkinsfile used in `do_not_merge`

```
pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    triggers{
        GenericTrigger(
            genericVariables: [
                [key: 'jsonvalue', value: '$']
            ],
        )
    }
    stages {
        stage('Validate Formatting') {
            steps {
                sh "echo $jsonvalue"
            }
        }
    }
}
```

The top of the Jenkinsfile used in my own repo's master

```
pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    triggers{
        GenericTrigger(
            genericVariables: [
                [key: 'jsonvalue', value: '$']
                [key: 'repository', regexpFilter: '[^a-z_-]', value: '$.repository']
            ],
            causeString: 'Triggered on $ref',
     regexpFilterExpression: 'generic $ref',
     regexpFilterText: '$repository refs/heads/' + BRANCH_NAME,
     printContributedVariables: true,
     printPostContent: true
        )
    }
    stages {
        stage('Validate Formatting') {

```
Jenkins Job console log

```
Generic Cause
23:39:37 Connecting to https://api.github.com using csss-admin/****** (csss-admin-github-creds)
Obtained CI/server_scripts/Jenkinsfile from f82dc66bd2a0c7e07b390881f37c22132985063e
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] node
Running on Jenkins in /var/jenkins_home/workspace/build_wall_e_dont_merge
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Declarative: Checkout SCM)
[Pipeline] checkout
using credential csss-admin-github-creds
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/CSSS/wall_e.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/CSSS/wall_e.git
 > git --version # timeout=10
using GIT_ASKPASS to set credentials csss-admin-github-creds
 > git fetch --no-tags --progress -- https://github.com/CSSS/wall_e.git +refs/heads/dont_merge:refs/remotes/origin/dont_merge # timeout=10
Checking out Revision f82dc66bd2a0c7e07b390881f37c22132985063e (dont_merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f f82dc66bd2a0c7e07b390881f37c22132985063e # timeout=10
Commit message: "trying to see if the payload can be accessed via the jenkinsfile"
 > git rev-list --no-walk f82dc66bd2a0c7e07b390881f37c22132985063e # timeout=10
[Pipeline] }
[Pipeline] // stage
[Pipeline] withEnv
[Pipeline] {
[Pipeline] stage
[Pipeline] { (Validate Formatting)
[Pipeline] sh
+ echo {action:synchronize,number:257,pull_request:{url:https://api.github.com/repos/CSSS/wall_e/pulls/257,id:370573971,node_id:MDExOlB1bGxSZXF1ZXN0MzcwNTczOTcx,html_url:https://github.com/CSSS/wall_e/pull/257,diff_url:https://github.com/CSSS/wall_e/pull/257.diff,patch_url:https://github.com/CSSS/wall_e/pull/257.patch,issue_url:https://api.github.com/repos/CSSS/wall_e/issues/257,number:257,state:open,locked:false,title:no need to approve: test pr,user:


```
Jenkins vers 2.207
Generic Webhook Trigger Plugin vers 1.66

**Comment by tomasbjerre** [comment]
Your first jenkinsfile has no filter, it will always trigger.

Not really sure what your question is?

**Comment by modernNeo** [comment]
to be more verbose, my issue is that when using a multibranch pipeline job, each branch and PR gets its own specific job under the overarching repo multibranch pipeline job.



My problem right now though is that there is one branch under the wall_e repo that has the `GenericTrigger` option in its Jenkinsfile, it is called `dont_merge`. and I have also made a fork of the wall_e repo under my own account and added the Jenkinsfile to the master under my own wall_e repo and made a PR to the main repo.

The issue I was experiencing was that any jobs for that PR that would normally be under a job specifically for that PR but in my case, the PR jobs were getting processed under the same job that was created for `dont_merge`.

I took your solution and modified the Jenkinsfile for `dont_merge` like so:

```
pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }
    triggers{
        GenericTrigger(
            genericVariables: [
                [key: 'jsonvalue', value: '$']
            ],
            causeString: 'Triggered on $ref',
            regexpFilterExpression: 'generic $ref',
            regexpFilterText: '$repository refs/heads/' + BRANCH_NAME,
            printContributedVariables: true,
            printPostContent: true
        )
    }
    
    stages {
        stage('Validate Formatting') {
            steps {
                sh "echo $jsonvalue"
            }
        }
    }
}
```

And now none of my jobs are getting built and tested by Jenkins. 
On Github, for each webhook request, the response the Github is getting back from Jenkins after sending the request for `dont_merge` or the PR is just 

```
{
  "jobs": {
    "build wall_e/dont_merge": {
      "regexpFilterExpression": "generic $ref",
      "triggered": false,
      "resolvedVariables": {
        "jsonvalue": "{\"action\":\"synchronize\",\"number\":257,\"pull_request\":{\"url\":\"https://api.github.com/repos/CSSS/wall_e/pulls/257\"",
        "jsonvalue_action": "synchronize",
        "jsonvalue_after": "bb4c5b8acc1b976c9840c843762ef577fcaf803a",
        "jsonvalue_before": "a69393d5519e4766b1bebb0327b45144ec376b3e",
        "jsonvalue_number": "257",
      },
      "regexpFilterText": "$repository refs/heads/dont_merge",
      "id": 0,
      "url": ""
    }
  },
  "message": "Triggered jobs."
}
```

The above responses has been cut down in the `jsonvalue` to remove unnecessary fluff

Hopefully that was more clear.

**Comment by tomasbjerre** [comment]
You are using the $repository variable but you have not configured any variable with that name.

**Comment by modernNeo** [comment]
My updated Jenkinsfile is now

```
pipeline {
    agent any
    options {
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
    }

    triggers{
        GenericTrigger(
            genericVariables: [
                [key: 'jsonvalue', value: '$']
                [key: 'repository', regexpFilter: '[^a-z_-]', value: '$.repository']
            ],
            causeString: 'Triggered on $ref',
            regexpFilterExpression: 'generic $ref',
            regexpFilterText: '$repository refs/heads/' + BRANCH_NAME,
            printContributedVariables: true,
            printPostContent: true
        )
    }
    stages {
        stage('Validate Formatting') {
            steps {
                sh "echo $jsonvalue"
            }
        }
    }
}

```

and jenkins is still not processing any of the incoming triggers, it just returns this response to GitHub

```
{
  "jobs": {
    "build wall_e/dont_merge": {
      "regexpFilterExpression": "generic $ref",
      "triggered": false,
      "resolvedVariables": {
        "jsonvalue": "{\"action\":\"synchronize\",\"number\":257,\"pull_request\":{\"url\":\"https://api.github.com/repos/CSSS/wall_e/pulls/257\"",
        "jsonvalue_action": "synchronize",
        "jsonvalue_after": "bb4c5b8acc1b976c9840c843762ef577fcaf803a",
        "jsonvalue_before": "a69393d5519e4766b1bebb0327b45144ec376b3e",
        "jsonvalue_number": "257",
      },
      "regexpFilterText": "$repository refs/heads/dont_merge",
      "id": 0,
      "url": ""
    }
  },
  "message": "Triggered jobs."
}
```

This is my webhook trigger `JENKINS_URL/generic-webhook-trigger/invoke`

**Comment by tomasbjerre** [comment]
Looks like you dont have the ref variable configured.

And you should also check what the repository variable actually resolves to.

**Comment by modernNeo** [comment]
I tried playing with it a little more today but to be honest, I need better documentation to be able to understand what I am doing. the only places I can find are the [readme](https://github.com/jenkinsci/generic-webhook-trigger-plugin) and the [plugins page](https://plugins.jenkins.io/generic-webhook-trigger/) on jenkins.

What I am specifically looking for is explantions of what these keywords do: `causeString`, `regexpFilterText`, `regexpFilterExpression`, `printContributedVariables`, `printPostContent`

What my object is, is to be able to have the script run the job for a PR using the name of the branch that it originated from [if it is a branch that is from the main repo] rather than having to use the branch variable that is set to "PR-XX".

**Comment by modernNeo** [comment]
@tomasbjerre can I get some assistance on this?

**Comment by modernNeo** [comment]
@tomasbjerre is it not possible to get help on this?

**Comment by tomasbjerre** [comment]
I dont understand what you are trying to do. A proper clear explanation is needed in order to get help.

"explantions of what these keywords" and "better docume tation" is not something I can work with.
