### ISSUE TITLE
500 error using smee trigger and bitbucket

### ISSUE THREAD

**Issue by sona1111** [jenkinsci/generic-webhook-trigger-plugin#157]
* Plugin version used.
1.66
 * Jenkins version used.
2.204.2

I am using bitbucket cloud and smee as described in this document: https://jenkins.io/blog/2019/01/07/webhook-firewalls/ . From what I understand, a 500 error is received when trying to post to the jenkins server. I have attached a fairly detailed log of the curl response provided by smee. Please let me know what other information I can gather to help debug this. 

Thanks for taking a look!

[smee_error2.txt](https://github.com/jenkinsci/generic-webhook-trigger-plugin/files/4156511/smee_error2.txt)

**Comment by tomasbjerre** [comment]
And it works when using curl without smee?

Are you sure Jenkins is on 127.0.0.1:8080/ and not 127.0.0.1:8080/jenkins?

I dont see anything in the log proving that the plugin was actually invoked.

**Comment by tomasbjerre** [comment]
A 500 from the plugin will have this response: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/GenericWebHookRequestReceiver.java#L138

**Comment by sona1111** [comment]
Hi @tomasbjerre , thank you for the follow up. I have tried the curl from the new issue screen. The server is on 8080 and not 8080/jenkins. :

```
curl -v -H "Content-Type: application/json" -X POST -d '{ "app":{ "name":"GitHub API", "url":"http://developer.github.com/v3/oauth/" }}' http://localhost:8080/generic-webhook-trigger/invoke?token=sometoken
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /generic-webhook-trigger/invoke?token=sometoken HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 79
> 
* upload completely sent off: 79 out of 79 bytes
< HTTP/1.1 404 Not Found
< Date: Wed, 05 Feb 2020 16:26:26 GMT
< X-Content-Type-Options: nosniff
< Content-Type: application/json;charset=utf-8
< Content-Length: 275
< Server: Jetty(9.4.z-SNAPSHOT)
< 
* Connection #0 to host localhost left intact
{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@jenkins/generic-webhook... "}
```
 
(I tried with a token too, and that worked fine to trigger my job)
So should I assume this is a smee error and report the bug to them? 

Thank you anyway.

**Comment by sona1111** [comment]
Ok, I think I have found the same issue opened already here: https://github.com/probot/smee-client/issues/116

Sorry to bother you!
