### ISSUE TITLE
Support for trigger conditions in jenkins declarative pipeline

### ISSUE THREAD

**Issue by ReddytoRumble** [jenkinsci/generic-webhook-trigger-plugin#158]
I have a declarative jenkins pipeline that executes certain stages based on a specific set of conditions. One of the ways that we control the stage execution within our pipeline is to use the [when](https://jenkins.io/doc/book/pipeline/syntax/#when) conditional when defining stages.
We can use the `triggeredBy` condition to exeute a stage based on the type of event that was used to start the jenkins job. Is it possible to control stage execution within the pipeline using this condition?

```
stage("Deploy to QA") {
      agent { label 'master' }
      when {
        beforeAgent true
         triggeredBy { genericTrigger }
        }
     echo "deploying to qa"
      }
```
Not sure if I have the right trigger name but it didn't seem to work for me when I tried it

**Comment by tomasbjerre** [comment]
Perhaps:
```
stage("Deploy to QA") {
      agent { label 'master' }
      when {
         beforeAgent true
         triggeredBy 'GenericTrigger'
      }
      echo "deploying to qa"
}
```

**Comment by tomasbjerre** [comment]
Did it work?

**Comment by tomasbjerre** [comment]
no response, closing

**Comment by KINGMJ** [comment]
@ReddytoRumble I use `GenericCause` , it works

```
stage('Deploy'){
            when{
                triggeredBy 'GenericCause'
            }
            steps{
                 sh '''
                    echo "aha, it works"
                   '''
            }
        }

```
