### ISSUE TITLE
How to Generic Trigger Access Variables in Pipeline?

### ISSUE THREAD

**Issue by jefdo** [jenkinsci/generic-webhook-trigger-plugin#16]
So, this example is shown for users who are using a Pipeline.
`
node {
 properties([
  pipelineTriggers([
   [$class: 'GenericTrigger',
    genericVariables: [
     [expressionType: 'JSONPath', key: 'variable1', value: 'expression1'],
     [expressionType: 'JSONPath', key: 'variable2', value: 'expression2']
    ],
    regexpFilterText: '',
    regexpFilterExpression: ''
   ]
  ])
 ])

 stage("build") {
  sh '''
  echo Build
  '''
 }
}
`

But how can we access variable1, and variable2 from within stage build? It may be a good idea to make the example echo similar to what the Job DSL example had.

**Comment by tomasbjerre** [comment]
Does not $variable1 work?

**Comment by jefdo** [comment]
It does not,
hitting the JENKINS_URL/generic-webhook-trigger/invoke
with
![image](https://user-images.githubusercontent.com/29634950/28733929-47cae28e-7393-11e7-9bdf-84b282fbb058.png)

![image](https://user-images.githubusercontent.com/29634950/28733993-95cf8142-7393-11e7-8c97-5ab6c64cbeb8.png)

Gives me...
![image](https://user-images.githubusercontent.com/29634950/28733898-1164dfe2-7393-11e7-8ccd-a9da7f77eb7c.png)

**Comment by jefdo** [comment]
Nvm closed it, I had one thing that was slightly off.

**Comment by tomasbjerre** [comment]
OK =) I updated the readme and added a curl command to make it clearer!

**Comment by jefdo** [comment]
Did you not need the '{}' when you used your variables?

**Comment by tomasbjerre** [comment]
I do not need it. I dont use them in the example i added to the readme.

Den 29 juli 2017 00:22 skrev "jefdo" <notifications@github.com>:
