### ISSUE TITLE
404 Not found, installed in Jenkins docker 

### ISSUE THREAD

**Issue by jlhuerfanor** [jenkinsci/generic-webhook-trigger-plugin#161]
I don't know if I've misunderstood the readme instructions, but I tried with http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=<token> but I got 404 Not found. I installed the plugin in a dockerized jenkins.

Docker Jenkins instance:
jenkins/jenkins:lts
Jenkins ver. 2.222.3
JENKINS_OPTS="--prefix=/jenkins"
Digest:sha256:15fca69266f4cc2107449d9fa2595acf0cbe1584eb425ee6f2fe9cefc9fc4b97 

Plugin version: 1.67
curl:

curl -v -H "Content-Type: application/json" -X POST -d '{ "ref":"refs/heads/master", "repository":{ "full_name":"test/webhooks" } }' http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=<sometoken>

**Comment by tomasbjerre** [comment]
Perhaps you just need to remove `/jenkins` from your `curl` command.

I started with: `docker run -p 8080:8080 jenkins/jenkins:2.222.3`

And I can do:

```bash
curl -v -H "Content-Type: application/json" -X POST -d '{ "ref":"refs/heads/master", "repository":{ "full_name":"test/webhooks" } }' http://localhost:8080/generic-webhook-trigger/invoke?token=
Note: Unnecessary use of -X or --request, POST is already inferred.
* Expire in 0 ms for 6 (transfer 0x5616a6b835c0)
...
* Expire in 1 ms for 1 (transfer 0x5616a6b835c0)
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x5616a6b835c0)
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /generic-webhook-trigger/invoke?token= HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.64.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 75
> 
* upload completely sent off: 75 out of 75 bytes
< HTTP/1.1 404 Not Found
< Date: Sun, 10 May 2020 04:39:45 GMT
< X-Content-Type-Options: nosniff
< Content-Type: application/json;charset=utf-8
< Content-Length: 275
< Server: Jetty(9.4.27.v20200227)
< 
* Connection #0 to host localhost left intact
{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@jenkins/generic-webhook... "}
```

**Comment by jlhuerfanor** [comment]
I think it is an error with the jenkins image. I've made some tests with clean instances of lts-alpine, lts-slim and lts-jdk11 and all they worked as expected. But currently I cannot pull one of those images because all of them have thrown errors installing the recommended plugins. I've notice that they were pushing to lts tag 4 hours ago so I will try again on monday.
