### ISSUE TITLE
Changes pushed to one branch should only trigger build for that branch

### ISSUE THREAD

**Issue by charshin** [jenkinsci/generic-webhook-trigger-plugin#163]
I have a multibranch project with 2 branches, i.e. `jenkins` & `webhook`. They have the same `Jenkinsfile`:
```
pipeline {
  triggers {
    GenericTrigger(
      genericVariables: [
        [key: 'ref', value: '$.ref']
      ],
      token: 'abc123',
      regexpFilterText: '$ref',
      regexpFilterExpression: '^refs/heads/(jenkins|webhook)$',
      printContributedVariables: true,
      printPostContent: true,
    )
  }
  ...
```

When I made a change to branch `jenkins` & pushed, it triggered build for both pipelines `jenkins` & `webhook`. `jenkins` builds on the latest commit that is just pushed, but `webhook` builds on its latest commit which didn't change. What I want is that it should only trigger build for `jenkins` only. Similarly, when I push changes to branch `webhook`, I expect only build for `webhook` triggered, but not `jenkins` or any other builds for that matter. Note that, I do not want pushed changes to any other branches (with Jenkinsfile on it) trigger any build at all. How would I configure? Thanks in advance :)

**Comment by tomasbjerre** [comment]
The readme has an example with: `regexpFilterExpression: 'refs/heads/' + BRANCH_NAME`. Sounds like you want to do exactly what is described in the readme.

**Comment by 478859-anurag** [comment]
Its always picking the last branch built on jenkins. Its not picking the correct branch name in expression
