### ISSUE TITLE
Github not getting notification from jenkins 

### ISSUE THREAD

**Issue by oben-resp** [jenkinsci/generic-webhook-trigger-plugin#164]
Jenkins ver. 2.222.3
Generic Webhook Trigger Plugin vers 1.67

I have everything correctly and i'm able to trigger builds with PR's and jenkins jobs are all successful , but somehow the github webhook does get a notifications or checks from the jobs. Am I missing  something on my setup ?

**Comment by tomasbjerre** [comment]
Follow the issue template
