### ISSUE TITLE
Masked Token Field

### ISSUE THREAD

**Issue by mapham** [jenkinsci/generic-webhook-trigger-plugin#165]
This is not a bug/issue but a request. Could the the Token Field under jenkins job "Jenkins/Configure/Generic Webhook Trigger" be masked, like password fields?
As of now anyone that go jenkins configure job can view the token.

Thanks....

**Comment by tomasbjerre** [comment]
When using a pipeline you can store the token as a string credential. It is explained in the readme.

When using the GUI, no not possible. The "Trigger builds remotely" does not use masking, so i decided not to use it in my plugin.

![image](https://user-images.githubusercontent.com/439571/83718592-a0d4ce80-a635-11ea-881b-e89da8932c1c.png)

Perhaps the Whitelist hosts section in the readme helps you.
