### ISSUE TITLE
Parameters are not copied to new build project

### ISSUE THREAD

**Issue by deona1** [jenkinsci/generic-webhook-trigger-plugin#166]
When creating a new Jenkins build project by copying an existing project, the Generic Webhook Trigger parameters are not copied to the new project.

I have an existing project in Jenkins that is used to build my master repo. The build is triggered via a webhook that sends the branch name as a post content parameter. I want to be able to copy this project (that builds master) and simply change the optional parameter to the name of my branch. The master project is like a template for my branch projects and I just have to change the branch name in the new one. I'm doing this so that other team members won't have to setup the build trigger every time they want to create a Jenkins project for their branch.
Maybe there's a better way to do this but this is the way I currently know. 

 * Plugin version used 1.67
 * Jenkins version used 2.222.3

**Comment by tomasbjerre** [comment]
Missing configuration, see issue template.

**Comment by deona1** [comment]
I didn't have a problem with the execution of the trigger - this is a good plugin. That's why I didn't send the other info. It was a problem in that the settings of this plugin are not copied when you create a new build item by copying an existing build project. There may be a good reason for that. I was just expecting that the settings would be copied.
