### ISSUE TITLE
Question: Is HTTP response to webhook is truncated to 8192 bytes?

### ISSUE THREAD

**Issue by RichardWilder** [jenkinsci/generic-webhook-trigger-plugin#167]
We are using Jenkins 2.204.5 with Generic Webhook Trigger plugin 1.67, generally with good success. 

Recently we observed a failure where the response has been truncated to 8192 characters and thus cannot be parsed as valid JSON. The particular use-case involves a Bitbucket pull-request with numerous comments. 

We use a JSONPath expression of $ to assign the POST request data to variable BB_POST_DATA, so there are a lot of contributed variables. We recognize that a possible work-around would be to trim the amount of contributed variables to only those items from Bitbucket that we specifically require.  
Another work-around might be to select the "Silent response" checkbox. 

So, the question is: Is the a limit to the size of the GWT reply? Or, is there a known limit to what Jenkins core can send?

**Comment by tomasbjerre** [comment]
Im not aware of such a limit.

**Comment by RichardWilder** [comment]
I will capture some data for reproducing the error.

**Comment by RichardWilder** [comment]
Subsequent tests using curl prove that Jenkins and GHT plugin do properly respond with large JSON. 

(FYI my original observations were made using Python and the Requests package. This must be where the problem exists. )

**Comment by RichardWilder** [comment]
Question answered - please close. And thank you for prompt response!
