### ISSUE TITLE
I am using Jenkins and scripted pipeline and all notifications are being sent twice.

### ISSUE THREAD

**Issue by HeidiRechek** [jenkinsci/generic-webhook-trigger-plugin#169]
I am using Jenkins and scripted pipeline and all bitbucketStatusNotify notifications are being sent twice. to Bitbucket cloud

Example commands in my node block 
bitbucketStatusNotify(buildState: 'INPROGRESS', buildKey: 'Build', repoSlug: "${BB_REPO}", commitId: "${SFRA_COMMIT}",buildDescription: "Stage prepare DeployTo Sandboxes "+ currentBuild.getCurrentResult()+" Duration "+currentBuild.durationString.replace(' and counting', ''))
bitbucketStatusNotify(buildState: 'FAILED', buildKey: 'Build', repoSlug: "${BB_REPO}", commitId: "${SFRA_COMMIT}",buildDescription: "Stage "+STAGE_NAME+" "+errMessage)

_Originally posted by @landaumd in https://github.com/jenkinsci/slack-plugin/issues/322#issuecomment-429975620_

**Comment by tomasbjerre** [comment]
Looks like you are using bitbucket branch source plugin.
It has nothing to do with this plugin.
