### ISSUE TITLE
Can we use environment variables in regexpFilterExpression?

### ISSUE THREAD

**Issue by ajaypandit** [jenkinsci/generic-webhook-trigger-plugin#17]
I am trying to set a dynamic filter based on the repo and the job name (we use same Jenkinsfile in all the repos) with following settings:

regexpFilterText: '$repo',
regexpFilterExpression: '/${env.JOB_NAME}.split("/")[1]/g'

The $repo is correctly set to the repo name e.g. template-service and I want to match it with the repo name in the job e.g. ORG/template-service/master. Even with this filter, the webhook is triggering all the jobs. I tried changing '${env.JOB_NAME}' to 'env.JOB_NAME' but that does not work either. Is it possible to use environment variables in regexpFilterExpression? Why is this filter triggering all the jobs?

**Comment by tomasbjerre** [comment]
Here is a working example of that: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/sandbox/sandbox.jenkinsfile

**Comment by ajaypandit** [comment]
It's working now. Thanks!

**Comment by tomasbjerre** [comment]
no problem!

**Comment by thomasbinny1989** [comment]
im trying the environment variable substitution on a declarative pipeline but it doesnt seem to work any suggestions?

    
     regexpFilterText: '$ref $changed_files $commit_user',
     regexpFilterExpression: "^refs/heads/${env.BRANCH_NAME}\\s(.*\"(${params.BRAND}\\/params.yml).*\"|.*\"(${params.BRAND}\\/.*\\.properties).*\")[^\\s]+?\\s((?!${env.GIT_USER}))"

The variable are part of environment{} in the pipeline template.

**Comment by tomasbjerre** [comment]
You should open a new issue about that. And explain how you are using the plugin so that there is something to investigate.

**Comment by shenmou98** [comment]
> I am trying to set a dynamic filter based on the repo and the job name (we use same Jenkinsfile in all the repos) with following settings:
> 
> regexpFilterText: '$repo',
> regexpFilterExpression: '/${env.JOB_NAME}.split("/")[1]/g'
> 
> The $repo is correctly set to the repo name e.g. template-service and I want to match it with the repo name in the job e.g. ORG/template-service/master. Even with this filter, the webhook is triggering all the jobs. I tried changing '${env.JOB_NAME}' to 'env.JOB_NAME' but that does not work either. Is it possible to use environment variables in regexpFilterExpression? Why is this filter triggering all the jobs?

@ajaypandit  can you share the code

> It's working now. Thanks!

@ajaypandit  Could you please share your worked code?  I have the similar issue.  Thanks so much.
