### ISSUE TITLE
In git hub organisation level triggering one single jenkins pipeline for all changes under that organisation 

### ISSUE THREAD

**Issue by 478859-anurag** [jenkinsci/generic-webhook-trigger-plugin#174]
I have enabled this plugin at organisation level initially with normal github-webhook, which was already triggering Jenkin’s pipeline for multiple repos under an organisation .

With both webhooks in place, I have only added generic trigger in Jenkinsfile for a single branch in a repo with token variable defined in webhook and Jenkinsfile trigger lets say the pipeline name is generictriggerdemo. Now for some reason when I created Jenkins file and pushed the code in a separate repo altogether with no generic trigger lets say the name is githubwebhookdemo. That is also triggering a jenkins build on the jenkins pipeline where I am using generic trigger i.e generictriggerdemo.

 * Plugin version 1.67 used.
 * Jenkins version 2.164 used.
 * Your configuration.
   * Variables configured, names, expressions...
   * Pipeline script (See Pipeline section in README)
 * Build job log
 * Post content received. It can be found in the job execution log. People using GitHub often forget to set the content type in "Manage webhook" when configuring the webhook at GitHub.
 * A `curl` command and its response.
 * Expected result and actual result.

You may also have a look at the test cases as they should answer the most common questions:
 
  https://github.com/jenkinsci/generic-webhook-trigger-plugin/tree/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd

If you are fiddling with expressions, you may want to checkout:

* [This JSONPath site](http://jsonpath.herokuapp.com/)
* [This XPath site](http://www.freeformatter.com/xpath-tester.html)
* [This regexp site](https://jex.im/regulex/)

A Curl command can look something like this:
```
curl -v -H "Content-Type: application/json" -X POST -d '{ "app":{ "name":"GitHub API", "url":"http://developer.github.com/v3/oauth/" }}' http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=sometoken
```

**Comment by 478859-anurag** [comment]
Any code checkin under that github organisation is triggering a job in generictriggerdemo jenkins pipeline

**Comment by tomasbjerre** [comment]
See:
https://github.com/jenkinsci/generic-webhook-trigger-plugin#trigger-only-specific-job

Or open new issue where you follow issue template
