### ISSUE TITLE
Not run the job if filter not match

### ISSUE THREAD

**Issue by maati55** [jenkinsci/generic-webhook-trigger-plugin#176]
Hi,

I need to configure the plugin to **not** run the pipeline job if `$ref` match with `refs/heads/master`, would it be possible to do that? 

something like this `'^(?!refs/heads/master)$'`

Plugin version: 1.67
Jenkins Version: 2.245
Payload:
```
{
  "ref": "refs/heads/master",
...
```

config:
```
  properties([
    pipelineTriggers([
     [$class: 'GenericTrigger',
      genericVariables: [
       [key: 'ref', value: '$.ref'],
       [key: 'ref_type', value: '$.ref_type']
      ],
      causeString: 'Triggered on $ref',
      token: 'tocken123',
      printContributedVariables: true,
      printPostContent: true,
      silentResponse: false,
      regexpFilterText: '$ref',
     ]
    ])
  ])
```

**Comment by tomasbjerre** [comment]
Yes you can use negative lookahead: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/c0cfc1314988ab53676b6e79147ca6acabfd9f8e/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github/github-push-trigger-unless-specific-user.feature#L11

**Comment by maati55** [comment]
Thanks for the prompt reply, sorry to reopen this one again
I have just added it to the config but looks like it doesn't work, job still trigger

```
properties([
    pipelineTriggers([
     [$class: 'GenericTrigger',
      genericVariables: [
       [key: 'ref', value: '$.ref', regexpFilter: '^((?!refs/heads/master))'],
       [key: 'ref_type', value: '$.ref_type']
      ],
      causeString: 'Triggered on $ref',
      token: 'tocken123',
      printContributedVariables: true,
      printPostContent: true,
      silentResponse: false,
      regexpFilterText: '$ref',
     ]
    ])
  ])
```

Received:

`{"ref":"refs/heads/master","before":"de5b6abc6aa6ea...","after":"3243c8e5477e8e6..." ...`

**Comment by tomasbjerre** [comment]
You added it at the wrong place. It should be added on same level as regexpFilterText as regexpFilterExpression. Chevk the readme.
