### ISSUE TITLE
Bitbucket server varaibles not getting printed

### ISSUE THREAD

**Issue by anirudhbagri** [jenkinsci/generic-webhook-trigger-plugin#177]
I have configured this plugin to get trigger using bitbucket webhooks.

In the plugin, I have selected these 2 options

Print post content
Print contributed variables

But in the logs, I neither see the post content nor any contributing variables.

Is there something I missed?
I am using the latest plugin version and bitbucket server.

**Comment by tomasbjerre** [comment]
Use the issue template
