### ISSUE TITLE
Load job variables into plugin

### ISSUE THREAD

**Issue by malachiobadeyi** [jenkinsci/generic-webhook-trigger-plugin#180]
We have a remote Jenkins file which is shared across teams and projects.  Individual build  actions are controled by a yaml file in each teams repo. It would be useful if we could load the yaml file as part of the webhook trigger and trigger a build based on regex matching on variables defined in file. Is that possible? If not do you have any thoughts on how I could achieve the same outcome in a different way?

**Comment by tomasbjerre** [comment]
Perhaps trigger one job in jenkins using this plugin. Let that job clone whatever repo and do that regexp natching on tje yaml. Let it trigger other jobs based on its findings.
