### ISSUE TITLE
Multibranch-pipeline repeatedly prints contributed variables

### ISSUE THREAD

**Issue by Swiftwork** [jenkinsci/generic-webhook-trigger-plugin#184]
Multibranch-pipeline seemingly prints contributed variables for every single step. This behavior is observed across all pipeline implementations regardless of steps used.

 * Plugin version used: 1.67
 * Jenkins version used: 2.235.1

Configuration DSL:
```groovy
String getJobName() {
  def parts = env.JOB_NAME.tokenize('/') as String[]
  return parts.length < 2 ? env.JOB_NAME : parts[parts.length - 2]
}

// ...

GenericTrigger(
  genericVariables: [
    [key: 'ref', value: '$.ref'],
    [key: 'message', value: '$.head_commit.message'],
    [key: 'author', value: '$.head_commit.author.name']
  ],
  causeString: 'Triggered on $ref by $author using GitHub webhook',
  regexpFilterText: '$ref $message',
  regexpFilterExpression: 'refs/heads/' + env.BRANCH_NAME + ' (?!.*\\[skip ci\\]).*', // This branch and all except [skip ci]
  printContributedVariables: true,
  token: getJobName()
)
```
Log excerpt: 
![image](https://user-images.githubusercontent.com/455178/95861716-22660700-0d62-11eb-9033-315cfd0d3fdb.png)

Unfortunately I can't share the pipelines as these are "proprietary". Can you reproduce the same results with the above configuration?

**Comment by tomasbjerre** [comment]
Should be fixed now in `1.88.1` open issue again if not working.
