### ISSUE TITLE
Webhook throwing 403 on Windows when payload includes a URL

### ISSUE THREAD

**Issue by tatebosler** [jenkinsci/generic-webhook-trigger-plugin#185]
I'm having an issue where Jenkins is returning HTTP 403 Forbidden when the value of a body parameter includes a URL.

OS: Windows 10
Jenkins version: 2.249.2
Plugin version: 1.68
Pipeline parameters:
* name `body`, JSONPath expression `$`

Pipeline definition script:
```groovy
node {
    echo "hello world."
    echo body
}
```

Body:
```
{
    "test": "https://github.com/"
}
```

Expected result: I expected the pipeline to be triggered when sending the body above (via curl, Postman, etc).

Actual result: Jenkins throws an HTTP 403 Forbidden error and does not trigger the pipeline.

The body `{"test":"github.com/"}` does work without throwing a 403, and the keys involved don't matter (it seems to be only throwing 403 when a URL is present in a value). Weirdly enough I did a clean install on my Mac and it's working without issues, so I'm not sure if there's something wrong with the Windows version, or if it's misconfigured.

**Comment by tomasbjerre** [comment]
I tried it on Ubuntu, latest version, see no problems.

I configured job like:
![image](https://user-images.githubusercontent.com/439571/96755557-284b9000-13d3-11eb-88ca-6a88e304cc59.png)

Invoke it with:
```
curl -X POST -H "Content-Type: application/json" -d '{ "test": "https://github.com/" }' -vs http://localhost:8080/jenkins/generic-webhook-trigger/invoke*   Trying 127.0.0.1:8080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /jenkins/generic-webhook-trigger/invoke HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 33
> 
* upload completely sent off: 33 out of 33 bytes
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Date: Wed, 21 Oct 2020 17:21:06 GMT
< X-Content-Type-Options: nosniff
< Stapler-Trace-001: -> evaluate(<hudson.model.Hudson@4a2ef7da> :hudson.model.Hudson,"/generic-webhook-trigger/invoke")
< Stapler-Trace-002: -> evaluate(((StaplerProxy)<hudson.model.Hudson@4a2ef7da>).getTarget(),"/generic-webhook-trigger/invoke")
< Stapler-Trace-003: -> evaluate(<hudson.model.Hudson@4a2ef7da>.getDynamic("generic-webhook-trigger",...),"/invoke")
< Stapler-Trace-004: -> evaluate(<org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver@254438db> :org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver,"/invoke")
< Stapler-Trace-005: -> <org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver@254438db>.doInvoke(...)
< Content-Type: application/json;charset=utf-8
< Content-Length: 194
< Server: Jetty(9.4.5.v20170502)
< 
* Connection #0 to host localhost left intact
{"jobs":{"test":{"regexpFilterExpression":"","triggered":true,"resolvedVariables":{"test":"https://github.com/"},"regexpFilterText":"","id":6,"url":"queue/item/6/"}},"message":"Triggered jobs."}
```

Output in Jenkins build log:
```
Generic Cause
Running as SYSTEM
Building in workspace /home/bjerre/workspace/generic-webhook-trigger-plugin/work/workspace/test
GenericWebhookEnvironmentContributor
 Received:

{ "test": "https://github.com/" }


Contributing variables:

    test = https://github.com/


[test] $ /bin/sh -xe /tmp/jenkins5894929860872940229.sh
+ ls
Finished: SUCCESS
```

**Comment by tatebosler** [comment]
Yeah, that's the bit that I'm confused about. It's working fine on my Mac, but it's failing when I run it on Windows. If it helps, this is running on a Windows EC2 instance in AWS.

**Comment by tomasbjerre** [comment]
Are you sure the response does not say something about whitelist? From: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/cbb8355eb12684a2159ba839deba98cd09f13587/src/main/java/org/jenkinsci/plugins/gwt/GenericWebHookRequestReceiver.java#L65

If the 403 comes from the plugin, the whitelist should be the only reason why.

What is the exact response you get with the 403?

**Comment by tatebosler** [comment]
Yeah, we've got the whitelist disabled. Here's the response I'm getting:

```
<html>

<head>
	<title>403 Forbidden</title>
</head>

<body>
	<center>
		<h1>403 Forbidden</h1>
	</center>
</body>
```

Weirdly enough the headers are suggesting that it's an AWS issue, not necessarily Jenkins (the good requests have a header with `Server: Jetty(9.4.30.v20200611)`, and this one has `Server: awselb/2.0`. I'll try poking around there too.

**Comment by tatebosler** [comment]
Update: Yes, it is actually an overly aggressive AWS WAF configuration as opposed to Jenkins' fault. My apologies for the false alarm, I'll go ahead and close this issue out then.
