### ISSUE TITLE
Two webhook POSTs only trigger one job despite unique parameter values

### ISSUE THREAD

**Issue by gongsu832** [jenkinsci/generic-webhook-trigger-plugin#197]
Jenkins version: 2.263.1
Generic Webhook Trigger Plugin version: 1.72

I have a freestyle job setup to receive webhook POSTs from github. When a pull request is merged, two webhook events are POSTed, one is a `pull_request` event with the payload `{"action": "closed", ...}` and the other is a `push` event with the payload `{"ref": "refs/heads/master", ...}`. I have followed the document to make the job parameterized and use the `X-GitHub-Delivery` UUID in the POST header for the unique value. However, I still only get one job triggered which shows two UUIDs in the console output:
```
Github Webhook Event bec5aa10-5489-11eb-9c9f-0b787ea43d19 [pull_request]
Github Webhook Event befb3d4c-5489-11eb-9930-dc17b5ea3fcd [push]
Running as SYSTEM
GenericWebhookEnvironmentContributor
 Received:

{"action":"closed", ...}
```
and the `{"ref": "refs/heads/master", ...}` payload is lost.

**Comment by tomasbjerre** [comment]
Can you supply your full configuration? A screenshot showing the parameters and the plugin configuration. Or Job DSL would also work if that is what you are using.

**Comment by gongsu832** [comment]
@tomasbjerre here is the capture of my job configuration. Thanks.
[jenkins-merge Config [Jenkins].pdf](https://github.com/jenkinsci/generic-webhook-trigger-plugin/files/5805853/jenkins-merge.Config.Jenkins.pdf)

**Comment by tomasbjerre** [comment]
It is because none of the resolved variables from this plugin are being resolved to variable with name of the parameter: `github_webhook_uuid`

You only resolve:

* `github_webhook_payload`
* `x_github_delivery`
* `x_github_event`

**Comment by gongsu832** [comment]
Ahh, thought the parameter name could be arbitrary as long as its default value gets resolved. Changing `github_webhook_uuid` to `x_github_delivery` worked. I now get two triggers. Thanks!

**Comment by tomasbjerre** [comment]
Ok good! The credentials thing should be its own issue.
