### ISSUE TITLE
Unable to select Token Credential

### ISSUE THREAD

**Issue by s390xlinux** [jenkinsci/generic-webhook-trigger-plugin#198]
Jenkins version: 2.263.2
Generic Webhook Trigger Plugin version: 1.72

I created a secret text credential for the "Token Credential" using the "Add" button next to it. But in the pull-down menu nothing shows up so I cannot select the credential (see the attached screenshot). I thought it might be a browser problem so I tried chrome, firefox, and safari but they all behave the same.

![image](https://user-images.githubusercontent.com/20214271/104608347-c310df00-564f-11eb-932b-9331facc0376.png)

**Comment by tomasbjerre** [comment]
I looked at it and it is this probably this problem: https://issues.jenkins.io/browse/JENKINS-64071
Can you verify that?

**Comment by s390xlinux** [comment]
I tried the non-LTS build 2.275 and indeed the problem was fixed. I prefer to stay on LTS so I will just use the plain text Token field for now. Thanks!
