### ISSUE TITLE
How to get the changed_files_0 value from changed_files without [""] of push event

### ISSUE THREAD

**Issue by KevinChris7** [jenkinsci/generic-webhook-trigger-plugin#201]
Hi Team,

I am using the generic variable with regexpFilter to get the directory name alone from the below Payload

### Reproduction steps
- This is the Push Event Payload
```
  "commits": [
    {
      "modified": [
        "base/Dockerfile"
      ]
    }
```
- This is the generic variable i am working with
```
                genericVariable {
                    key("DOCKER_FILE")
                    value("\$.commits[*].['modified','added'][*]")
                    regexpFilter("/Dockerfile")
                    expressionType("JSONPath")
                }
```

### Results

Expected result:
I need only **base** without `[""]` 

Actual result:
`["base"]`

**Comment by tomasbjerre** [comment]
You should have a variable named `DOCKER_FILE_0` that contains only `base`.

If an expression is resolved to an array, there will be variables suffixed with indexes:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/java/org/jenkinsci/plugins/gwt/VariablesResolverRequestParameterTest.java#L56

**Comment by KevinChris7** [comment]
I get this but for manually triggering the job I will have DOCKER_FILE variable only so if I use DOCKER_FILE_0 in Jenkinsfile manual trigger will fail..So is there any workaround

**Comment by tomasbjerre** [comment]
In `Jenkinsfile` you may add:

```groovy
def DOCKER_FILE = params.DOCKER_FILE ?: DOCKER_FILE_0;
```

And use the value of `DOCKER_FILE`.


I tried here:
https://groovy-playground.appspot.com/

```groovy
def params = [
    DOCKER_FILE: 'a'
]
def DOCKER_FILE_0 = "b"
def DOCKER_FILE = params.DOCKER_FILE ?: DOCKER_FILE_0;
println DOCKER_FILE

params = [
]
DOCKER_FILE = params.DOCKER_FILE ?: DOCKER_FILE_0;
println DOCKER_FILE

params = [
    DOCKER_FILE: 'a'
]
DOCKER_FILE_0 = null
DOCKER_FILE = params.DOCKER_FILE ?: DOCKER_FILE_0;
println DOCKER_FILE
```

Will print:
```
a
b
a
```

**Comment by KevinChris7** [comment]
@tomasbjerre DOCKER_FILE will have a value while webhook trigger so it will have the preference over DockerFile_0 as per your example use case..This will again return ["base"]..Kindly correct me If I am wrong

**Comment by tomasbjerre** [comment]
What does your `Jenkinsfile` look like?

What I am suggesting is to, in the `Jenkinsfile`, check if it was triggered by this plugin or manually. Use `DOCKER_FILE_0` if it was the plugin and `params.DOCKER_FILE` if manually triggered.

**Comment by KevinChris7** [comment]
I am using jobdsl so example.groovy where I will have parameters and generic variables as well..In Jenkinsfile will have the scripted pipeline

**Comment by jrichardsz** [comment]
Since JsonPath java implementation is being used, the result always will be a collection: https://stackoverflow.com/a/57599604/3957754

You could try with  array index:  

    $.commits[*].['modified'][0]

![https://ibb.co/9Wvt5q0](https://ibb.co/9Wvt5q0)

In order to remove **/Dockerfile** you will need groovy.

**Comment by tomasbjerre** [comment]
@KevinChris7 what is your problem now that you changed the Jenkinsfile?

**Comment by KevinChris7** [comment]
@tomasbjerre @jrichardsz I have written a groovy function to handle this..Thanks for the support
