### ISSUE TITLE
Builds aren't properly mapped to their PR/Branch

### ISSUE THREAD

**Issue by jonathonbattista** [jenkinsci/generic-webhook-trigger-plugin#202]
Builds from Webhooks arent updated properly and are mapped to the wrong PR/Branch ID:

For example, I built **PR-1** with branch **feat/change-name**.

Now every subsequent Webhook gets built as **PR-1** even though it contains values from different PRs.

Here is the Webhook response from GitHub for **PR-2**.
```
{"jobs":{"generic-webhook/PR-1":{"regexpFilterExpression":"feat/test","triggered":true,"resolvedVariables":{"BRANCH":"feat/test","STATE":"open"},"regexpFilterText":"feat/test","id":10,"url":"queue/item/10/"}},"message":"Triggered jobs."}
```

I thought it was an issue with discovering Branches/PR, but I have the **Multibranch Scan Webhook Trigger** configured.
### Version report

Jenkins and plugins versions report: 

```
jenkins: 2.249.3
generic-webhook-trigger: 1.72
multibranch-scan-webhook-trigger: 1.0.5
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Kubernetes **jenkins/jenkins:lts**
```

### Reproduction steps

- Step 1: Add the example Declarative Jenkinsfile to a GitHub repo
- Step 2: Configured a GitHub webhook using a token
- Step 3: Setup Pipeline using BlueOcean
- Step 4: Scan Repo and run Pipeline once
- Step 5: Create a PR to trigger Pipeline (i.e. PR-1 built as PR-1)
- Step 5: Create another PR to trigger the Pipeline (i.e. PR-2 built as PR-1)
### Results

Expected result:

Each Webhook is built as its respective PR/Branch:

**PR-1** should be built under **PR-1**
**PR-2** should be built under **PR-2**

Actual result:

The Generic Webhook job doesn't get updated and the PR/Branch is built under the wrong ID.

**PR-2** is built under **PR-1**

**Comment by tomasbjerre** [comment]
So this is your pipeline, I assume:

```groovy
pipeline {
  agent any
  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: '$.ref']
     ],
...
     regexpFilterText: '$ref',
     regexpFilterExpression: 'refs/heads/' + BRANCH_NAME
    )
  }
  stages {
    stage('Some step') {
      steps {
        sh "echo $ref"
      }
    }
  }
}
```

The pull-request webhook:
https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#pull_request
Does not contain `$.ref`, so what you are seeing is probably the result of push event:
https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#push

So you have to detect that it is a pull request and resolve whatever variables you need for that. Perhaps something like this would work:

```groovy
     genericVariables: [
      [key: 'ref', value: '$.ref']
      [key: 'pr_id', value: '$.pull_request.id']
     ],
...
     regexpFilterText: '$ref$pr_id',
     regexpFilterExpression: 'refs/heads/' + BRANCH_NAME
```

And in the pipeline build step you will have to check if:

 * `pr_id` is set and if so, it is a PR build.
 * Or if `ref` is set and it is a branch build.

If it is a pr build you probably want to resolve some more variables, and perform the merge before build... this might help:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github/github-pull-request.feature
