### ISSUE TITLE
Backslashes in example bitbucket-server/bitbucket-server-tag.feature

### ISSUE THREAD

**Issue by solarjoe** [jenkinsci/generic-webhook-trigger-plugin#203]
There are several backslashes in the example bitbucket-server/bitbucket-server-tag.feature

I am not that familiar with regex, but my Jenkins complained with a syntax error.

https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/bitbucket-server/bitbucket-server-refs_changed.feature#L7

https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/bitbucket-server/bitbucket-server-refs_changed.feature#L8

https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/bitbucket-server/bitbucket-server-refs_changed.feature#L80

https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/bitbucket-server/bitbucket-server-refs_changed.feature#L84

**Comment by tomasbjerre** [comment]
The backslashes are there to escape the pipe that would otherwise end the table. The table being read by Cucumber. https://cucumber.io/

**Comment by solarjoe** [comment]
Thanks for the reply.
