### ISSUE TITLE
QUESTION: multiple commits trigger multiple jobs,how to terminate old job if running and only keep latest one running? 

### ISSUE THREAD

**Issue by Saurabhj87ST** [jenkinsci/generic-webhook-trigger-plugin#204]
When reporting a bug, please **try** to provide as much information as possible.

 * Plugin version used. = 1.72
 * Jenkins version used. 2.259
 * Your configuration.
 We are using freeform jobs to run sonar scans on every Pr commit, 
our job is taking 20minutes to complete one run, if user commit 3 times in few minutes, it will trigger 3 jobs together as we are using concurrent builds to run, but it does not stop old runs and just let the latest one only running. can you help us how we can achieve that with this plugin? 
we are using github webhooks along with token to run respective job on jenkins. 
 * Expected result and actual result.
We want if a new commit is made and old jobs are still running for old commit on a single PR, it should cancel old builds and only run the latest job.

**Comment by tomasbjerre** [comment]
No such feature in this plugin.

**Comment by Saurabhj87ST** [comment]
Thanks tomasbjerre, do you know if we can achieve this with any other plugin? 
we want to extract PR number base branch and source branch of PR for sonar scan and PR decoration in github. We are currently using this plugin but not sure what can be a substitute of this. Thanks

**Comment by tomasbjerre** [comment]
I dont know how to terminate the ongoing build when a new commitnis pushed.

But it may help to limit the numbernof concurrent builds for each PR to 1. Letting any ongoing build finnish before next, latest, starts.

Another thing to look at might be quiet period.
