### ISSUE TITLE
Triggering is not working with Token Credential ID

### ISSUE THREAD

**Issue by raksit31667** [jenkinsci/generic-webhook-trigger-plugin#206]
### Version report

Jenkins on Docker v2.222
Generic Webhook Plugin v1.72

### Reproduction steps

- Add new credentials on Jenkins

- Configure Job on either UI or DSL script, specify `tokenCredentialId` with the one we have just created.

![Screen Shot 2564-06-02 at 10 12 07](https://user-images.githubusercontent.com/16893636/120419809-5774a780-c38d-11eb-91f9-5e8769abddd3.png)

- Make a HTTP request using

```
POST https://<jenkins-url>/generic-webhook-trigger/invoke?token=<token-here>
```

### Results

Expected result:

It should return HTTP 200 OK with new job running.

Actual result:

It returns HTTP 404 NOT FOUND without any jobs running.

### Additional info

It works if I hardcode `token` input instead of using `tokenCredentialId`.

**Comment by tomasbjerre** [comment]
I tried with Jenkins 2.277.4.

Created a `secret text` credential with id `theid`.

Pipeline:
```groovy
 properties([
  pipelineTriggers([
   [$class: 'GenericTrigger',
    genericVariables: [
     [
      key: 'href',
      value: '$.href'
     ]
    ],

    causeString: 'Triggered on $ref',

    tokenCredentialId: 'theid',

    printContributedVariables: true,
    printPostContent: true,

    silentResponse: false
   ]
  ])
 ])
```

Trigger with Curl:
```shell
curl -vs http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=abc123 2>&1
```

Works for me.

Note that you have to run a pipeline once, to apply the properties to the job. So you can verify what has been applied by inspecting the job. In my case I can see:

![image](https://user-images.githubusercontent.com/439571/120516577-cf63c180-c3cf-11eb-9cd7-0b537da2409b.png)

**Comment by raksit31667** [comment]
Hi @tomasbjerre, thank you for your support.

You are right, I missed the part where I needed to run a pipeline once as documented [here](https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/README.md#pipeline).
