### ISSUE TITLE
Get the list of changed files in the payload for a pull-request event type

### ISSUE THREAD

**Issue by sowmyadass** [jenkinsci/generic-webhook-trigger-plugin#209]
### Feature Request

I am using GitHub and Jenkins in my environment. I have configured Generic Webhook trigger to trigger builds based on Push and Pull request event types in the GitHub repository. 
In a pull request event type, currently the payload contains below details about the PR changes:
    "commits": 17,
    "additions": 8,
    "deletions": 9,
    "changed_files": 2

I have a use case wherein I need to check the list of files changed as part of the PR and do some conditional processing based on it in the jenkins pipeline job. 

I see the list of changed files are a part of the payload when the event type is a "push" but that is not there in the payload when the event is of the type "pull-request". 

Can the payload be enhanced to include the list of changed files for pull-request events or is there already an existing way to do this ?

**Comment by tomasbjerre** [comment]
Like this? https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github/github-push-get-changed-files.feature

**Comment by sowmyadass** [comment]
Thanks for your quick response. I already checked the above link and tried it out earlier today, this works well for push events but not for the pull-request events. The pull-request event payload does not have changed files whereas the push event payload has those listed.

To give you a bit more context around my use case, I am finding a way to trigger a build for a GitHub pull request, only if the changed files in a pull request belong to a specific directory.

For eg: If my GitHub workspace/repository structure looks like:

src/
     a.cpp
     b.cpp
docs/
     README.md
ui/
   abc.js
   def.js

As per my use case, I want to trigger a jenkins build for a pull request event, only if the files changed as part of the pull request has at least one file modified from the ui directory. In other words, there would be no build triggered unless files under ui directory get modified.

**Comment by tomasbjerre** [comment]
Ok. Sounds like a feature request for Github. Not something that can be solves here.
