### ISSUE TITLE
Usage of multibranch pipeline in conjuntion with generic webhook trigger 

### ISSUE THREAD

**Issue by kalidina** [jenkinsci/generic-webhook-trigger-plugin#212]
Jenkins version : 2.235.1-alpine
Plugin version : 1.74

### Reproduction steps

- Created a multi-branch pipeline from Jenkins UI pointing to our github repo url; and setup 'Scan by webhook' using token option
- Configure multibranch webhook (webhook url : JENKINS_URL/multibranch-webhook-trigger/invoke?token=[Trigger token])  for our github repo
- Jenkinsfile in our repo is implemented using generic webhook trigger block. sample pipeline code:
pipeline {
    agent any
    triggers {
        GenericTrigger(
         genericVariables: [
          [key: 'changed_branch', value: '$.ref'],
         ],
         genericHeaderVariables: [
           [key: 'X-GitHub-Event', regexpFilter: '']
         ],
         token: 'test1',
         causeString: 'Triggered on $changed_branch',
         printContributedVariables: true,
         printPostContent: true,
         silentResponse: false
        )
      }

### Results

 For multibranch pipeline implemented with generic webhook triggers, not sure if the suggestion is to configure both webhooks (multibranch, generic-webhook) on the repo. Please suggest. Not able to get the pipeline to parse generic trigger variables with just the multibranch webhook configured on the repo. 
 For a simple/non-multibranch pipeline, configuring just the generic-webhook on repo works fine. But for a multi-branch pipeline, how should the webhook configuration look like ? to make use of functionalities of both plugins.

**Comment by tomasbjerre** [comment]
Last time I checked the "Multibranch Scan Webhook Trigger" just triggers the scanning of multibranch. It does not trigger any jobs.

This plugin triggers jobs.

If you want to trigger jobs and contribute content from webhook, you need this plugin configured in repo.

**Comment by dkoerner85** [comment]
Scanning a multibranch-pipeline in Jenkins will trigger jobs if new commits are found for the respective branches. This behaviour can be disabled by adding the property **Suppress automatic SCM triggering** to the branch source.

So, the https://plugins.jenkins.io/multibranch-scan-webhook-trigger will not trigger jobs by itself, but as a consequence of triggering the scan.
