### ISSUE TITLE
Cannot retrieve "Request Header" value in Jenkins job

### ISSUE THREAD

**Issue by wg21908** [jenkinsci/generic-webhook-trigger-plugin#215]
Plugin version used: 1.75
Jenkins version used: 2.249.1
Your configuration: A freestyle job running on a single Jenkins instance

I've installed your plugin in my Jenkins install.  I have a GitHub webhook created that has a single event defined, the event for "GitHub Tag/Branch Deletions".  I'm able to print out my 2 desired values of the JSON payload sent from GitHub in my freestyle jenkins job without problem.

My problem: I am not able to print out the X-GitHub-Event request header in my Jenkins job.  If I look at the most recent delivery in GitHub, it shows that it was successful and shows the X-GitHub-Event as a request header that has a value of "delete".  The goal is to print that value of "delete" in the Jenkins job.

I go into Jenkins to reconfigure the job, I browse to the "Build Triggers > Header Parmaters" section.  I add a "Request Header" called: "x_github_event" in an attempt to capture this request header.  In the "Build > Execute Shell" I echo out the value of $x_gitHub_event but it never prints a value.  

Any help is appreciated, this seems like the last hurdle I need to get past in the task I'm working.

**Comment by tomasbjerre** [comment]
Add the header with the name of the heade, X-GitHub-Event, not the variable name.

Have the plugin print contributed variables to see the derived name.

**Comment by wg21908** [comment]
Thank you, your feedback got me past that hurdle.  

The verbiage you have on the plugin of: "Name of request header in lowercase. Resulting variable name has '_' instead of '-' characters" right below the "request header" text field threw me off, it gives the indication that the "request header" text field value has to abide by these two rules.

**Comment by tomasbjerre** [comment]
Thanks for the suggestion. Releasing that change now.
