### ISSUE TITLE
Post Content Param not returning expected type back when using a jsonPath filter

### ISSUE THREAD

**Issue by mattgrayling** [jenkinsci/generic-webhook-trigger-plugin#221]
Hello, 
 
I may be using the plugin incorrectly if so I apologies. My issue is that I am trying to pull out a value and filter at the same time and the returning value is not of string type like when using no filter below in Scenario (1)
 
 Jenkins Version 2.277.1
 Plugin Version - 1.77
 
 <b>Scenario (1)</b>
 Variable - BRANCH 
 Expression - `$.pullRequest.fromRef.id` 
 Returns - `BRANCH = refs/heads/main` 
 
 <b>Scenario (2)</b>
 Variable - BRANCH 
 Expression - `$.[?(@.eventKey != "pr:merged:")].pullRequest.fromRef.id`
 Return - `BRANCH=["refs/heads/PROP-367"]` and `BRANCH_0=refs/heads/PROP-367`
 
 Would it be possible to have Scenario (2) working like Scenario (1) or is there something wrong with my configuration?
 
 Many Thanks

**Comment by tomasbjerre** [comment]
Sounds like a JSONPath question that you can ask on Stackoverflow. I dont have a good answer.
