### ISSUE TITLE
Bitbucket Events missed by generic webhook trigger plugin

### ISSUE THREAD

**Issue by mkjkec2005** [jenkinsci/generic-webhook-trigger-plugin#222]
Bitbucket Events missed by generic webhook trigger plugin.

Issue: 199 of 200 back-to-back branch-update events were sent by Bitbucket/processed by Jenkins.

Jenkins ver. 2.222.3
GWT - 1.67	

I have configured a customer logger(org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver) but could not find the reason why events are missed. Atlassian support indicated that Bitbucket has correctly processed the events and sent them to Jenkins. 

Job config:
Variable: http_post_content
Expression: $
JSONPath

Could you please guide us on how we can debug this issue? This is repeatedly happening and Jenkins is missing 3-4 per 100 events.

**Comment by tomasbjerre** [comment]
See https://github.com/jenkinsci/generic-webhook-trigger-plugin#trigger-exactly-one-build
