### ISSUE TITLE
request Payload is not getting parsed if content-type is application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by sonal-chauhan** [jenkinsci/generic-webhook-trigger-plugin#225]
I am integrating jenkins with slack-interactive-messages  via generic-webhook-trigger-plugin where slack-interactive-message-responseURL is of generic-webhook-trigger url.
Problem is that slack use to call slack-interactive-message-responseURL with content-type as application/x-www-form-urlencoded (inbuild functionality of slack) and generic-webhook-trigger-plugin only parses requestBody If content-type is application/json.

i tried hitting the same webhook url on method = post with requestBody and its parsing requestBody when content-type is application/json and not parsing requestBody when content-type is application/x-www-form-urlencoded.

One more thing , requestBody is getting parsed with method=get even if the content-type is application/x-www-form-urlencoded 

can't it parse the requestbody on method=post & content-type = application/x-www-form-urlencoded ?

**Comment by tomasbjerre** [comment]
Try 1.78. It should consume `application/x-www-form-urlencoded`

**Comment by sonal-chauhan** [comment]
> Try 1.78. It should consume `application/x-www-form-urlencoded`

@tomasbjerre Thanks for 1.82.
