### ISSUE TITLE
XMLHtmlRequest does not supply body to Job

### ISSUE THREAD

**Issue by StefanIGit** [jenkinsci/generic-webhook-trigger-plugin#229]
* Plugin version 1.77
 * Jenkins version 2.322

Hi, I have a webpage with a form which should trigger a Jenkins job when Submit is clicked.
It should supply the form data to the job and the job should use it.

I managed, by javascript, to send a xhr (XmlHttpRequest) with the form data as json in body.
It looks kind of correct in the Jenkins log except I have 2 request, the preflight (OPTIONS) and the POST.

```Jan 14, 2022 5:45:19 PM FINE org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver
Triggering Scalers/Change_Scale_Settings
Jan 14, 2022 5:45:19 PM FINE org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver
 with:

Jan 14, 2022 5:45:19 PM FINE org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver
Triggering Scalers/Change_Scale_Settings
Jan 14, 2022 5:45:19 PM FINE org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver
 with:
{"Name":"administration","Queue":"administration/events/tree-queue"}
```

The Result is a triggered Job but with empty... body (option enabled "Print post content")

```GenericWebhookEnvironmentContributor
 Received:




Contributing variables:

    NAME = 

```
Is there a way to ignore the preflight request? I cannot find a way to disable it.
Am I doing it wrong or is this a bug?

**Comment by tomasbjerre** [comment]
Ignoring `OPTIONS` in 1.80. Open issue again if any problems.

**Comment by StefanIGit** [comment]
thank you, now it works as expected :)
