### ISSUE TITLE
Passing ?token=TOKENHERE doesnt work

### ISSUE THREAD

**Issue by duronrulez** [jenkinsci/generic-webhook-trigger-plugin#23]
For some reason when i try to pass a token param to use the token auth it is being ignored and i get the following error:

`{"status":"ok","data":{"triggerResults":{"ANY":"Did not find any jobs to trigger! The user invoking /generic-webhook-trigger/invoke must have read permission to any jobs that should be triggered. You may try adding http://user:passw@url... or configuring and passing an authentication token like ...trigger/invoke?token=TOKENHERE"}}}` 

Can anyone please advise on whether they experience the same or its just my jenkins instance?

**Comment by tomasbjerre** [comment]
What version of the plugin?
How exactly did you configure it?
How exactly are you invoking it? curl command is good.

**Comment by duronrulez** [comment]
**What version of the plugin?**
Version 1.19

**How exactly did you configure it?**
Its incredibly simple config that reads bitbucket posts and looks for a branch name. When i invoke the webhook url from a logged in browser session it works, so i would assume the configuration is fine. Also the error message is different when the problem is configuration.

**How exactly are you invoking it?**
I am invoking it using the BitBucket web hooks. Which do a post to this url:
http://JENKINSURL/generic-webhook-trigger/invoke?token=TOKENHERE (where token here is the token from the api key in my jenkins account). The post contains JSON encoded data about a push.

**Comment by tomasbjerre** [comment]
The token should be the token in the job. I added a screenshot to the readme.

**Comment by duronrulez** [comment]
Ah, i understand. Thank you!
