### ISSUE TITLE
Job not triggered but response looks good

### ISSUE THREAD

**Issue by jjaaxx44** [jenkinsci/generic-webhook-trigger-plugin#231]
* Plugin version used. : 1.83
 * Jenkins version used. : Jenkins 2.303.1

I have simple branch variable with $.pullrequest.destination.branch.name JSONPath

When my PR merges and webhook request shows below response, where "triggered": false
HTTP status: 200
{
  "jobs": {
    "Test": {
      "regexpFilterExpression": "$branch",
      "triggered": false,
      "resolvedVariables": {
        "branch": "fl"
      },
      "regexpFilterText": "fl",
      "id": 0,
      "url": ""
    }
  },
  "message": "Triggered jobs."
}

I'm not sure what is going wrong, Optional filter has "$branch" and filter Text has "fl".
and above response shows the intended result from the request but build does not trigger

**Comment by tomasbjerre** [comment]
Looks like you should switch values of `regexpFilterExpression` `regexpFilterText`. So that `regexpFilterText` is `$branch`.

**Comment by jjaaxx44** [comment]
Thanks man, that was funny ha ha.
I wasted 2hrs of my weekend on this :(
