### ISSUE TITLE
How to configure allow for Job Quiet Period override in pipeline code?

### ISSUE THREAD

**Issue by SysEngDan** [jenkinsci/generic-webhook-trigger-plugin#232]
I'm currently using the option through the web GUI in Jenkins to override the job quiet period, but once my pipeline runs, that gets disabled. I suppose it's because I need to insert it into my pipeline. I can't seem to find the right syntax for this. I see the other issue where this was developed, #159, and the commit, but I don't know the code well enough to pick out the syntax I can use in my own pipeline.

**Comment by tomasbjerre** [comment]
I would suggest using the built in snippet generator to get it right. https://www.jenkins.io/doc/book/pipeline/getting-started/
