### ISSUE TITLE
"print contributed variables" very noisy

### ISSUE THREAD

**Issue by chris-kiick-sp** [jenkinsci/generic-webhook-trigger-plugin#233]
Checking "print contributed variables" in GWT config causes the variables to be printed many, many times. On a fairly simple pipeline with 3 stages and 5 steps total, the variables were printed 50 times.  Once would have been enough.

Is there a way to cut this down so it only prints them once, or at least a lot fewer than it does?  

 * Plugin version used.  1.74
 * Jenkins version used.  2.332.1

**Comment by tomasbjerre** [comment]
Duplicate https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/184
