### ISSUE TITLE
generic webhook trigger didn't work without specifiying token 

### ISSUE THREAD

**Issue by vaibhav65** [jenkinsci/generic-webhook-trigger-plugin#234]
Used when applying webhook at github without token
JENKINS_URL/generic-webhook-trigger/invoke

{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@jenkins/generic-webhook... "}

When simply pasting url on chrome it works without token 

https://<jenkinsurl>:<port>/generic-webhook-trigger/invoke

**Comment by vaibhav65** [comment]
version:[Jenkins 2.342](https://www.jenkins.io/).So to avoid this error i had to add  multiple webhooks at github for multiple repos with multiple tokens

**Comment by tomasbjerre** [comment]
You are probably logged in when using browser. And that is why it works.

**Comment by vaibhav65** [comment]
Ok ,But how i can used in git hub webhook without token.

**Comment by tomasbjerre** [comment]
Sounds like you want to allow anonymous users to trigger jobs. You need to adjust your security settings.

**Comment by vaibhav65** [comment]
Thanks i started using token ..But Occasionally token not found for Generic Webhook Trigger Jenkins Plugin when triggered from webhook.

The difference i found  is Automatic inclusion of GitSCM plugin in config.xml when tried to configure job

In build trigger i choose generic webhook trigger but jenkins does take automatically GitSCM and create property in job>config.xml file

    </org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty>
  </properties>
  <definition class="org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition" plugin="workflow-cps@2682.va_473dcddc941">
    <scm class="hudson.plugins.git.GitSCM" plugin="git@4.10.3">
      <configVersion>2</configVersion>
