### ISSUE TITLE
Jenkins fails to receive the trigger

### ISSUE THREAD

**Issue by gals-ma** [jenkinsci/generic-webhook-trigger-plugin#239]
When reporting a bug, please **try** to provide as much information as possible.

 * Plugin version used - 1.83
 * Jenkins version used - 2.332.1

In general, we use the webhook to trigger on every Pull Request action (commit, label, draft and all) on all of our repositories (around 150).
In 90% of the times it works as expected, but we experience other 10% cases where github seem to deliver the request and Jenkins does not get it for some reason.
Any idea what could cause this?

**Comment by Stokvisss** [comment]
Same problem here, the webhooks seem to be a bit unreliable. HTTP 200 is returned, then nothing happens on Jenkins' side.

Plugin version: 1.84
Jenkins version: Jenkins 2.359

**Comment by tomasbjerre** [comment]
Perhaps this:
https://github.com/jenkinsci/generic-webhook-trigger-plugin#trigger-exactly-one-build

But there is no information supplied in this issue. It is impossible to investigate.
