### ISSUE TITLE
"Post content parameters" radio button not selectable for multiple variables

### ISSUE THREAD

**Issue by packar3k** [jenkinsci/generic-webhook-trigger-plugin#246]
Hi,
Met with the following issue today!

Jenkins version: 2.346.2
Plugin version: 1.84

When creating new jobs with multiple "Post content parameters" the radio buttons to select JSONPath/XPath are not selectable except for the first variable.

It's been working fine for me, maybe the problem happened after my recent Jenkins version update to 2.346.2. 
In all the old jobs the selection still works.

As a temporary workaround, I directly adjusted the job config and added `<expressionType>JSONPath</expressionType>`
After that, the selection of the buttons is working again.
![Screenshot 2022-08-10 at 15 11 51](https://user-images.githubusercontent.com/110938268/183910214-416e9acd-2faf-4257-9ce1-d7d500c35a33.png)
Thanks in advance!

**Comment by tomasbjerre** [comment]
I can confirm this.

I think it is a problem in Jenkins, not in the plugin. The plugin has little code to handle those radio buttons:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/resources/org/jenkinsci/plugins/gwt/GenericVariable/config.jelly#L7

**Comment by packar3k** [comment]
Ok, thanks for the response.

**Comment by Ruruthia** [comment]
I think it can be caused by this Jenkins regression: https://issues.jenkins.io/browse/JENKINS-70139

**Comment by timjar3** [comment]
> packar3k
Could you please mention the steps on how/where you adjusted the Job config?

**Comment by packar3k** [comment]
@timjar3 If you have access to the Jenkins job config on the Jenkins server, locate the job config and then you can manually edit the job config xml --> find the generic hook config --> modify the expression Type
