### ISSUE TITLE
Enable support for TLS Client Certificate Auth

### ISSUE THREAD

**Issue by mkjkec2005** [jenkinsci/generic-webhook-trigger-plugin#247]
Hi,

Please find the Jenkins and plugin version details below. 

Jenkins: 2.289.2
Generic Webhook Trigger: 1.74

We are trying to set up an encrypted Jenkins and the need is to secure all communication. 
mtls functionality is offered by the Bitbucket branch source plugin. 

-Mohan

**Comment by mkjkec2005** [comment]
@tomasbjerre could you please check this request?

**Comment by tomasbjerre** [comment]
The only thing I find with TLS in that plugin is here:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/ade16a1aa29a4f5755d7cf9334a813a6eb69d65d/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/api/credentials/BitbucketClientCertificateAuthenticator.java

The plugin uses TLS to communicate with Bitbucket. This plugin just receives requests, it does not open new connections. So I'm not really sure what you are looking for here.

**Comment by mkjkec2005** [comment]
Can we use TLS to communicate with Bitbucket in generic-webhook-trigger-plugin also?

**Comment by mkjkec2005** [comment]
@tomasbjerre  we want to use Jenkins in a completely secure environment (use mTLS), hence this request.

**Comment by mkjkec2005** [comment]
@tomasbjerre Could you please help on this topic?
