### ISSUE TITLE
Not able to trigger the job from bitbucket using generic webhook of jenkins.

### ISSUE THREAD

**Issue by pawan-1999** [jenkinsci/generic-webhook-trigger-plugin#249]
Hello Engineers,

 * Jenkins version used is [Jenkins 2.263.1]
 * Plugin Generic Webhook Trigger [1.84] 

When I commit the code in xxxx repo to developTest branch with token test it should trigger job but  its not triggering

 * jenkins job configuration for generic webhook
   * Post content parameters:
       variable: branch
       Expression: $push.changes[0].new.name
   * Token: test
   * Optional Filter:
     * Expression:^developTest
     * Text: $branch
    
* webhook configured in bitbucket XXXX/generic-webhook-trigger/invoke?token=test
 the response after commit 
  body: {"jobs":{"(Development) Community Build Image replica":{"regexpFilterExpression":"^developTest$","triggered":false,"resolvedVariables":{"branch":""},"regexpFilterText":"","id":0,"url":""}},"message":"Triggered jobs."}

when validating the regex expression for entire body getting expected output but when I commit and see the webhook request in bitbucket above is the response of body.

please support.

Thanks & Regards
 Pawan Gupta

**Comment by tomasbjerre** [comment]
Can you supply curl commands as described in the readme? Supply a curl command that you think should trigger a build.

**Comment by pawan-1999** [comment]
The job should be triggered when the commit is done on specific branch that
is not happening.
Please check the body which i shared in issue.

**Comment by tomasbjerre** [comment]
The body being sent to the plugin is what Im asking for.
