### ISSUE TITLE
XmlFlattener doesn't work with Attribute nodes

### ISSUE THREAD

**Issue by danduff** [jenkinsci/generic-webhook-trigger-plugin#25]
The XMLFlattener only allows access to Element nodes and not Attribute nodes.

e.g.
Element nodes successfully work with an XPATH of /element
`<element>value</element>`

Attribute nodes do no work with an XPATH of /attribute[@name='key']/@value
`<attribute name='key' value='value' />`

I've  tried a fix for this by modifying isXmlLeafNode() to check for either ELEMENT_NODE or ATTRIBUTE_NODE which resolved the problem I had.

`return node != null &&
        (node.getNodeType() == Node.ELEMENT_NODE || 
        node.getNodeType() == Node.ATTRIBUTE_NODE) &&
        node.getChildNodes().getLength() == 1
        && node.getFirstChild().getNodeType() == Node.TEXT_NODE;`

**Comment by tomasbjerre** [comment]
Released in 1.20 now. Open issue again if not working.
