### ISSUE TITLE
Failed to load: Generic Webhook Trigger Plugin (generic-webhook-trigger 1.84.1)

### ISSUE THREAD

**Issue by sreejesh-radhakrishnan-db** [jenkinsci/generic-webhook-trigger-plugin#250]
When reporting a bug, please **try** to provide as much information as possible.

I have tried to install the plugin by copying the  generic-webhook-trigger.hpi  to   /var/lib/jenkins/  and restarting the jenkins

On the jenkins the plugin is not loading and showing this error
Failed to load: Generic Webhook Trigger Plugin (generic-webhook-trigger 1.84.1)
 - Plugin is missing: credentials (2.1.16)
 - Plugin is missing: plain-credentials (1.2)
 - Plugin is missing: structs (1.7)

Sorry this may not be a bug, I am new to JENKINS and PLUGINS, if this is something of me missing basis. can you guide me please?

 * Plugin version used. 1.84.1
 * Jenkins version used.  2.361.1
 * Your configuration.
   * Variables configured, names, expressions...   (NONE  has been explicitly done)
   * Pipeline script (See Pipeline section in README)
 * Build job log
 * Post content received. It can be found in the job execution log. People using GitHub often forget to set the content type in "Manage webhook" when configuring the webhook at GitHub.
 * A `curl` command and its response.
 * Expected result and actual result.

You may also have a look at the test cases as they should answer the most common questions:
 
  https://github.com/jenkinsci/generic-webhook-trigger-plugin/tree/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd

If you are fiddling with expressions, you may want to checkout:

* [This JSONPath site](http://jsonpath.herokuapp.com/)
* [This XPath site](http://www.freeformatter.com/xpath-tester.html)
* [This regexp site](https://jex.im/regulex/)

A Curl command can look something like this:
```
curl -v -H "Content-Type: application/json" -X POST -d '{ "app":{ "name":"GitHub API", "url":"http://developer.github.com/v3/oauth/" }}' http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=sometoken
```

**Comment by tomasbjerre** [comment]
Sounds like you need to install those missing plugins.

**Comment by sreejesh-radhakrishnan-db** [comment]
ah okay, should have learn to read englsh at Primary school better :-),,  thank you.
