### ISSUE TITLE
webhook without credentilas working 

### ISSUE THREAD

**Issue by malki-akamai** [jenkinsci/generic-webhook-trigger-plugin#251]
Hello everyone, 
I am using this plugin at version 1.85.2
My jenkins server works with  azure ad authentication as login interface.

I need to define a webhook from some place to trigger a pipeline so I used the plugin, and I just notice that using the basic api "https://myjenkins/generic-webhook-trigger/invoke?token=SECURITYTOKEN" I can trigger a webhook and its successful no matter the way I authenticate to jenkins..

can someone helps me to understand why is it happen?  
Is it related to the authentication side of jenkins or to the webhook plugin?

**Comment by tomasbjerre** [comment]
The plugin is implemented like that. From the readme: The token also allows invocations without any other authentication credentials.
