### ISSUE TITLE
Jenkins 2.375.2 and webhook trigger plugin  Version1.86.2

### ISSUE THREAD

**Issue by adiltajammal** [jenkinsci/generic-webhook-trigger-plugin#256]
when upgrade plugin from 1.84 to 1.86 my webhook trigger multiple builds against one webhook

**Comment by tomasbjerre** [comment]
Can you supply ypur configuration?

**Comment by adiltajammal** [comment]
![trigger2](https://user-images.githubusercontent.com/121027849/217460151-51194e4b-edd4-4e1b-b86a-a8ef5ca3c81d.png)
![trigger3](https://user-images.githubusercontent.com/121027849/217460160-93b2f288-909f-404b-b63c-a10eb5b395c3.png)
![trigger4](https://user-images.githubusercontent.com/121027849/217460163-2c71c9b6-5507-4b13-90de-2f41f64523d8.png)
![trigger5](https://user-images.githubusercontent.com/121027849/217460166-cab8ea85-e30c-4d43-ad10-d6154d85298e.png)
![trigger6](https://user-images.githubusercontent.com/121027849/217460169-2d9037a3-8883-4f4c-8120-ac23bad016fb.png)
![triiger1](https://user-images.githubusercontent.com/121027849/217460172-0c013634-b19d-4997-b532-2aa857aeb119.png)




HI Tomasbjerre these are my configurations for webhook trigger plugin

**Comment by adiltajammal** [comment]
![triiger1](https://user-images.githubusercontent.com/121027849/217460448-3b2aff09-2897-45ff-b745-2f919736303e.png)
![trigger2](https://user-images.githubusercontent.com/121027849/217460472-b7514362-159d-42b3-bf67-a6d7d374265f.png)
![trigger3](https://user-images.githubusercontent.com/121027849/217460488-ce3b23e0-cd57-4b01-b502-a1c8a4f12bd9.png)
![trigger4](https://user-images.githubusercon
![trigger5](https://user-images.githubusercontent.com/121027849/217460510-8aaf39dd-8309-4cfe-8015-a3bd6d0bd85e.png)
tent.com/121027849/217460499-1f104083-8941-4a2a-8699-714282a73f14.png)


Hi tomas this is my configuration please do let me know Sir Thanks alot for help

**Comment by adiltajammal** [comment]
[tomasbjerre](https://github.com/tomasbjerre)

**Comment by tomasbjerre** [comment]
Are you sure the plugin is invoked only once? Can you repeat that with a curl command? There are example curl commands in readme here on Github.

The culprit here is probably the option "allow several triggers per build". If the plugin is invoked several times, and you want just one build, you should check that box.

If you want exactly one build for each invocation of the plugin, you should leave it as is in your screenshots.

**Comment by adiltajammal** [comment]
Thanks aloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooootttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt

**Comment by tomasbjerre** [comment]
Did it get invoked several times? Or is it a bug?

**Comment by adiltajammal** [comment]
according to my understanding from the description given under which is 

(If checked, the plugin will allow one build to have several triggers. If not checked, the plugin will trigger exactly one job when invoked.)

this option should allow multiple trigger against one build but if webhook invoked again and again.....in my problem case webhook was invoked only once and multiple trigger started ..after turning this option ON now my webhook invoked only one trigger against one build... so i think this is a bug

**Comment by tomasbjerre** [comment]
Can you repeat that with curl?
