### ISSUE TITLE
JSONPath processing seems to not handle "," operator

### ISSUE THREAD

**Issue by darrensony** [jenkinsci/generic-webhook-trigger-plugin#26]
Using the example of a GitHub PushEvent (1)

I can create a "Post content parameters" entry as such:

```
Variable: gitFilesModified
Expression: $.commits[*].modified[*]
```

And the Environment variable in the run "gitFilesModified_0" is set as expected.

However, if I try to create a variable for all files affected:

```
Variable: gitFilesAffected
Expression: $.commits[*].modified,added,removed[*]
```

No environment variables starting with "gitFilesAffected" are created at all.

Testing with jsonpath.com, this doesn't seem to be a problem with the path expression itself.

Cheers
Darren

(1) https://developer.github.com/v3/activity/events/types/#pushevent

**Comment by tomasbjerre** [comment]
The plugin uses this implementation:
https://github.com/json-path/JsonPath

Perhaps this works: `$.commits[*].[modified,added,removed][*]`.

**Comment by darrensony** [comment]
That does not work either. Same behaviour.

**Comment by tomasbjerre** [comment]
This works: `$.commits[*].['modified','added','removed'][*]`

I added a test case as an example here:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/java/org/jenkinsci/plugins/gwt/VariablesResolverJsonPathTest.java#L290
