### ISSUE TITLE
Guava 11 is bundled with the 1.86.2 version

### ISSUE THREAD

**Issue by yzakharuk-iqmessenger** [jenkinsci/generic-webhook-trigger-plugin#262]
The latest (1.86.2) version of the plugin bundle contains Guava 11 jar file. This may cause problems as the latest versions of Jenkins core contains a much newer version of Guava (In my case, this cause `VerifyError: class com.google.common.collect.EmptyImmutableSortedSet overrides final method com.google.common.collect.ImmutableCollection.toArray()[Ljava/lang/Object;` errors.).

As far as I understand, the plugin should not contain any version of the Guava library but use the provided version.

**Comment by tomasbjerre** [comment]
Thanks for reporting, should be fixed now.
