### ISSUE TITLE
"Override Quiet Period"（Generic Webhook Trigger）is it available ?

### ISSUE THREAD

**Issue by xtucg** [jenkinsci/generic-webhook-trigger-plugin#263]
A Curl command can look something like this:
```
curl -H "Content-Type: application/json" -X POST -d '{ "app":{ "name":"GitHub API", "url":"http://developer.github.com/v3/oauth/" }}' http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=sometoken&jobQuietPeriod=60
```
I have allowed the trigger to override this job's quiet period，but "jobQuietPeriod" doesn't seem to work？（quiet period is still default 5）

**Comment by tomasbjerre** [comment]
Change it to:

curl -H "Content-Type: application/json" -X POST -d '{ "app":{ "name":"GitHub API", "url":"http://developer.github.com/v3/oauth/" }}' "http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=sometoken&jobQuietPeriod=60"

**Comment by xtucg** [comment]
> Change it to:
> 
> curl -H "Content-Type: application/json" -X POST -d '{ "app":{ "name":"GitHub API", "url":"http://developer.github.com/v3/oauth/" }}' "http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=sometoken&jobQuietPeriod=60"

It worked, thank you
