### ISSUE TITLE
tigger specific branch is worked but checkout is not the specific branch

### ISSUE THREAD

**Issue by csrlsm** [jenkinsci/generic-webhook-trigger-plugin#265]
I configured gwt with jenkins+github，and it works. but when the job was tiggered, git checkout to the main branch.
for example, i push to the "origin/test" bransh and tigger by webhook, but git fetch all branch and checkout to the main branch.

the output messages from job as follow:

...
Contributing variables:

    ref = refs/heads/test

The recommended git tool is: NONE
using credential d5d05eac-5bc3-4318-a3fc-2d4cb5fff9df
 > /usr/bin/git rev-parse --resolve-git-dir /var/lib/jenkins/workspace/test/.git # timeout=10
Fetching changes from the remote Git repository
 > /usr/bin/git config remote.python_test.url git@github.com:xxx/python_test.git # timeout=10
Fetching upstream changes from git@github.com:xxx/python_test.git
 > /usr/bin/git --version # timeout=10
 > git --version # 'git version 2.25.1'
using GIT_SSH to set credentials jenkins_github
 > /usr/bin/git fetch --tags --force --progress -- git@github.com:xxx/python_test.git +refs/heads/*:refs/remotes/python_test/* # timeout=10
Seen branch in repository python_test/dev
Seen branch in repository python_test/main
Seen branch in repository python_test/test
Seen 3 remote branches
 > /usr/bin/git show-ref --tags -d # timeout=10
Checking out Revision f685a731128d411gf455afb0a476a29238553b0d (python_test/main)
 > /usr/bin/git config core.sparsecheckout # timeout=10
 > /usr/bin/git checkout -f f685a731128d411gf455afb0a476a29238553b0d # timeout=10

**Comment by tomasbjerre** [comment]
This plugin does not clone anything.
