### ISSUE TITLE
How to bypass the crumb protection?

### ISSUE THREAD

**Issue by jrichardsz** [jenkinsci/generic-webhook-trigger-plugin#267]
## Expected Behavior

Using curl I should be able to execute a simple job invokation

## Current Behavior

I got these errors :

```
curl -vs "http://localhost:8080/jenkins/generic-webhook-trigger/invoke"
```

![image](https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/3322836/3c76e1e6-a10f-44af-af4a-c54a2693b84d)

```
curl -vs -X POST "http://admin:123456@localhost:8080/jenkins/generic-webhook-trigger/invoke"

curl -vs -X POST "http://admin:123456@localhost:8080/jenkins/generic-webhook-trigger/invoke?token=123456"
```

![image](https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/3322836/0e80450c-7684-46f5-bcfb-88e72c12097f)

## Possible Solution

https://stackoverflow.com/a/56167349/3957754

But in my case, the CSRF configuration is different. 

![image](https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/3322836/ee7f5074-6411-4881-8d96-1ffbbf5ada44)

I also tried checking and unchecking the proxy compatibility. The error is the same

## Steps to Reproduce

1. Start the lastes jenkins version using docker

```
docker run -it --name jenkins -p 8080:8080 jenkins/jenkins:jdk11
```
2. Install the plugin
3. Configure the plugin
4. Restart jenkins
5. Use curl to test the webhook invokation

## Context (Environment)

 * Plugin version used: 1.86.3 
 * Jenkins version used : 2.411
   * <a href="https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/3322836/46400fde-dd5f-48f1-9268-44210a3a11b4" target="_blank">https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/3322836/46400fde-dd5f-48f1-9268-44210a3a11b4</a> 

 * Your configuration.
   *  <a href="https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/3322836/f1832752-3c16-49d8-885f-cee81a142624" target="_blank">https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/3322836/f1832752-3c16-49d8-885f-cee81a142624</a>

**Comment by tomasbjerre** [comment]
The plugin does not require login or crumb:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/add7cca58723548ddcb76caebda96eb54978aa8c/src/main/java/org/jenkinsci/plugins/gwt/GenericWebHookRequestReceiver.java#L38

Change the curl command to:
```
curl -vs -X POST "http://localhost:8080/generic-webhook-trigger/invoke?token=123456"
```

Open issue again if not working!
