### ISSUE TITLE
Which version to use for Jenkins 2.0

### ISSUE THREAD

**Issue by carlmacdiarmada** [jenkinsci/generic-webhook-trigger-plugin#28]
Hi,

I have been using your plugin and I used it on my personal jenkins server which works great and does exactly what I need it to do, However in my work we only have Jenkins 2.0.. is there a version of the plugin that will support this? I have 1.20 installed and it doesnt recognize the input with job DSL api creation through groovy

Thanks
Carl

**Comment by carlmacdiarmada** [comment]
it seems to work fine when manually set up - just the job dsl api doesnt seem to work.

**Comment by tomasbjerre** [comment]
I would say 2.23 or later. I never used it with an earlier release of Jenkins.

**Comment by carlmacdiarmada** [comment]
ok thank you. I was hoping the earlier releases might have had support for 2.0!
