### ISSUE TITLE
How can I get the raw json body？

### ISSUE THREAD

**Issue by yuchengren** [jenkinsci/generic-webhook-trigger-plugin#284]
Hello，
my pipeline like this
`genericVariables: [
      [key: 'BODY',
        value: '$',
        expressionType: 'JSONPath', //Optional, defaults to JSONPath
        regexpFilter: '', //Optional, defaults to empty string
        defaultValue: '' //Optional, defaults to empty string
      ],
     ],`

when I user $BODY in shell script， it is not a raw json, but a JSONPATH format string 。
How can I get the raw json body， sample: gitlab payload  json body

**Comment by tomasbjerre** [comment]
Can you supply complete `pipeline`, `request` with curl command and `response`?

**Comment by yuchengren** [comment]
> Can you supply complete `pipeline`, `request` with curl command and `response`?
`
pipeline {
  agent any

  environment {
     SCRIPT_PROJECT_ROOT = "/Users/macuser/PycharmProjects/smartscripts"
  }

  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'BODY',
        value: '$',
        expressionType: 'JSONPath', //Optional, defaults to JSONPath
        regexpFilter: '', //Optional, defaults to empty string
        defaultValue: '' //Optional, defaults to empty string
      ],
     ],
     causeString: 'Generic Cause',
     token: 'gitlab',
     printContributedVariables: true,
     printPostContent: true,
     silentResponse: true,
    )
  }

  stages {
    stage('action') {
      steps {
        sh "export PYTHONPATH=${SCRIPT_PROJECT_ROOT} && python3 -u ${SCRIPT_PROJECT_ROOT}/android/jenkins/webhook/webhook-gitlab.py \
            --data $BODY \
        "
      }
    }
  }
}
`

the jenkins execute log:
`
+ python3 -u /Users/macuser/PycharmProjects/smartscripts/android/jenkins/webhook/webhook-gitlab.py --data object_kind:push event_name:push ...
`

$BODY  output is not raw json,but a JSONPATH string.

**Comment by tomasbjerre** [comment]
I am missing the curl-command.
Also the log, ans specifically the contributed variables.

**Comment by yuchengren** [comment]
> I am missing the curl-command. Also the log, ans specifically the contributed variables.

It it just trigger by gitlab webhook， the URL is
`http://JENKINS_URL/generic-webhook-trigger/invoke?token=gitlab`,
I want to do something after push， and I need to raw json body

**Comment by tomasbjerre** [comment]
This is impossible to investigate if you do not supply something that I can reproduce.

**Comment by yuchengren** [comment]
the gitlab we

> This is impossible to investigate if you do not supply something that I can reproduce.

sorry, I do not understand, Has any else Do you need？
The webhook is not a curl-command, it is just trigger by gitlab push event。the gitlab push event, webhook body sample is on docs: https://docs.gitlab.com/ee/user/project/integrations/webhook_events.html

**Comment by yuchengren** [comment]
more jenkins log:
Generic Cause
GenericWebhookEnvironmentContributor
 Received:

{"object_kind":"push","event_name":"push",...}


Contributing variables:

    BODY = {"object_kind":"push","event_name":"push",..}
 
 + python3 -u /Users/macuser/PycharmProjects/smartscripts/android/jenkins/webhook/webhook-gitlab.py --data object_kind:push event_name:push...
 
 ===
the BODY variables in log is Json,but  in pipeline shell command $BODY is not json， but JSONPATH format

**Comment by tomasbjerre** [comment]
So you are saying that if you do:

```groovy
sh """
 echo "BODY: " + BODY
"""
```

You do not get `BODY: {"object_kind":"push","event_name":"push",..}` ?
What exactly do you get?

**Comment by yuchengren** [comment]
> * object_kind:push event_name:push ...

Yes ! , 
sh "export PYTHONPATH=${SCRIPT_PROJECT_ROOT} && python3 -u ${SCRIPT_PROJECT_ROOT}/android/jenkins/webhook/webhook-gitlab.py
--data $BODY "
the $BODY  is not json, but   JSONTPATH format string:  object_kind:push event_name:push ...

**Comment by tomasbjerre** [comment]
If you print the variable, like I said, you will see that it is the raw json.

You problem is probably is how you are using the value. See https://stackoverflow.com/a/38385227/2477084

**Comment by yuchengren** [comment]
> If you print the variable, like I said, you will see that it is the raw json.
> 
> You problem is probably is how you are using the value. See https://stackoverflow.com/a/38385227/2477084

you are right! the BODY is a raw json.  thanks very much . The problem is that, shell command  json param is need to wrap by ''
