### ISSUE TITLE
Plugin does not accept Github token scheme

### ISSUE THREAD

**Issue by rchennafi** [jenkinsci/generic-webhook-trigger-plugin#287]
It seems to me that the authentication scheme for Github webhooks does not currently work. If I'm missing something here, please point it out.

Jenkins Version 2.413
Generic Webhook Trigger 1.88.2

Used the default configuration. Also tried a configuration where I passed a token I'd given to the Github webhook.

Pipeline Script
```
pipeline {
    agent {
        label 'master'
    }

    stages {
        stage('Check') {
            steps {
                echo "Wow"
            }
        }
    }
}
```

Github reports a 404 when attempting to call the invoke URL. This appears to be because it does not send a 'token' like the plugin expects, and instead send a SHA signature generated from the token for verification.

https://docs.github.com/en/webhooks/using-webhooks/validating-webhook-deliveries#validating-webhook-deliveries

This is what Github is reporting in terms of the response/request.

Request
```
404
Request URL: https://my.jenkins.server/generic-webhook-trigger/invoke
Request method: POST
Accept: */*
Content-Type: application/json
User-Agent: GitHub-Hookshot/***
X-GitHub-Delivery: ****
X-GitHub-Event: pull_request
X-GitHub-Hook-ID: ***
X-GitHub-Hook-Installation-Target-ID: ***
X-GitHub-Hook-Installation-Target-Type: repository
X-Hub-Signature: sha1=***
X-Hub-Signature-256: sha256=***
```

Response
```
Content-Length: 279
Content-Type: application/json;charset=utf-8
Date: Wed, 13 Dec 2023 20:12:31 GMT
Server: Jetty(10.0.15)
X-Content-Type-Options: nosniff

{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@example.org/generic-webhook... "}
```

The username/password idea does not work in this scenario, nor do I see a way to pass it, since we are using Microsoft OAUTH for access control. The job also appears configured correctly barring the token, given it triggers if I call the invoke URL manually.

```
{"jobs":{"Testing/Check Github Commits Tester":{"regexpFilterExpression":"","triggered":true,"resolvedVariables":{},"regexpFilterText":"","id":9605385,"url":"queue/item/9605385/"}},"message":"Triggered jobs."}
```

**Comment by tomasbjerre** [comment]
Im  nor really sure what you are trying to do. You can configure a token in the plugin for a specific job. That token will need to be supplied when trying to trigger that job.

There is also HMAC verification which is something completely different. Not sure if maby that is what you want.

**Comment by rchennafi** [comment]
@tomasbjerre What I'm saying is when I configure the token it does not work, because Github does not call the webhook with any of the accepted ways to authenticate the token.

So yeah, I'm asking for the plugin to support secret keys with Github. That happens to be HMAC verification.

**Comment by tomasbjerre** [comment]
"The job also appears configured correctly barring the token, given it triggers if I call the invoke URL manually" what is the exact URL that you trigger?

"does not send a 'token' like the plugin expects" but your supplied pipeline code does not contain any token.

If you are browsing to the trigger URL, you might already be authenticated and that is why the job is found and triggered.

If you add the same URL to GitHub is will not be authenticated and not find any jobs to trigger.

If you configure a token in the plugin, the jobs with that token will be found even if you are not authenticated. So that is one thing to try, try to configure a token and add the URL with token query parameter in GitHub.

**Comment by rchennafi** [comment]
`If you configure a token in the plugin, the jobs with that token will be found even if you are not authenticated. So that is one thing to try, try to configure a token and add the URL with token query parameter in GitHub.`

This actually works as a solution here, though not the most ideal as it exposes the token in the repo settings. Feel free to close it. Implementing the Github auth scheme would be nice, but it is hardly required.

`"does not send a 'token' like the plugin expects" but your supplied pipeline code does not contain any token.`
The token is set outside of the pipeline.

```
"If you are browsing to the trigger URL, you might already be authenticated and that is why the job is found and triggered."
If you add the same URL to GitHub is will not be authenticated and not find any jobs to trigger.
```
That is correct. I just spoke about that to clarify the setup scheme is actually working.

**Comment by tomasbjerre** [comment]
What is the problem with exposing the token? It can only be used to trigger the job.

If you dont want anyone to be able to trigger the job, you should also use the whitelist feature. https://github.com/jenkinsci/generic-webhook-trigger-plugin?tab=readme-ov-file#whitelist-hosts

**Comment by rchennafi** [comment]
An exposed token is less secure, in any case, not a big deal. Who knows what one may be triggering with that token. Jobs can do just about anything.

_If you dont want anyone to be able to trigger the job, you should also use the whitelist feature._
Not an effective solution when it requires whitelisting all of Github's IPs in this situation.

**Comment by tomasbjerre** [comment]
If you let each job have their own token, you will only be able to trigger one job with the token.

You may also want to use the regexp filter when resolving values from the webhook to only allow numbers or whatever you expect them to be.

Also you can whitelist all IP:s and use HMAC.
