### ISSUE TITLE
Reload trigger configuration from scm

### ISSUE THREAD

**Issue by schlumpfit** [jenkinsci/generic-webhook-trigger-plugin#288]
Hi there, 

see the request below:

 * Plugin version used: Version: 1.88.2
 * Jenkins version used: Version 2.414.3
 * Your configuration: Does not really matter I guess.
 * Expected result:
 
 A change in the trigger configuration inside a Jenkinsfile from scm is reflected in the actual run.

 * Observed result:

A change in the trigger configuration inside the Jenkinsfile from scm is only valid for the second run.

* Reasoning:

I know that the docs explicitly state about that:

> When configuring from pipeline (not multibranch pipeline), that pipeline needs to run once, to apply the plugin trigger config, and after that this plugin will be able to trigger the job. This is how Jenkins works, not something implemented in this plugin.

But maybe it would be possible to reduce this to a minimal set of required parameters like the token and reload the rest of the variables and expressions from the actual Jenkinsfile that was fetched from scm.

I get the point that the "reload" has to happen for the very first time, but afterwards it would be great if it would directly read the configuration from the Jenkinsfile before it applies the filters.

Generally the Jenkinsfile (especially the trigger config) is not supposed to change that often, but when it does this behavior can lead to really confusing behavior since the changes of one branch are suddenly applied to another branch when they run on the same job. So the change is always one run behind if multiple branches have different configurations. (I am not a big fan of the multi branch pipelines and went happily away from that by using this plugin instead with a Jenkinsfile from scm.)

**Comment by schlumpfit** [comment]
Thanks for the reply.

I guess that your approach is configuring the job/trigger "externally" and will only work as one configuration for all branches?

I currently make use of the Jenkinsfile from scm. This gives me the benefit that I can have multiple branches (mostly PRs) using the same job and still being able to perform changes also on the Jenkinsfile which would only affect the run for the particular branch. This way I can have my Jenkinsfile live with the repository and do not make use of the multibranch pipeline job.

Could I do something similar using the jobdsl plugin?

An interesting question would be if the generic-webhook-trigger plugin is invoked before or after the Jenkinsfile is fetched.

My sad assumption here is that the evaluation of the trigger happens before anything else is allocated/fetched, which also would make a lot of sense to me. But if the Jenkinsfile is already be present somewhere, it would be just a matter of reloading the configuration before the actual evaluation.

I also agree that a fetch of the Jenkinsfile inside the plugin is a big and undesirable change to the footprint of the plugin...

**Comment by tomasbjerre** [comment]
Yes I have same pipeline for each branch. Here is some code:
- https://github.com/tomasbjerre/jenkins-configuration-as-code-sandbox/blob/master/jobs/applicationRepo.groovy
- And that code is being invoked from https://github.com/tomasbjerre/jenkins-configuration-as-code-sandbox/blob/master/vars/createJobs.groovy

You can adjust that JobDSL to get read the Jenkinsfile from the repo.

Yes the plugin is invoked before the Jenkinsfile is read.

**Comment by schlumpfit** [comment]
Thanks for the great feedback.

I thought there might be a feasable way, but I have the feeling that it is not worth the effort. So I think the issue can be considered as closed.

Regarding your suggestion with the JobDSL and the pipeline from SCM:

Can you point me to some documentation/sources how the pipeline from scm is loaded?
I am wondering which parts of the declarative pipeline are read from scm and are applied immediatly and which are taken from the job xml config from the controller. From what I can see, the triggers and parameters are read from controller disk and are updated after the run, being valid for the next invocation. How does this behave for concurrent jobs?

Can there be a mix of JobDSL configuring eg. parameters and triggers and the actual stages/steps are loaded from scm?

**Comment by tomasbjerre** [comment]
You can ask about such things on Stackoverflow or here https://groups.google.com/g/jenkinsci-dev
