### ISSUE TITLE
Buildcause no longer detected since Jenkins update?

### ISSUE THREAD

**Issue by faandg** [jenkinsci/generic-webhook-trigger-plugin#289]
* Plugin version used **1.88.2**
 * Jenkins version used: Jenkins **2.426.1**
 * multibranch pipelines
 * trigger config
```
triggers {
    GenericTrigger( 
        causeString: 'Bitbucket webhook trigger', 
        printContributedVariables: false, 
        regexpFilterExpression: '', 
        regexpFilterText: '', 
        token: 'xxx', 
        tokenCredentialId: '')
}
```

Hi, we start our pipelines with this piece of code to determine whether the build was started by the Generic Webhook Trigger.
```
stage('Initialize') {
    steps {
        sh 'printenv'
        script{
            if (currentBuild.getBuildCauses('jenkins.branch.BranchIndexingCause').size()){
                TRIGGER='index'
            } else {
                TRIGGER="${BUILD_USER}"
            }
        }
    }
}
```

However since the last update there no longer seems to be a BranchIndexingCause (so the size==0 -> [which evaluates as false for groovy](https://stackoverflow.com/questions/53394027/why-does-0-integer-value-behaves-as-false-in-if-statement-in-groovy)) and we get a failure because there is no BUILD_USER variable either (only on manually triggered builds).

The expected behavior would be that `currentBuild.getBuildCauses('jenkins.branch.BranchIndexingCause').size()` returns 1 which evaluates as `true` and we can determine the pipeline flow based on the fact that we triggered from a webhook.

Do you know if there is a bug at play here, maybe due to recent changes on the Jenkins side?
A different method to check if the pipeline was triggered by the genericWebhookTrigger would also be a helpful as a workaround.

**Comment by tomasbjerre** [comment]
If the build is triggered by this plugin, the cause is 
 `org.jenkinsci.plugins.gwt.GenericCause`.

So perhaps you can invert the if statement and look for this cause.

**Comment by faandg** [comment]
`org.jenkinsci.plugins.gwt.GenericCause` is detected correctly, thanks!
Should I keep the ticket open to investigate the behavior change of `jenkins.branch.BranchIndexingCause` build causes?

**Comment by tomasbjerre** [comment]
No, BranchIndexingCause is not part of this plugin.
