### ISSUE TITLE
Unable to resolve variable 

### ISSUE THREAD

**Issue by dkinzer** [jenkinsci/generic-webhook-trigger-plugin#29]
I'm trying to get the repository name from a github webhook POST.  The payload looks like this (truncated for clarity):

```json
{
  "repository": {
    "name": "foo"
  }
}
```
And I've tested at https://jsonpath.curiousconcept.com/ that `$.repository.name` correctly parses for the respository name.

However, the jenkins job is continually failing to add the variable.  When I look at the logs I see the following message:

> Dec 20, 2017 1:06:01 PM INFO org.jenkinsci.plugins.gwt.resolvers.PostContentParameterResolver resolve
>  Unable to resolve repository_name

My configuration looks correct to me:

![image](https://user-images.githubusercontent.com/444215/34222775-c1cf2810-e58a-11e7-9805-ecb38ebd4a36.png)

I am running Jenkins 2.89.2
And generic-webhook-trigger-plugin 1.20

**Comment by tomasbjerre** [comment]
I'm adding some more details to that log and releaseing that as 1.21 now.

Does this happen if you trigger the job with a `curl` command? To make sure the post content is what you think it is.

**Comment by dkinzer** [comment]
Thanks, your suggestion helped me solve it.

Testing with curl worked:

```bash
 curl -H "Content-Type: application/json" -X POST -d '{ "repository": { "name": "foo" } }'  http://localhost
/jenkins/generic-webhook-trigger/invoke
{"status":"ok","data":{"triggerResults":{"deploy tul_cob to libqa":"OK"}}}
```

So I decided to take a closer look at the webhook configuration and noticed the culprit:

![image](https://user-images.githubusercontent.com/444215/34224111-b7c2505e-e58f-11e7-852a-006ee4348017.png)

After setting content type to `application/json`  all works as expected.

**Comment by tomasbjerre** [comment]
Ok! Same as https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/27
