### ISSUE TITLE
Not compatible with the "Trigger builds remotely" configuration option

### ISSUE THREAD

**Issue by raychinov** [jenkinsci/generic-webhook-trigger-plugin#290]
- Jenkins 2.332.3
- Generic Webhook Trigger Version 1.85.2

When I enable _Trigger builds remotely (e.g., from scripts)_ configuration in a Pipeline Jenkins job, Jenkins responses with `HTTP 404` and:
``` 
{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@example.org/generic-webhook... "}
```

With no other changes, when disable the _Trigger builds remotely_ config, the webhook trigger works as expected.

**Comment by tomasbjerre** [comment]
Here is the logic:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/8d66d67dd7f4e7035bc5a8428c601e6f8e648b2f/src/main/java/org/jenkinsci/plugins/gwt/jobfinder/JobFinder.java#L108

So if you leave the token-field empty in the plugin configuration, and keep a token-value in `Trigger builds remotely`, it should work if you supply the token-value from `Trigger builds remotely`.

The first version of this plugin did not have its own `token`-field. It was added in #63 in 2018, perhaps it is time to simplify this code and just rely on the token-field from this plugin.

**Comment by tomasbjerre** [comment]
Support for `BuildAuthorizationToken` is dropped now in `2.0.0`. The token used by this plugin now must be configured in the plugin config.
