### ISSUE TITLE
All branches are triggered instead of one specific

### ISSUE THREAD

**Issue by MistaMFDOOM** [jenkinsci/generic-webhook-trigger-plugin#296]
### Explain your issue

Hello,

I'm trying to use the plugin with Bitbucket webhooks. I'm using multi-branch pipelines and I'm trying to only trigger the branch "webhook". The issue is where I checkout from webhook to a different branch "webhook2". It now has the same config but shouldn't do anything since it should trigger on push and merge only on the "webhook" branch as per this config:

`regexpFilterExpression: '^.*\\bwebhook\\b.*$'`

This is my config in the Jenkinsfile:

```
    pipelineTriggers([
        [$class: 'GenericTrigger',
            genericVariables: [
            [key: 'branch', value: '$.push.changes[0].new.name'],
            ],
            token: 'abc123',
            causeString: 'Triggered By BitBucket',
            printContributedVariables: true,
            allowSeveralTriggersPerBuild: false,
            printPostContent: true,
            silentResponse: false,
            regexpFilterExpression: '^.*\\bwebhook\\b.*$',
            regexpFilterText: '$branch'
        ]
        ])
])
```

What happens is that on any push / merge events, the webhook and webhook2 branches get triggered.
What am I missing here?

This is what I'm seeing in the webhook logs:

`{"jobs":{"someProduct/Microservices/test-service/webhook2":{"regexpFilterExpression":"^.*\\bwebhook\\b.*$","triggered":true,"resolvedVariables":{"branch":"webhook"},"regexpFilterText":"webhook","id":2924,"url":"queue/item/2924/"},"someProduct/Microservices/test-service/webhook":{"regexpFilterExpression":"^.*\\bwebhook\\b.*$","triggered":true,"resolvedVariables":{"branch":"webhook"},"regexpFilterText":"webhook","id":2923,"url":"queue/item/2923/"}},"message":"Triggered jobs."}`

**Comment by tomasbjerre** [comment]
I see you are using "printPostContent". Have a look at that and your json path to find out why.

**Comment by MistaMFDOOM** [comment]
Where can I see the post content?

**Comment by tomasbjerre** [comment]
In the build log of a triggered job.

**Comment by MistaMFDOOM** [comment]
Thanks for the fast response Tomas. Will check

**Comment by MistaMFDOOM** [comment]
Hey Tomas,

Sorry about my ignorance in this, I usually find my way in logs.

what exactly am I looking for?

see a big payload and at the bottom:

“contributed values: webhook”
This is on a triggered job in the webhook branch. On the webhook2 branch that was also triggered there’s no POST content.

**Comment by tomasbjerre** [comment]
Check the readme, there is information about multibranch pipeline there.

If it is still a problem, open issue again and follow this issue template:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/new?assignees=&labels=bug&projects=&template=1-report-problem.yml
