### ISSUE TITLE
Lacks job selection

### ISSUE THREAD

**Issue by danielbathke** [jenkinsci/generic-webhook-trigger-plugin#3]
If you have 2+ projects on Jenkins and call the URL to invoke, it will build all projects with this plugin enabled. Should be a parameter to set which job to build.

**Comment by tomasbjerre** [comment]
I released 1.5 now that also contributes any request parameters. So that you can add such a parameter and then use the "Optional filter" to only trigger when that parameter has a given value.

Does it solve the issue?

**Comment by danielbathke** [comment]
It ain't on the default plugin directory, https://plugins.jenkins.io/generic-webhook-trigger stills on 1.4
