### ISSUE TITLE
Add a way to test a webhook is triggered but doesn't actually run the job (dry run)

### ISSUE THREAD

**Issue by matthuisman** [jenkinsci/generic-webhook-trigger-plugin#300]
### What feature do you want to see added?

Maybe just a HEADER we can add to the request that tells the plugin to not actually start the job.
Everything else remains the same including the returned Triggered payload etc

**Comment by tomasbjerre** [comment]
Releasing this now. See README: https://github.com/jenkinsci/generic-webhook-trigger-plugin?tab=readme-ov-file#dry-run

**Comment by matthuisman** [comment]
Wow 😲 that's quick.
Really appreciated.
Keep up the awesome work

**Comment by tomasbjerre** [comment]
Thanks for the good idea! I think it is a really nice feature.
