### ISSUE TITLE
Internal error (Error 500)

### ISSUE THREAD

**Issue by random92username** [jenkinsci/generic-webhook-trigger-plugin#301]
### Jenkins and plugins versions report

Hi,

I get a 500 error on some occasions, I'm not sure if it's a bug or if something is missing in the configuration. I have this plugin connected from Jenkins to bitBucket. 
It works correctly when creating, deleting a branch, but at the time of uploading changes gives an error 500 and sends the same execution 3 times giving the same error. 

How can I solve it? What more information can I give you to be able to solve it?

Thank you very much.

Edit:

The tracking of the plugin is as follows: Bitbucket launches a request to a lambda and the lambda is in charge of initiating communication with the plugin. ( El timeout de la lambda dura 3seg )

Having it this way does not always fail showing this error ( error 500 ) which is the error returned by the lambda.

We are using the plugin cache configured with 60min.

Normally it fails when applying changes to release branches.

Attached is a small log of what the lambda and Jenkins returns.

I hope that with this small update we can find the solution to the problem.

Thank you very much for your help.

**Comment by tomasbjerre** [comment]
There should be an exception in the jenkins log. That would be very helpful.

**Comment by random92username** [comment]
Sorry, I just edited the main comment adding more information. @tomasbjerre

**Comment by tomasbjerre** [comment]
No log attached. There is nothing here that can be investigated.

Perhaps try without the cache?

**Comment by tomasbjerre** [comment]
Closing this issue because there is nothing in it that can be investigated.

**Comment by tomasbjerre** [comment]
Possibly same as #304

**Comment by random92username** [comment]
Hi,
Sorry for the little information provided. 
After checking the webhook version we see that we are on version 2.1.0. 
Reviewing the issue provided something similar happens to us. We will try a downgrade. In case the same problem keeps occurring, I would rewrite the provided logs and errors.

Thank you very much, best regards

**Comment by random92username** [comment]
Hello,
Sorry for the little information provided.
After checking the webhook version we see that we are on version 2.1.0.
Reviewing the topic provided we have something similar but it is not exactly the same problem because those error lines shown in the logs do not appear. We have made a review and we do not see any error as in other cases that have been seen.

Do you advise us to try to update to version 2.1.1?

Thank you very much, best regards

**Comment by tomasbjerre** [comment]
I would suggest updating, yes.

**Comment by random92username** [comment]
Hello,

We have upgraded to version 2.1.1 but we still have the same problem. And the logs do not show any errors.

What would you advise us to do?

Thank you very much.
