### ISSUE TITLE
When jenkins pipeline fails the input value of the Token field gets empty.

### ISSUE THREAD

**Issue by nicoko93** [jenkinsci/generic-webhook-trigger-plugin#303]
### Jenkins and plugins versions report

The title is pretty much self explainatory. I would add that the TOKEN field I am talking about is the one above this text : "Optional token. If it is specified then this job can only be triggered if that token is supplied when invoking http://JENKINS_URL/generic-webhook-trigger/invoke. It can be supplied as a: "

**Comment by tomasbjerre** [comment]
I tried this by creating a pipeline like:

```groovy
properties([
    pipelineTriggers([
        GenericTrigger(
            causeString: 'Generic Cause',
            genericVariables: [
                [defaultValue: '', key: 'name', regexpFilter: '', value: '$.app.name']
            ],
            printContributedVariables: true,
            printPostContent: true, 
            regexpFilterExpression: '', 
            regexpFilterText: '', 
            token: 'abc123', 
            tokenCredentialId: ''
        )
    ])
])

node {
    sh """
    thiscommandwillfail
    """
}
```
The command `thiscommandwillfail` does not exist, so this will always fail.

I trigger builds with:

```sh
curl -vs "http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=abc123" 2>&1
```

I can trigger the job several times and the `token` is still there.

Tested with Jenkins `2.426.3` and plugin `2.1.0`.
