### ISSUE TITLE
Multiplying triggers

### ISSUE THREAD

**Issue by lemmuu** [jenkinsci/generic-webhook-trigger-plugin#304]
### Jenkins and plugins versions report

Hello,
Yesterday I update the plugins in Jenkins (currently on 2.440.2) in bulk, amongst them, updating Generic Webhook Trigger to latest (2.1.0) and suddenly I have multiplied triggers for one webhook.

Webhook server log was telling me error code 500, with 5 retries, although the build was triggered indeed 5 times for each POST call.

I am seeing in the Jenkins log messages like:
[id=6297]	SEVERE	o.j.p.g.GenericWebHookRequestReceiver#doInvoke: SecondaryDataMerge
java.lang.NullPointerException: Cannot invoke "hudson.model.Queue$Item.getUrl()" because "item" is null
	at org.jenkinsci.plugins.gwt.GenericTrigger.trigger(GenericTrigger.java:230)
	at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.doInvoke(GenericWebHookRequestReceiver.java:192)
	at org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver.doInvoke(GenericWebHookRequestReceiver.java:98)
...

Also, this was only happening for a few builds, all triggered through the same tunnel, but everything, the jobs, the tunnel is configured in the exact same was as other ones. The only difference between ones that had the issue and ones that didn't was the source of the hook, coming from different Plastic SCM repos.

Rolling back to version 2.0.0 fixes the issue

Pipeline script and build log I think are irrelevant since this issue was happening before running the Pipeline, at the trigger step.

**Comment by tomasbjerre** [comment]
Thanks for reporting. Releasing a fix now in 2.1.1.
