### ISSUE TITLE
Help wanted: Okta one-time verification

### ISSUE THREAD

**Issue by yermulnik** [jenkinsci/generic-webhook-trigger-plugin#306]
### Explain your issue

I have a use case, that is somewhat similar to https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/113, but is a bit different as it is related to Okta.
When one sets up Okta Event Hook, it must pass one-time verification: https://developer.okta.com/docs/guides/event-hook-implementation/nodejs/main/#configure-initial-event-hook-verification — Okta sends `X-Okta-Verification-Challenge` HTTP header and the endpoint has to send a `{"verification": "value_of_X-Okta-Verification-Challenge_header"}` JSON object in response (as response **body**).
I can't seem to figure this out. Any help is much appreciated. Thank you.

**Comment by yermulnik** [comment]
For anyone happen to stumble upon this issue: Okta Support has an option to modify Even Hook from UNVERIFIED to VERIFIED on your request.

**Comment by vignesh-sowmitri** [comment]
How to fix this issue ? I am having the same issue. When i preview and Deliver the event hook, it seems to be working fine. Gives me Delivery successful and i can check the Cloud logs based on the API gateway URL provided. But when i try to verify , its giving me error message. How do i contact Okta support to verify the request ?

**Comment by yermulnik** [comment]
> How do i contact Okta support to verify the request ?

https://support.okta.com/

**Comment by vignesh-sowmitri** [comment]
Hey, I was not able to open Case. I am a System Admin for the OKTA URL that i own and I do have Case Admin permission. But still for some reason it shows as if I dont have the permission.

So i posted my query in Help Center => Community => Questions.

Will that help ?
