### ISSUE TITLE
Possible to clear cache on demand?

### ISSUE THREAD

**Issue by ntfc** [jenkinsci/generic-webhook-trigger-plugin#308]
### Explain your issue

Hello,

First of all, thanks a lot for the plugin as it has greatly helped in setting up a more general webhook handling system!

However one limitation we run into is that once a job is created or configured to use this plugin it takes a long time to start processing webhooks (unless Jenkins is restarted). I understand this is related to some internal caching as explained in https://github.com/jenkinsci/generic-webhook-trigger-plugin?tab=readme-ov-file#cache-jobs

Is there a way to manually or programmatically clear this cache, or to define a shorter TTL?

Thank you!

**Comment by tomasbjerre** [comment]
What version of the plugin do you use?

**Comment by tomasbjerre** [comment]
The way I interpret "takes a long time to start processing webhooks " it sounds like the behavior prior to 2.2.0.

You mean that any request to the plugin will give you 404 and after a "long time" it starts responding with 200?
