### ISSUE TITLE
Wanna get all request body that payload body including null value

### ISSUE THREAD

**Issue by wckhg89** [jenkinsci/generic-webhook-trigger-plugin#31]
I wanna receive all request body including null value for matching secret key

i tried below code for getting request body that payload

```
properties([
            pipelineTriggers([
                [$class: 'GenericTrigger',
                     genericVariables: [
                             [expressionType: 'JSONPath', key: 'body', value: '$'],
                             [expressionType: 'JSONPath', key: 'reference', value: '$.ref'],
                             [expressionType: 'JSONPath', key: 'referenceType', value: '$.ref_type']
                     ],
                     genericHeaderVariables: [
                             [key: 'X-GitHub-Event', regexpFilter: ''],
                             [key: 'X-Hub-Signature', regexpFilter: '']
                     ],

                     regexpFilterText: '',
                     regexpFilterExpression: ''
                ]
            ])
    ])

...


def payLoad = "${env.body}"

echo "${payLoad}'
```

result is not including null value

The expected value contains null, but does not match the X-path-signature value.

How to get request body including null value

cf) The null values ​​are homepage and mirror-url

**Comment by tomasbjerre** [comment]
Can you supply the JSON that you post to the plugin?

**Comment by wckhg89** [comment]
@tomasbjerre 
Sorry, json file is code written by the company and contains information that should not be exposed outside.

however, json file is very similar to https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/github-push-event.json

If the homepage and mirror-url values ​​in the repositry field of the json file are null, it seems that you can not parse the value.

**Comment by wckhg89** [comment]
@tomasbjerre 
I found a code to exclude null

It seems to be returning json object exclude null value in the ``filter`` method in class ``FlattenerUtils`` of the ``org.jenkinsci.plugins.gwt.resolvers package``.

I want a complete payload body json object same as getPostContent method in in class GenericCause

**Comment by tomasbjerre** [comment]
Should be fixed now in 1.23.

**Comment by wckhg89** [comment]
@tomasbjerre 
It's works well. thanks so much

**Comment by hunkjun** [comment]
stages {
        stage('推送') {
            steps {
                echo env.gitlabSourceRepoURL
                echo env.gitlabBranch
            }
        }
    }

## use env is a best way.
