### ISSUE TITLE
 125/5000 gitlab webhook has the following error: {"jobs":null,"message":"Did not find any jobs with GenericTrigger configured! \nA token was supplied.\n"}

### ISSUE THREAD

**Issue by wangkunyu123** [jenkinsci/generic-webhook-trigger-plugin#313]
### Jenkins and plugins versions report

I have added a variable $TOKEN to the Jenkins Generic Webhook Trigger, set it in the TOKEN configuration entry, and also included it in the Groovy script configuration:
triggers {
GenericTrigger (
causeString: 'Triggered by develop',
genericVariables: [[key: 'ref', value: '$.ref'],[key: 'TOKEN', value: '$TOKEN']],
token: '$TOKEN'
)
}
environment {
TOKEN = "develop"
}
I have configured token=develop in the GitLab webhook URL. However, after testing the build, I encountered the following error message: {"jobs":null,"message":"Did not find any jobs with GenericTrigger configured! \nA token was supplied.\n"}
I want to ensure that this plan is feasible.

**Comment by tomasbjerre** [comment]
I would try it with curl first before involving Gitlab.

I would not use environment variable for the token, but hard code token like: `token: 'develop'`.

This looks strange: `[key: 'TOKEN', value: '$TOKEN']`. The value here should be a jsonpath and key the variable to store result.

**Comment by wangkunyu123** [comment]
> 在使用 Gitlab 之前，我会先用 curl 尝试一下。
> 
> 我不会对令牌使用环境变量，而是使用类似这样的硬编码令牌：`token: 'develop'`。
> 
> 这看起来很奇怪：`[key: 'TOKEN', value: '$TOKEN']`。这里的值应该是一个 jsonpath，并且键是存储结果的变量。

Ah, I understand now.  My previous assumption was incorrect.

**Comment by user599** [comment]
> > 在使用 Gitlab 之前，我会先用 curl 尝试一下。
> > 我不会对令牌使用环境变量，而是使用类似这样的硬编码令牌：`token: 'develop'`。
> > 这看起来很奇怪：`[key: 'TOKEN', value: '$TOKEN']`。这里的值应该是一个 jsonpath，并且键是存储结果的变量。
> 
> Ah, I understand now. My previous assumption was incorrect.啊，我现在明白了。我之前的假设是错误的。

Hey, I had the same problem, did you finally find a way to put the token into the environment?
This is my code:
```
    environment {
        PROJECT_NAME = 'demo-jenkins'
    }

    triggers {
        GenericTrigger(
                 ....
                token: "${env.PROJECT_NAME}"
        )
    }
```

**Comment by user599** [comment]
> I would try it with curl first before involving Gitlab.
> 
> I would not use environment variable for the token, but hard code token like: `token: 'develop'`.
> 
> This looks strange: `[key: 'TOKEN', value: '$TOKEN']`. The value here should be a jsonpath and key the variable to store result.

So can I set my token in the environment? When I do this, the token is always null, but the jenkisn environment variable is recognized.
- Custom variable
```
environment {
        PROJECT_NAME = 'demo-jenkins'
    }

    triggers {
        GenericTrigger(
                 ....
                token: "${env.PROJECT_NAME}"
        )
    }
```
![Image](https://github.com/user-attachments/assets/2dfffc66-94e3-4e66-8d21-d829ca87bb29)
-  Jenkisn environment
```
environment {
        PROJECT_NAME = 'demo-jenkins'
    }

    triggers {
        GenericTrigger(
                 ....
                token: "${env.BRANCH_NAME}"
        )
    }
```
![Image](https://github.com/user-attachments/assets/5aaeefeb-2611-4861-94bf-1c3bc5240e59)
