### ISSUE TITLE
Did not find any jobs with GenericTrigger configured!\nA token was supplied.\n

### ISSUE THREAD

**Issue by CarryWll** [jenkinsci/generic-webhook-trigger-plugin#316]
### Jenkins and plugins versions report

* Plugin version：2.2.1
* Jenkins version：2.455
1. I set up a multi-branch pipeline with jenkins. In this project, there are three branches: a, dev, and c. I only need to build the dev branch, so I only added Jenkinsfile in the dev branch. a, c did not add Jenkinsfile.
```
pipeline {
    agent any
    triggers {
        GenericTrigger (
            causeString: 'Triggered by dev',
            genericVariables: [[key: 'ref', value: '$.ref']],
            printContributedVariables: true,
            printPostContent: true,
            regexpFilterExpression: 'refs/heads/' + BRANCH_NAME,
            regexpFilterText: 'refs/heads/dev',
            token: '123456'
        )
    }
    stages {
        stage('test') {
            sh 'echo test'
        }
    }
}
```
Because Jenkins multi-branch pipeline has no interface to set generic-webhook-trigger-plugin
![image](https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/54405475/180997cf-5964-4d33-97cd-257589bfa71b)
So after I add and complete the above file, I scan the entire project, and I can check the configuration on the page.
![image](https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/54405475/f0bd7146-2515-4ed1-9ee9-0d921b09d671)，But I http://127.0.0.1:8080/generic-webhook-trigger/invoke?token=123456
The result is:
```json
{
    "jobs": null,
    "message": "Did not find any jobs with GenericTrigger configured!\nA token was supplied.\n"
}
```

```sh
curl -v "http://JENKINS-SERVER/generic-webhook-trigger/invoke?token=123456" -H "Content-Type: application/json" -d "{\"ref\": \"refs/heads/master\"}"
```
response result：
```json
{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured!\nA token was supplied.\n"}
```
2. When I build an ordinary pipeline, select and configure it on the page, it can be successfully called.

![image](https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/54405475/2e9b1eaf-0d4f-4374-9353-82b4bb9e9410)

**Comment by tomasbjerre** [comment]
- Use English 
- Supply curl command

**Comment by tomasbjerre** [comment]
You give it the master branch in your example, you should change that to `refs/heads/dev`.

`curl -v "http://JENKINS-SERVER/generic-webhook-trigger/invoke?token=123456" -H "Content-Type: application/json" -d "{\"ref\": \"refs/heads/dev\"}"`

You also need to scan with multibranch pipeline. After that, verify that the job is created and with the intended configuration.

Once you have a job configured, try with the curl command again.

**Comment by CarryWll** [comment]
> You give it the master branch in your example, you should change that to `refs/heads/dev`.
> 
> `curl -v "http://JENKINS-SERVER/generic-webhook-trigger/invoke?token=123456" -H "Content-Type: application/json" -d "{\"ref\": \"refs/heads/dev\"}"`
> 
> You also need to scan with multibranch pipeline. After that, verify that the job is created and with the intended configuration.
> 
> Once you have a job configured, try with the curl command again.

I changed master to dev, still the same error result.
```json
{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured!\nA token was supplied.\n"}
```
and My multi-branch pipeline has been successfully configured, but it is not editable on the interface. It is automatically generated from Jenkinsfile.
![1719841264264](https://github.com/jenkinsci/generic-webhook-trigger-plugin/assets/54405475/639a7221-92e3-421c-8511-50f294a066f5)

**Comment by tomasbjerre** [comment]
You can try restart Jenkins. If that solves it, it might be same problem as #311 #312

**Comment by CarryWll** [comment]
> You can try restart Jenkins. If that solves it, it might be same problem as #311 #312

Thank you very much, The problem was successfully solved after restart.
