### ISSUE TITLE
changed_files regexpFilterExpression doesn't work

### ISSUE THREAD

**Issue by DreamPWJ** [jenkinsci/generic-webhook-trigger-plugin#318]
### Explain your issue

I want to automate the build based on the module name recorded in git commit， But no matter how I write it, it doesn't work
`regexpFilterText: '_$ref_$git_message_$changed_files', regexpFilterExpression: '^' + '_(refs/heads/' + "${BRANCH_NAME}" + ')' + '_(release)' + '.*' + '_(.*'+ "${(IS_MONO_REPO == true || IS_MAVEN_SINGLE_MODULE == false) ? '\\' + "${PROJECT_NAME}" + '\\' : ''}"  + '.*)'`

**Comment by DreamPWJ** [comment]
“pengbo-park/pengbo-park-app/src/main/java/com/pengbo/park/app/controller/weixn/WeiXinPayController.java” get pengbo-park-app regexp is it not OK

**Comment by DreamPWJ** [comment]
@tomasbjerre  Why is it so urgent to close? It's not a bug, just asking how to write

**Comment by DreamPWJ** [comment]
Because the document is relatively simple, I can only ask questions here

**Comment by tomasbjerre** [comment]
Impossible for me to help if you dont provide needed information.
