### ISSUE TITLE
files changed in a Pull Request 

### ISSUE THREAD

**Issue by flutca** [jenkinsci/generic-webhook-trigger-plugin#323]
### Jenkins and plugins versions report

The list of files changed in a Pull Request (PR) is not being retrieved using the following syntax: $.commits[*].['modified','added','removed'][*]. This issue persists even when the PR involves a larger number of changed files, such as 11 files. Is there an alternative method to successfully retrieve the full list of changed files in a PR?

The PR contains multiple push.  And we like to catch the list of files also for reopened. In case PR was closed.

**Comment by tomasbjerre** [comment]
Read issue template
