### ISSUE TITLE
Having issue parsing github request

### ISSUE THREAD

**Issue by lubronzhan** [jenkinsci/generic-webhook-trigger-plugin#330]
### Jenkins and plugins versions report

Plugin version: `2.2.5`
Jenkins verison: `2.452.2`
I was trying to use example https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/3e649137695947d30c8c6437b249780e6454e081/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github/github-pull-request.feature#L7 here to parse the github post body using jsonPath
But github post body is wrapped in a `payload` element now. for example
```
{
    "payload": [
        {"action":"created"}
    ]
}
```
Then using `$.action` doesn't return anything for action.
Example jenkins config file I have
```
pipeline {
    agent {
        node {
        }
    }
  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'payload', value: '$.payload[0]'],
      [key: 'action', value: '$.action']
     ],

     causeString: 'Triggered on $action',

     token: 'token1',

     printContributedVariables: true,
     printPostContent: true,

     silentResponse: false,

     shouldNotFlatten: false,
    )
  }
  stages {
    stage('Some step') {
      steps {
        sh "echo $payload"
        sh "echo $action"
      }
    }
  }
}

```
Running the pipeline got below error
```
14:47:25  Also:   org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: f89c7f77-e85b-40d7-a209-583ddb326aa7
14:47:25  groovy.lang.MissingPropertyException: No such property: action for class: groovy.lang.Binding
14:47:25  	at groovy.lang.Binding.getVariable(Binding.java:63)
14:47:25  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:285)
14:47:25  	at org.kohsuke.groovy.sandbox.impl.Checker$7.call(Checker.java:375)
```

Even if I change from `$.action` to `$.payload[0].action`, still nothing returns. I can only get the output of `$.payload[0]`

Does anyone also run into this?

**Comment by tomasbjerre** [comment]
Works on my machine.

I created a pipeline like this:

```

 node {
 properties([
  pipelineTriggers([
   [$class: 'GenericTrigger',
     genericVariables: [
      [key: 'payload', value: '$.payload[0]'],
      [key: 'action', value: '$.action']
     ],

     causeString: 'Triggered on $action',

     token: 'token1',

     printContributedVariables: true,
     printPostContent: true,

     silentResponse: false,

     shouldNotFlatten: false,
   ]
  ])
 ])

 stage("build") {
  sh "echo $payload"
 }
}
```

I run that, manually, and I get your error. And that is totally ok, as long as the properties are applied and they are.

I trigger it with:
```
curl -v \
 -H "Content-Type: application/json" \
 -X POST \
 -d '{ "payload": [ {"action":"created"} ] }' \
 "http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=token1"
```

It triggers and logs:

```
 Received:

{ "payload": [ {"action":"created"} ] }


Contributing variables:

    payload = {"action":"created"}
    payload_action = created


[Pipeline] node
Running on [Jenkins](http://localhost:8080/jenkins/computer/(built-in)/) in /home/bjerre/workspace/generic-webhook-trigger-plugin/work/workspace/gh
[Pipeline] {
[Pipeline] properties
[Pipeline] stage
[Pipeline] { (build)
[Pipeline] sh
+ echo {action:created}
{action:created}
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
Finished: SUCCESS
```

**Comment by lubronzhan** [comment]
Sorry forgot to put the jenkins version 2.452.2. Which jenkins version is yours? I guess it shouldn't be related to jenkins version?
I also tried your scripted jenkins file, I only saw payload got contributed, not payload_action
```
Contributing variables:
10:05:57  
10:05:57      payload = {"action":...
```

I directly use github to send the request, since curling our jenkins requires a crumb.

Right now the workaround I have is to parse that payload in the script to get information I need.

**Comment by tomasbjerre** [comment]
I tested with `2.414.3`.

**Comment by dbratanis** [comment]
Hello, Jenkins 2.462.3 , same issue trying to map the variables from the Github Webhook with no success. Receiving the same error as shown in the authors post.

**Comment by Kurt-Larson** [comment]
We're getting exactly the same problem the plug-in's JSONPath experssion not being able query anything deeper than "$.payload[0]" with the Payload of a Webhook request from GitHub (an internal only GitHub Enterprise Server v3.14.3).

Jenkins 2.443
Generic Webhook Plugin 2.2.5

**Comment by lubronzhan** [comment]
Turns out that I forgot to change the content type to `application/json` in the github hook
![Image](https://github.com/user-attachments/assets/1c4cd052-ff15-40be-b1c6-fd3f47b18af6)
cc @Kurt-Larson
