### ISSUE TITLE
Is this possible to trigger certain Jenkins job [Question]

### ISSUE THREAD

**Issue by ddimitrioglo** [jenkinsci/generic-webhook-trigger-plugin#36]
Let's assume that we have:

* `jenkins-test-1` repo and we have `jenkins-test-1` job
* `jenkins-test-2` repo and we have `jenkins-test-2` job

And both of the repos have webhook (http://username:password@jenkins_url/generic-webhook-trigger/invoke) configured.
This is triggering both the jenkins jobs `jenkins-test-1` & `jenkins-test-2`

Is this possible to trigger only one of them (for example by passing a GET parameter with job name)?

**Comment by tomasbjerre** [comment]
Yes.

I usually set a different `token` for each job and pass that with `?token=....`.

Or just pass any get-parameter, resolve it to a variable, use the regexp filter/text to only trigger if that parameter has a specific value.

**Comment by arahja** [comment]
I am experiencing this issue as well, I have been passing the token in but multiple build jobs are still kicking off.

This is my curl string triggering multiple build jobs:
curl --insecure --user username:api_token https://buildserver.domain.name/generic-webhook-trigger/invoke?token=NblctU4JaDoykLe8rtQgjV7I3kA5WhDr

**Comment by tomasbjerre** [comment]
Probably because you authenticate with both a user and the token. Perhaps if you skip the `--user username:api_token`.

If that does not work, then use the filter-feature. I added this to the readme as well.

**Comment by arahja** [comment]
Pardon my ignorance. If I run the following: curl --insecure --user username:api_token https://buildserver.domain.name/generic-webhook-trigger/invoke?buildToken=NblctU4JaDoykLe8rtQgjV7I3kA5WhDr

In my build, I then select "This project is parameterized" and set a string parameter Name to "buildToken".

In the optional filter section, I would then set the Text field to "$buildToken" and the Expression field to "^NblctU4JaDoykLe8rtQgjV7I3kA5WhDr$"

Am I making the correct assumptions?

**Comment by ddimitrioglo** [comment]
@tomasbjerre Thank you! It really works and really helpful!
