### ISSUE TITLE
Logic in "Optional filter" text field [question]

### ISSUE THREAD

**Issue by ddimitrioglo** [jenkinsci/generic-webhook-trigger-plugin#39]
I would like to add some logic by concatenating strings/variables in `Optional filter` text field.

For example: 
* concatenate string w/ variable `$FILTER_VAR'customstring'`
* concatenate variables `$FILTER_VAR$ANOTHER_VAR`

Is it possible or I can workaround this?

**Comment by tomasbjerre** [comment]
If `$FILTER_VAR` is ABC and `$ANOTHER_VAR` is DEF then:

* `$FILTER_VAR'customstring'` should be `ABC'customstring'`.
* `$FILTER_VAR$ANOTHER_VAR` should be `ABCDEF`.

If that does not work, then it is a bug!

**Comment by ddimitrioglo** [comment]
So, to get `ABCsomestring` I need to do like this: `$FILTER_VARsomestring`? 
Wont this conflict with `${FILTER_VARsomestring}` variable?

**Comment by ddimitrioglo** [comment]
@tomasbjerre Thanks, your approach worked, in spite the fact that it looks weard ${FILTER_VARsomestring} 😉

**Comment by tomasbjerre** [comment]
No no conflict. The second syntax is not used for variables in this plugin. Ok great!
