### ISSUE TITLE
Did not find any jobs to trigger!

### ISSUE THREAD

**Issue by iFunbox** [jenkinsci/generic-webhook-trigger-plugin#4]
Apr 29, 2017 8:36:42 AM org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver doInvoke
INFO: Did not find any jobs to trigger! The user invoking /generic-webhook-trigger/invoke must have read permission to any jobs that should be triggered.

I use postman request everything is ok,but gitlab webhook error.
What is the problem , thanks.

**Comment by tomasbjerre** [comment]
You are probably authenticated in postman but not in gitlab. Did you add username/password in gitlab?

**Comment by tomasbjerre** [comment]
I added a troubleshooting section to the readme. Perhaps it helps.

**Comment by iFunbox** [comment]
solved~~  thanks
