### ISSUE TITLE
Header parameter not available for Optional Filter text

### ISSUE THREAD

**Issue by gmanfunky** [jenkinsci/generic-webhook-trigger-plugin#40]
Thanks a ton for this project.. 

I will dive deeper, but after a couple hours I wanted to file an issue with a simplified test case. 

I am able to get Request Parameters parsed into the Text for the Optional Filter, but it seems like the HTTP header variable isn't getting interprolated. 

For example, webhook configuration like this:
![image](https://user-images.githubusercontent.com/1102928/36336547-896cdf68-133d-11e8-936b-00aa226b6138.png)

But a curl like 
`curl -v -H 'TESTHEADER: testValue' https://example.com/generic-webhook-trigger/invoke?token=
GABE`

Returns a json response without the parameter substution.
![image](https://user-images.githubusercontent.com/1102928/36336587-f0837e0a-133d-11e8-83dc-8e74990a553c.png)

I re-configured it with Request Parameter and it gets replaced and matched as expected. 

I'm actually trying to match `X-GitHub-Event: pull_request` in my Optional Filter, but I whittled it down to a simple header without dashes for this test.  

I'll go looking at the test code next, and maybe even go grab a JDK to possibly help. But i wanted to check if anything seemed out of sorts to others too. 

Thanks again for the project!

**Comment by gmanfunky** [comment]
I went through the unit tests and mocked up a similar situation and didn't find a problem. Then I went back to testing and was able to get `$Accept` resolved., and even got `$X_GitHub_Event` to resolve how i needed it from github. (After I noticed that variable names change to snake_case)

This all makes me believe this is just my setup and maybe just the way my `curl` is behaving on windows.

**Comment by gmanfunky** [comment]
https://github.com/jenkinsci/generic-webhook-trigger-plugin/pull/41

**Comment by tomasbjerre** [comment]
Looks like the header variables are not even resolved. All resolved variables should be in the response.

I setup a couple of jobs and triggered them with:
`curl -v -H 'TESTHEADER: testValue' -H 'other-header: otherval' http://localhost:8080/jenkins/generic-webhook-trigger/invoke?token=GABE`

I got:
```
{  
   "status":"ok",
   "data":{  
      "triggerResults":{  
         "free2":{  
            "id":9,
            "regexpFilterExpression":"testValue",
            "regexpFilterText":"testValue",
            "resolvedVariables":{  
               "TESTHEADER":"testValue",
               "TESTHEADER_0":"testValue"
            },
            "searchName":"",
            "searchUrl":"",
            "triggered":true,
            "url":"queue/item/9/"
         },
         "free1":{  
            "id":8,
            "regexpFilterExpression":"testValue",
            "regexpFilterText":"testValue otherval",
            "resolvedVariables":{  
               "TESTHEADER":"testValue",
               "other_header_0":"otherval",
               "other_header":"otherval",
               "TESTHEADER_0":"testValue"
            },
            "searchName":"",
            "searchUrl":"",
            "triggered":true,
            "url":"queue/item/8/"
         }
      }
   }
}
```

So the issue can be closed right?

**Comment by gmanfunky** [comment]
Yes. I will come back with a small update once I figure out exactly what is wrong with my situation beyond the plug-in. Thanks!

**Comment by gmanfunky** [comment]
For me, this was an HTTPv2 issue. I realized I multiple versions of `curl` on my host... one with HTTP2 support. Forcing the request via `curl --http1.1` had the plugin set my header variable set as expected.

**Comment by gmanfunky** [comment]
I've learned that HTTP headers are supposed to be case insensitive, according to the HTTP spec, but many do not adhere to this. HTTP/2 (e.g., an nginx reverse proxy with SSL cert) will encode headers as lowercase. 

I see that Jenkins has made some changes over the last year or two to be more header case insensitive. It might be a nice enhancement for `generic-webhook-trigger` to be case insensitive too.
