### ISSUE TITLE
"This project is parameterized" parameters are being ignored if triggered

### ISSUE THREAD

**Issue by jbobaggins** [jenkinsci/generic-webhook-trigger-plugin#45]
Our SCM tool is sending PR events to trigger our builds but the default parameters that we set get ignored and are not present in the environment.

1) Create Pipeline Job
2) Check "This project is parameterized"
3) Add dummy parameter
4) setup generic webhook trigger with your repo
4) Manually build project - pass: dummy parameter is present
5) Trigger the job with a commit - fail: dummy parameter is not present

Workaround:
Define all parameters in generic webhook trigger section... this means we have to define everything twice

**Comment by tomasbjerre** [comment]
I released a fix for that in 1.29 now!

**Comment by jbobaggins** [comment]
Awesome, thanks a lot @tomasbjerre
