### ISSUE TITLE
Declarative Pipeline support

### ISSUE THREAD

**Issue by MichalPloski** [jenkinsci/generic-webhook-trigger-plugin#47]
It would be nice to have a chance to use this plugin with declarative pipeline under trigger sections.
In my case we have all pipelines written in declarative way except one using generic trigger.

**Comment by tomasbjerre** [comment]
Should be fixed now in 1.33. Open issue again if not working.

**Comment by berkesokhan** [comment]
Would you mind sharing a usage snippet under a declarative pipeline's triggers section so we may try?

**Comment by tomasbjerre** [comment]
I added an example now.

**Comment by berkesokhan** [comment]
Thanks!  Saw the README, I will report if we found any errors.

**Comment by ntindall** [comment]
I'm not able to get the README example working @tomasbjerre 

The webhook is successfully triggered (it causes the job to run), but I can't get any of the JSON parsing / extraction logic to work... any ideas?

**Comment by albertinisg** [comment]
I'm following the documentation and I'm facing a weird issue with the declarative pipeline. If I configure the plugin using the interface, everything works and I get the right output:
```json
{
    "status": "ok",
    "data": {
        "triggerResults": {
            "ci-playground": {
                "id": 38751,
                "regexpFilterExpression": "",
                "regexpFilterText": "",
                "resolvedVariables": {},
                "triggered": true,
                "url": "queue/item/38751/"
            }
        }
    }
}
```
But if I follow the documentation example for the declarative pipeline, the job is never triggered. I should be missing something simple, but can't find out what...

Plugin version: **1.46**

My pipeline is declared as:
```groovy
pipeline {
  agent any
  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: '$.ref']
     ],
     
     printContributedVariables: true,
     printPostContent: true
    )
  }
  stages {
    stage('Some step') {
      steps {
        sh "echo $ref"
      }
    }
  }
}
```
So then I call it like:
```bash
$ curl -X POST -H "Content-Type: application/json" -d '{ "before": "1848f12", "after": "5cab1", "ref": "refs/heads/develop" }' --insecure -v "https://<user>:<pass>@<myjenkinsinstance>/generic-webhook-trigger/invoke"
```
And I get a 200 OK, but the job doesn't start:
```
> POST /generic-webhook-trigger/invoke HTTP/1.1
> Host: XXXXXXXXXXXXXXXX
> Authorization: Basic XXXXXXXXXXXXXXX
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 70
> 
* upload completely sent off: 70 out of 70 bytes
< HTTP/1.1 200 OK
< Server: nginx/1.13.10
< Date: Wed, 07 Nov 2018 11:30:17 GMT
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Content-Type-Options: nosniff
```
What am I missing?

**Comment by tomasbjerre** [comment]
Might be same as https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/84 and/or https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/81 but they were never really resolved.

You could try adding a `token` and supply that in your request. But even if that works it is still strange because the plugin should have responded with a clear message telling you to do that: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/GenericWebHookRequestReceiver.java#L33

You comment contains `< Server: nginx/1.13.10` which is interesting. Are you sure Jenkins is being invoked? Perhaps it is a proxy responding with HTTP 200.

**Comment by albertinisg** [comment]
Thanks for the superquick response!

Modified the pipeline to add the token:
```groovy
pipeline {
  agent any
  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: '$.ref']
     ],
     
     token: 'abc123',
     
     printContributedVariables: true,
     printPostContent: true
    )
  }
  stages {
    stage('Some step') {
      steps {
        sh "echo $ref"
      }
    }
  }
}
```
Then triggered providing the token with the 3 different ways possible: as a parameter, in the header and bearer token; no success.

About the nginx, if I configure the plugin with the interface I get it to work even with the nginx in between:
```bash
> POST /generic-webhook-trigger/invoke HTTP/1.1
> Host: XXXXXXXXXXXXXXXXXX
> Authorization: Basic XXXXXXXXXXXXXXXXXXXX
> User-Agent: curl/7.52.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 70
> 
* upload completely sent off: 70 out of 70 bytes
< HTTP/1.1 200 OK
< Server: nginx/1.13.10
< Date: Wed, 07 Nov 2018 11:48:54 GMT
< Content-Type: application/json;charset=utf-8
< Content-Length: 231
< Connection: keep-alive
< X-Content-Type-Options: nosniff
< 
{"status":"ok","data":{"triggerResults":{"ci-playground":{"id":38758,"regexpFilterExpression":"","regexpFilterText":"","resolvedVariables":{"ref":"refs/heads/develop
```
Is there any scenario where the plugin returns just a 200 OK? Otherwise there might be something with the nginx yes... But still weird that it works with the interface and not the pipeline itself

**Comment by tomasbjerre** [comment]
What do you mean with "if I configure the plugin with the interface"? Is that by using the GUI?

And when using the pipeline, do you use multibranch pipeline plugin? Did you make sure the multibranch job has been launched to synk with the Git repositories?

If not using multibranch pipeline, I'm not really sure how that works. I guess the properties are applied to a job when the pipeline is run.

Anyway, when using properties from a pipeline, you may browse to the jobs and check what configuration has been applied to them. By simply viewing the jobs configuration in the GUI.

I usually script all jobs with Job DSL plugin and let Job DSL configure this plugin. The jobs created by Job DSL are pipelines and I have no configuration of this plugin in my pipelines.

**Comment by tomasbjerre** [comment]
Releasing 1.47 now with a fix. So that the plugin will print information when no jobs were found and not be silent. Still that does not solve the actual issue for you.

**Comment by albertinisg** [comment]
> Releasing 1.47 now with a fix. So that the plugin will print information when no jobs were found and not be silent. Still that does not solve the actual issue for you.

Just seen that :D thanks a lot!!

**Comment by albertinisg** [comment]
I did test it with the Job DSL with no success either :(

Also, now with the same pipeline I had before, I can see more information in the response, which is great!
```json
{
    "status": "ok",
    "data": {
        "triggerResults": {
            "ANY": "Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@jenkins/generic-webhook... "
        }
    }
}
```
Anyway, I was just trying to set it up for a simple example and just filter as explained in the doc, but couldn't make it work through the GUI either. With the following configuration, it triggers the build no matter the body of the POST. The plugin is configured as follows and I set the regexp as in the Gherkin test in https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github/github-push-tag.feature:

![gui-conf](https://user-images.githubusercontent.com/8257425/48405683-0e0ecf00-e733-11e8-9c4d-480c92ae3370.PNG)

After that, I make the same request with different body:

```json
{ "before": "1848f12", "after": "5cab1", "ref": "refs/tags/develop" }
{ "before": "1848f12", "after": "5cab1", "ref": "refs/heads/develop" }
```

And both requests starts the build:
```json
{
    "status": "ok",
    "data": {
        "triggerResults": {
            "ci-playground": {
                "id": 39047,
                "regexpFilterExpression": "",
                "regexpFilterText": "",
                "resolvedVariables": {},
                "triggered": true,
                "url": "queue/item/39047/"
            }
        }
    }
}
```
To me it looks interesting that the fields `regexpFilterExpression`, `regexpFilterText` and `resolvedVariables` are empty. They shouldn't be, right?

**Comment by tomasbjerre** [comment]
Perhaps you did not mean to have that advanced regexp in the value filter of the ref parameter? The text just below the field explains what it does.

And you have other field below, not shown inte your screenshot, for regexpFilterExpression and regexpFilterText .

**Comment by albertinisg** [comment]
Damn... you are 100% right... I added the regular expression in `regexpFilterExpression` and the variable in `regexpFilterText` and I can see it now in the response and it blocks the triggering:

```json
{
    "status": "ok",
    "data": {
        "triggerResults": {
            "ci-playground": {
                "id": 0,
                "regexpFilterExpression": "^(refs/tags/.+)$",
                "regexpFilterText": "$ref",
                "resolvedVariables": {},
                "triggered": false,
                "url": ""
            }
        }
    }
}
```
Thanks a lot for all your patience and support!! :)
