### ISSUE TITLE
Turn 'Optional filter' to negative matching

### ISSUE THREAD

**Issue by kdeenkhoorn** [jenkinsci/generic-webhook-trigger-plugin#49]
If i use the webplugin with an Optional filter this option is allways positive.
If the value does match the expression the build is trigert.

But i like to be able to state under witch condition i like to skip the build.
Say if user is 'build' i like to skip the build. Any other user is fine.

How do i accomplish this ?

**Comment by tomasbjerre** [comment]
Here is an example that triggers if the user is not "jenkins":

https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/java/org/jenkinsci/plugins/gwt/GenericTriggerTest.java#L37

**Comment by kdeenkhoorn** [comment]
Weird, if i use ^((?!BUILD_USER))$ it does not work.
If i use ^((?!BUILD_USER).)*$ it works.
What is the diference ?

My variable contains ACTOR = "MY_NAME"

Logging:

Triggering GenericTrigger [genericVariables=[GenericVariable [expressionType=JSONPath, key=ID, value=$.pullRequest.id, regexpFilter=], GenericVariable [expressionType=JSONPath, key=ACTOR, value=$.actor.name, regexpFilter=]], regexpFilterText=$ACTOR, regexpFilterExpression=^((?!iBUILD_USER))$, genericRequestVariables=null]
Mar 22, 2018 11:28:20 AM INFO org.jenkinsci.plugins.gwt.GenericTrigger isMatching
Not triggering "^((?!iBUILD_USER))$" not matching "My_NAME".


Thanks in advance.

**Comment by kdeenkhoorn** [comment]
Forgot to mention, the plugin version is 1.10 on Jenkins 2.60.1

**Comment by tomasbjerre** [comment]
Perhaps remove the `$` at the end of regexp or move it inside the parenthesis.

**Comment by ximbal** [comment]
So you are saying that if I set the username of the user committing to "Jenkins" it will ignore it and skip the build????, if so, that is exactly the behavior I am trying to achieve.

**Comment by tomasbjerre** [comment]
It is all about the json string. if "set the username of the user " means you change the json being sent, then yes.

You should continue this discussion in the issue you originally created. Closing this one as the reporter dos not respond.

**Comment by kdeenkhoorn** [comment]
Hi, due to courses and work i was not able to answer in time. It seems that ^((?!BUILD_USER).)*$ is the only thing that works for me. Have tried different notations also the one 'hidden' in your code but i can not get that notation to work. This solution is fine for me at this moment. Thanks for the support.

Kl@@s

**Comment by kdeenkhoorn** [comment]
Thanks for the quick support, keep up the good work!
