### ISSUE TITLE
Doesn't work with Pipelines

### ISSUE THREAD

**Issue by svenbs** [jenkinsci/generic-webhook-trigger-plugin#5]
It seems this plugin is not working with pipelines.

In the Jenkinsfile I've this properties are configured:
properties([buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '', daysToKeepStr: '', numToKeepStr: '5')), pipelineTriggers([[$class: 'GenericTrigger', regexpFilterExpression: '', regexpFilterText: '']])])

I've just scanned your source-code and I think a function for PipelineTriggers is missing.

**Comment by tomasbjerre** [comment]
Did you try the example from the wiki page or from the readme here in the repo?
What exactly is the error you are getting?

**Comment by tomasbjerre** [comment]
Do you know what is missing? I did not find any documentation about anything special that needs to be implemented to support this.

**Comment by svenbs** [comment]
I've followed the reade from the repo, by using the Jenkins-WebUI. But I've also implemented the pipelineTriggers into a Jenkinsfile. With freestyle-jobs it works out of the box.

I just started working with jenkins this week, so I'm not deep enough into the matter.

So this is just a vague guess and maybe helps to identify the issue. If you export the job-defitions via jenkins-cli you can see that freestyle-jobs have their triggers defined in the first XML-level:
`"project" -> "triggers"`

While triggers for pipelines are defined below  
`"project" -> "properties" -> "org.jenkinsci.plugins.workflow.job.properties.PipelineTriggersJobProperty" -> "triggers"`

Maybe there is a class to get these triggers?

I'll attach both job definitions for review.

[freestyle-job.xml.gz](https://github.com/jenkinsci/generic-webhook-trigger-plugin/files/967019/freestyle-job.xml.gz)

[pipeline-job.xml.gz](https://github.com/jenkinsci/generic-webhook-trigger-plugin/files/967020/pipeline-job.xml.gz)

**Comment by tomasbjerre** [comment]
Is the pipeline a multi branch pipeline or just a regular pipeline?

**Comment by svenbs** [comment]
It's a regular pipeline.

**Comment by tomasbjerre** [comment]
I suspect properties only work for multibranch pipeline.

**Comment by svenbs** [comment]
I've just tested a multibranch pipeline, unfortunately it didn't work either.

Steps I've taken:
1. Create a new multibranch pipeline element
2. enable "generic webhook trigger" without any further configurations
3. trigger a build via http://JENKINS_URL:8080/generic-webhook-trigger/invoke
4. The build for the freestyle-job hast started, that for the multibranch pipeline did not.

If you need more debug information please let me know.

**Comment by tomasbjerre** [comment]
I've been debugging it a bit. First problem seems to be [JobFinder](https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/JobFinder.java).  It does not find `org.jenkinsci.plugins.workflow.job.WorkflowJob`. Bit if it's changed like this, then that is solved:
```
  public static List<GenericTrigger> findAllJobsWithTrigger() {
    List<GenericTrigger> found = new ArrayList<>();
    List<ParameterizedJob> candidateProjects =
        Jenkins.getInstance().getAllItems(ParameterizedJob.class);
    for (ParameterizedJob candidateJob : candidateProjects) {
      GenericTrigger genericTriggerOpt = findGenericTrigger(candidateJob.getTriggers());
      if (genericTriggerOpt != null) {
        found.add(genericTriggerOpt);
      }
    }
    return found;
  }

  private static GenericTrigger findGenericTrigger(Map<TriggerDescriptor, Trigger<?>> triggers) {
    if (triggers == null) return null;
    for (Trigger<?> candidate : triggers.values())
      if (candidate instanceof GenericTrigger) return (GenericTrigger) candidate;
    return null;
  }
```

But then I get a `ClassCastException` in [GenericTrigger](https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/GenericTrigger.java) on `job.scheduleBuild2`.

**Comment by tomasbjerre** [comment]
I'm releasing a fix now as 1.9. Should be available within a few hours. Open issue again if not working!

**Comment by tomasbjerre** [comment]
I tested it with a Jenkinsfile like this:
https://github.com/tomasbjerre/sandbox/blob/master/Jenkinsfile
And for multibranch pipeline.

**Comment by svenbs** [comment]
Pipelines are triggered now. Thanks!

**Comment by stadia** [comment]
`WorkflowScript: 3: The properties section has been renamed as of version 0.8. Use options instead.`

**Comment by savinov** [comment]
Scripted version works with regular pipeline as well.
Please note in docs that pipeline doesn't have to be a multibranch.

**Comment by Ordiel** [comment]
What about multi branch pipelines, any way to get that working?

**Comment by tomasbjerre** [comment]
Yes

**Comment by Ordiel** [comment]
which is...?

I ask since I am having the same issue trying to get the following working:

```
properties properties([$class: 'com.tikal.hudson.plugins.notification.HudsonNotificationProperty', endpoints: [
    [buildNotes: '', retries: 3, urlInfo: [urlOrId: 'https://imagine.a.url/abcde', urlType: 'PUBLIC']]
]])```

**Comment by tomasbjerre** [comment]
I dont see how that relates to this plugin. If it does, open a new issue and clearly  describe your use case. Make sure to check the readme first.
