### ISSUE TITLE
Want to get the entire payload (cause.getPostContent() )

### ISSUE THREAD

**Issue by karthickrc** [jenkinsci/generic-webhook-trigger-plugin#50]
I am trying to use this awesome plugin to get the non modified received body. so that I can send the paylaod as it is to a kafka using curl.
using Post content parameters - variale PAY_LOAD giving the modified information.

How can I access the actual payload which gets printed under GenericWebhookEnvironmentContributor
 Received: ? 

Please help!

**Comment by tomasbjerre** [comment]
If you specify the JSONPath as just $ then that should evaluate to all json.

Den mån 26 mars 2018 21:16karthickrc <notifications@github.com> skrev:

**Comment by karthickrc** [comment]
Thanks for quick response. I tried that option still not pulling the pull body into shell

My config:
**post contenet parameters** : variable BODY
Expression : $
Checked JsonPath

in Execute Shell:
 echo $BODY

Still dont see the complate payload. 

NOte : when I use $PAYLOAD shows content, but it has stripped out the key names from body.

Once you help me on this I should be able to push event o kafka. Wiating for your response. 

your plugin is awesome. 

Thanks

**Comment by tomasbjerre** [comment]
What does  body evaluate to? Do you have latest version? The payload variable is not from this plugin unless you configured that variable as well.

**Comment by karthickrc** [comment]
Thanks for clarifying it. I was trying to use PAYLOAD variable as a custom one which was causing the problem.
After using as BODY with $ as you specified I am able to get the actual payload. 
Thanks again.

**Comment by tomasbjerre** [comment]
Great!

**Comment by yuchengren** [comment]
> Thanks for clarifying it. I was trying to use PAYLOAD variable as a custom one which was causing the problem. After using as BODY with $ as you specified I am able to get the actual payload. Thanks again.

I get the same problem, I need the raw json body，but $BODY is not a json ，but a JSONPATH String. Can you tell me how you solute this problem ,for more detail, thanks very much^^
