### ISSUE TITLE
Is there a way to use this plugin to prevent builds for specific user commits?

### ISSUE THREAD

**Issue by ximbal** [jenkinsci/generic-webhook-trigger-plugin#51]
I have a classic scenario, I have a pipeline that commits changes into github with a service account, obviously I am on an infinite loop scenario, is there a way to filter out commits from specific users and avoid this infinite loop?

Thank you

**Comment by tomasbjerre** [comment]
You may
1. Resolve the committer or maby commit message from the webhook json.
2. Add a filter regexp/string that matches on the service users commit.

You can have a look at this issue as well: https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/49

**Comment by ximbal** [comment]
Following that same logic I've tried:
![image](https://user-images.githubusercontent.com/19576367/37985079-de09d584-31c5-11e8-8bdb-760b7fc3b226.png)

And it didn't seem to work, it still triggers the build, all I need is to avoid commits made by jenkins to trigger a build

**Comment by tomasbjerre** [comment]
Try invoking it with curl and check the response. It should be helpful.

**Comment by ximbal** [comment]
Ok, got it working with IMPORTANT DETAILS!!!!

Well they are rather obvious but the combination and order of factors is important to make it right:

So, first of all, you need to make sure that your HOOKS are delivering JSON, I am using github and my hook was not set to deliver JSON, I've changed that and I started having feedback on my jenkins log about the payload.

![image](https://user-images.githubusercontent.com/19576367/38033320-cb29f98c-326d-11e8-9df6-341ef99229a7.png)

This is the feedback you get on Jenkins logs:
![image](https://user-images.githubusercontent.com/19576367/38033378-ec9c1f28-326d-11e8-8241-df96d23f66a2.png)

I had to setup this parameter on my running instance of Jenkins, after I did it, things started working, I am using Jenkins 2.89
So go to the jenkins console and run this:
Set on Jenkins:
System.setProperty('hudson.model.ParametersAction.keepUndefinedParameters', 'true')

![image](https://user-images.githubusercontent.com/19576367/38033558-4e519ab8-326e-11e8-83c8-ddb316033f38.png)


Note that this will only work while this instance is running if you need to persist this parameter then you'll need to pass it on the command that launches jenkins server as -D

And this is how my Job Looks Like, basically it will IGNORE all the commits made by a user with name "Jenkins" you can adjust this depending on your payload.
![image](https://user-images.githubusercontent.com/19576367/38033687-8f38b156-326e-11e8-900a-284b32b454aa.png)

where
 `$.commits[0].committer.name` = "Jenkins" and this is how GitHub webhook deliver's the payload.

`$COMMITTER` is the variable defined in the Post content parameters section

And the most important part:

`^((?!jenkins).)*$` which is the regular expression that evaluates negatively to exclude that jenkins user

**Comment by tomasbjerre** [comment]
Great!
