### ISSUE TITLE
GitHub webhooks firing up twice and  Build is getting triggered.

### ISSUE THREAD

**Issue by ximbal** [jenkinsci/generic-webhook-trigger-plugin#53]
I have configured the Jenkins job to ignore specific commits from specific user, I am looking that github is triggering twice the same hook with the same payload, when this gets to jenkins, it gets stopped on its tracks the first time but not the second time, leading to a build.
![image](https://user-images.githubusercontent.com/19576367/38041692-68a25bf2-3280-11e8-8883-7234eec7acad.png)

![image](https://user-images.githubusercontent.com/19576367/38041720-7bdc8832-3280-11e8-85f6-6e996ba74c04.png)

Please note the timestamps for both, they happen within milliseconds.

**Comment by ximbal** [comment]
We are tagging and pushing so one call of the hook is triggered for the TAG and the second one for the push, and I was grabbing the committer's name from the wrong place since the payloads are different when you push and when you tag. To fix this issue you can grab the committers name from a different place in the payload: $.head_commit.committer.name rather than $.commits[0].committer.name

**Comment by tomasbjerre** [comment]
Great!
