### ISSUE TITLE
Ability to add multiple Optional Filters

### ISSUE THREAD

**Issue by ximbal** [jenkinsci/generic-webhook-trigger-plugin#54]
Would it be possible to add multiple optional filters so that the plugin could prevent builds for multiple scenarios? The same way we could add multiple post content parameters?

- Specific Events
- Specific users
- The combination of both, I want to prevent builds on commits made by `User X` and to prevent builds when a `Tag` event is sent
This would allow fine grain situations on when to trigger a legitimate build.

**Comment by tomasbjerre** [comment]
You can do that by creating a more complex filter string and regexp.

**Comment by ximbal** [comment]
You are right, but not everyone is a Regex Expert, would you at least consider it?

**Comment by tomasbjerre** [comment]
The plugin is very simple right now. I'd like to keep it that way. And I think this can be solved with better documentation.

Yes, you can add multiple parameters like that.

**Comment by tomasbjerre** [comment]
I added some BDD style tests. Including example with multiple variables:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github-push-event.feature

Perhaps this kind of documentation can solve this issue.

**Comment by petromir** [comment]
@tomasbjerre I hit the same issue, so you have my +1 for implementing it. The link above is not accessible.

**Comment by tomasbjerre** [comment]
Open a new issue where you describe what you are trying to do. This will not be implemented unless someone has a use case that requires it.

**Comment by sako0938** [comment]
Here is the location for the above missing link, I think: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/filter-on-multiple-variables.feature
