### ISSUE TITLE
When token used, only trigger if token supplied

### ISSUE THREAD

**Issue by tomasbjerre** [jenkinsci/generic-webhook-trigger-plugin#55]
Currently, if `token` supplied, the implementation uses that `token` to authenticate. And that will make the job visible for that request. But! The job might be visible without authentication or the invoke may use something like `http://user:pass@jenkins/` and be authenticated without the `token`...

I'm considering changing the behavior so that if a `token` is configured in the job, then the job will only trigger if that `token` is supplied. Even if the invoke has enough credentials to see the job without supplying the `token`.

**The problem** with the current implementation is that someone can accidentally trigger a lot of jobs if invoking the plugin with credentials that makes a lot of jobs visible.

**Comment by jcaxmacher** [comment]
The behavior I'm seeing is that even when the token in "Trigger builds remotely" is set, the generic webhook plugin disregards it.  The webhook triggers the job whether or not the token in the request parameter matches what has been defined.

So, I added a filter on the request parameter to match the token as well.  This prevents triggering the job, but the HTTP response from the generic webhook plugin is that triggerResults are OK for the job (even though the job has been filtered).  Maybe I'm doing something wrong.

![image](https://user-images.githubusercontent.com/638600/38441561-264c1c90-39b3-11e8-9bcd-9347f9df5a9f.png)

**Comment by tomasbjerre** [comment]
Thanks for the vote!

Sounds like your security settings is making the job visible, even without authentication.

Adding a filter like that is one of the two suggested ways of making only a specific job trigger. In the readme.

The `OK` just means it did not crash =)

**Comment by tomasbjerre** [comment]
This is released in 1.31 now. Your filter should not be needed anymore.
