### ISSUE TITLE
Boolean parameter becomes string

### ISSUE THREAD

**Issue by ximbal** [jenkinsci/generic-webhook-trigger-plugin#58]
When triggering a build using the generic webhook the parameters for the job are represented as string and not their original types, Could this be related to the actual plugin or is it a wider issue with Jenkins?

![image](https://user-images.githubusercontent.com/19576367/39721897-e7d33e2a-520e-11e8-9c8e-2f802edf1d5d.png)

VS

![image](https://user-images.githubusercontent.com/19576367/39721944-09065db6-520f-11e8-9657-8e392d064ede.png)

**Comment by tomasbjerre** [comment]
It happens here:
https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/GenericTrigger.java#L182

Should be possible to solve in the plugin.

**Comment by ximbal** [comment]
Would you consider a fix for the next released version?

**Comment by tomasbjerre** [comment]
Yes.

Making it look the same in the GUI is no problem. But is there more to it than that? Does this have any actual effect in your job than just that it looks bad in the GUI?

**Comment by ximbal** [comment]
Yeap, The jenkinsfile complains because it is expecting to find a boolean and it is getting a string, the thing is we can mitigate by casting but if we need to cast then it ain't transparent when using the plugin, do not get me wrong, you've done a hell of a job here developing it, it is just that after we updated our jenkins server to the latest LTS the use case when we use your plugin is failing with github specifically, we've tested it in bitbucket and things work as a charm, so I am unsure why this is failing, my feeling is that if you do not cast to a string things should work.

**Comment by tomasbjerre** [comment]
I just released 1.35 with a fix for this. Should be available in the update site within a few hours. Open issue again if not working!
