### ISSUE TITLE
Multiple Jenkins triggering

### ISSUE THREAD

**Issue by ddimitrioglo** [jenkinsci/generic-webhook-trigger-plugin#59]
Hi, 

We are facing the issue with multiple Jenkins triggering.
Here are the steps which we have followed to reproduce the issue:

**On local machine:**
1.  `git checkout dev`
2. `git pull origin dev` 
3. `git checkout -b debug_1`
4. Made some changes, commit and `git push origin debug_1`

Follow steps 1 - 4 once again (just change `debug_1` => `debug_2`) 

5. Create a Pull Request from `debug_2` to `dev` branch 

Expected result:
- Jenkins job is triggered from `debug_2` as a source branch and `dev` as destination. 

Actual result:
- Jenkins is triggered twice. 

**Jenkins**
We are using following configuration:

![image](https://user-images.githubusercontent.com/9005667/40113245-783aa7f6-5911-11e8-9ab4-be21ff52123d.png)
and 

![image](https://user-images.githubusercontent.com/9005667/40113327-c58bd4bc-5911-11e8-8972-296b8215ebd9.png)

**Comment by tomasbjerre** [comment]
Which version of the plugin?

**Comment by ddimitrioglo** [comment]
Oh sorry, we are using v1.32

**Comment by tomasbjerre** [comment]
Can you provide the JSON that triggers the jobs?

**Comment by ddimitrioglo** [comment]
As our project is private, could you please specify what exactly you want to see and I'll try to find and provide you.

**Comment by tomasbjerre** [comment]
It would be interesting to see what events are being consumed.

Perhaps they differ in the `action` and you only want to trigger if `$.action` resolves to `opened`.

Or are you saying that you just want to trigger for the push event?

**Comment by ddimitrioglo** [comment]
I already have an middleware where I'm filtering only 'reopened', 'opened' and 'synchronize' actions
```
if (!['reopened', 'opened', 'synchronize'].includes(requestData.action)) {
  // call <endpoint>/generic-webhook-trigger/invoke?token=<mytoken>&filter=<myfilter>
}
```
any other causes?

**Comment by tomasbjerre** [comment]
Do you have this in your pipeline?
```
     printContributedVariables: true,
     printPostContent: true
```

So that you know what those 2 consumed json webhooks looks like. The question is really what they are and how they differ. And when that is known, a filter can be created.

**Comment by tomasbjerre** [comment]
No wait... forgot you are configuring the plugin with GUI. You should have these checkboxes checked in the GUI to see the json in job build log.

**Comment by ddimitrioglo** [comment]
Checked those checkboxes, will try to reproduce and come with updates

**Comment by ddimitrioglo** [comment]
@tomasbjerre We've reproduced the issue and it looks weird...
So, we have 2 jobs triggered and this is how their logs look like:

Job A (expected):
```
Triggered by opening PR to "dev" branch
Building in workspace /var/lib/jenkins/jobs/avozicov-quality-assurance/workspace
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
GenericWebhookEnvironmentContributor
 Received:

{"action":"opened","number":6,"pull_request":.... // and here full payload
```

Job B (unexpected):
```
Started by an SCM change
Building in workspace /var/lib/jenkins/jobs/avozicov-quality-assurance/workspace
[WS-CLEANUP] Deleting project workspace...
[WS-CLEANUP] Done
Cloning the remote Git repository
Cloning repository https://github.com/<reponame>.git
 > git init /var/lib/jenkins/jobs/avozicov-quality-assurance/workspace # timeout=10
Fetching upstream changes from https://github.com/<reponame>.git
 > git --version # timeout=10
```

As we can see it wasn't triggered by `generic-webhook-trigger-plugin`, and it looks like it was triggered by `git` on top of which your plugin is working, right?

**Comment by ddimitrioglo** [comment]
Don't you relay on this plugin?

![image](https://user-images.githubusercontent.com/9005667/40168923-721eb3e6-59cd-11e8-930e-bc48688bfa98.png)

If not, can I disable it?

**Comment by tomasbjerre** [comment]
You can disable it. Unless you want to clone with that plugin.

**Comment by ddimitrioglo** [comment]
How then I will get the latest changes from github repo?

**Comment by tomasbjerre** [comment]
Resolve the information you need from the webhook. Like perhaps `$.ref ` in a variable named `ref`.

And in your pipeline/build script do a `git cone ...` and `git checkout $ref`...

**Comment by ddimitrioglo** [comment]
@tomasbjerre thank you for your time, will investigate the issue and try to find a solution.
