### ISSUE TITLE
After auth still can't trigger things

### ISSUE THREAD

**Issue by cierzniak** [jenkinsci/generic-webhook-trigger-plugin#6]
Hi,
I've a private bitbucket repo and want to connect via SSH key. Standard Bitbucket plugin is useless since it only provides auth by password (I don't want to create new Jenkins user at Bb and don't want to use my own credentials).

In both multibranch pipelines I've setted this plugin in same way:
![zrzut ekranu z 2017-05-09 13-58-22](https://cloud.githubusercontent.com/assets/815618/25849661/a826fb08-34bf-11e7-8d8f-9cdec7634c91.png)
and use webook: **http://username:api-token@jenkins.example.org:8080/generic-webhook-trigger/invoke**

but still have
````
May 09, 2017 1:59:35 PM org.jenkinsci.plugins.gwt.GenericWebHookRequestReceiver doInvoke
INFO: Did not find any jobs to trigger! The user invoking /generic-webhook-trigger/invoke must have read permission to any jobs that should be triggered.
````

Jenkins is setted to "everyone can do everything" and disallowed is to read by everyone; Jenkins SSH key is added to project, not Bb account

Tried via Bb webhooks, Postman and cUrl, still same response (no triggered tasks):
````
{
	"status": "ok",
	"data": {
		"triggerResults": {}
	}
}
````

**Comment by tomasbjerre** [comment]
There was a fix for multibranch pipelines in 1.9 is that the version you are using?

**Comment by cierzniak** [comment]
Yes, 1.9 is installed. I've installed clean Jenkins instance few days ago and added your plugin today after update repo.

**Comment by tomasbjerre** [comment]
If you browse to `/generic-webhook-trigger/invoke` with your webbrowser. While logged in with a user that you know can view the job. Does that also not work?

**Comment by tomasbjerre** [comment]
This multibranch pipeline is a bit new to me. You do want to scan the repositories within your organization? You dont want to build the repositories? Because it looks to me like you have configured it for scanning and trigger scan with this plugin.

If you want the repositories to build on, I think it should work if you add this to the Jenkinsfiles in each repo:
```
 properties([
  pipelineTriggers([
   [$class: 'GenericTrigger',
    genericVariables: [
     [expressionType: 'JSONPath', key: 'variable1', value: 'expression1'],
     [expressionType: 'JSONPath', key: 'variable2', value: 'expression2']
    ],
    regexpFilterText: '',
    regexpFilterExpression: ''
   ]
  ])
 ])
```

**Comment by tomasbjerre** [comment]
I'm releasing a fix here where I simply remove that checkbox from the multiline pipeline triggers. And I hope that what you actually want to do is to trigger the jobs, like my previous comment.

**Comment by cierzniak** [comment]
So I need to have it in Jenkinsfile, ok

But what if I want to trigger just one of repos? Did I set it properly?

````
node {

 properties([
  pipelineTriggers([
   [$class: 'GenericTrigger',
    genericVariables: [
     [expressionType: 'JSONPath', key: 'FULL_REPOSITORY_NAME', value: '$.repository.full_name'],
    ],
    regexpFilterText: "${FULL_REPOSITORY_NAME}",
    regexpFilterExpression: 'my_bitbucket_account/my_bitbucket_repo'
   ]
  ])
 ])
 ...
}
```

where `my_bitbucket_account/my_bitbucket_repo` shows properly what I want to build now

Now I setted webhook to **jenkins.com:8080/job/job-name/build** without CSRF protection as a working out-of-box solution, but I want to have more secure Jenkins instance, so will check that trigger via pipeline :)

**Comment by tomasbjerre** [comment]
The `regexpFilterText: "${FULL_REPOSITORY_NAME}",` should be without `$` `regexpFilterText: "FULL_REPOSITORY_NAME",`.

I'm not sure if it has to be like this:
```
node {
 properties([
```
Instead of
```
pipeline {
 agent any
 properties([
```

But aside from that, if you add this to the Jenkinsfile in `my_bitbucket_account/my_bitbucket_repo` that should trigger this plugin.

**Comment by cierzniak** [comment]
Ok, will check at home on my private project :) Now wil close issue and reopen if it will be trouble

Today Jenkins made update to 1.10.

Thank you for help
