### ISSUE TITLE
Specifying the authentication token in a scripted pipeline

### ISSUE THREAD

**Issue by timur-han** [jenkinsci/generic-webhook-trigger-plugin#63]
Hi,

How can we specify the authentication token in scripted pipeline?

**Comment by tomasbjerre** [comment]
When using a multibranch pipeline job?

I ususally setup an ordinary pipeline and configure a token just like I would with a freestyle project. But I'll try to supply an example with a token for multibranch as well.

**Comment by tomasbjerre** [comment]
Actuallly, this should be an issue on the [Build Token Root Plugin](https://wiki.jenkins.io/display/JENKINS/Build+Token+Root+Plugin). Here: https://issues.jenkins-ci.org/secure/Dashboard.jspa

**Comment by tomasbjerre** [comment]
I'm adding token support now in scripted pipelines. Just add the `token: 'abc123',`.

Released in 1.41.
