### ISSUE TITLE
Multiple GitHub pushes landed with the same queue ID overwriting each other parameters

### ISSUE THREAD

**Issue by gevial** [jenkinsci/generic-webhook-trigger-plugin#64]
Plugin version 1.39

We have multiple web hooks set up in GitHub. All hooks have the same structure:

```
https://user:PASSWORD@jenkins.example.com/generic-webhook-trigger/invoke?siteFQDN=www-example-com-staging.example.com&locale=/us/en
```

We use query arguments as a parameters for the job (`siteFQDN` and `locale`).

Recently we noticed that Jenkins responded with the same queue ID for two different web hooks which had different query arguments. Those hooks were fired within 30 seconds interval. As a result, instead of two job runs with different parameters we had only one run.

Expected behavior: different queue item with its own parameters for every web hook run.

In Jenkins build interface  I can see that "Generic Cause" is mentioned multiple times instead of 1, that seems to prove my assumption that multiple pushes ended up as one build.
<img width="698" alt="generic cause" src="https://user-images.githubusercontent.com/4682674/43718050-1f5357e8-9992-11e8-98e9-076f45b6066c.png">

**Comment by tomasbjerre** [comment]
This is something that I'd like to change in the plugin. But when looking at how this plugin triggers a job I cannot see any alternative that would avoid this behavior. There are 2 workarounds.

## Make the job parameterized

![sc2018-08-06 20-08-47](https://user-images.githubusercontent.com/439571/43733343-9583b76a-99b4-11e8-9d31-409c457dc7da.png)

If you check the checkbox to make the job parameterized and add parameters that have the same name as the variables you resolve with this plugin. Then each unique variation of those resolved variables will have its own item in the queue.

## Make the job execute concurrent builds

This is not as safe... I think there is a very small potential issue here if you trigger the job at the exact same millisecond.

**Comment by alfarme** [comment]
@tomasbjerre I just ran into the same problem. I tried both the workarounds, didn't seem to change anything.

I am using your plugin to parse json messages from Prometheus Alertmanager and then react to them with a triggered job. Whenever two alerts come in within a certain timespan, I get only one job triggered:

![image](https://user-images.githubusercontent.com/39736763/51237971-027b9680-1976-11e9-8c62-d9a6ba4f19af.png)

I am contributing three variables from the json POST, and I am using one of them in your 1st workaround, like in your picture above. 

I could work around this if all variables would be available, but only the first trigger contributes anything, as seen here:

![image](https://user-images.githubusercontent.com/39736763/51238319-eb897400-1976-11e9-8a57-0b184045594b.png)

 As you can see, there are no STATUS_1, JOB_1 etc.

Any help would be appreciated :)

**Comment by tomasbjerre** [comment]
Do you have the quiet period set to 0 in the job?

**Comment by tomasbjerre** [comment]
The plugin used to have 0 but with this change it now respects whatever is set in the job configuration: https://github.com/jenkinsci/generic-webhook-trigger-plugin/pull/88

**Comment by alfarme** [comment]
quiet period was set to 5, so I set it to 0.

I will report back after some more testing.

**Comment by alfarme** [comment]
> Do you have the quiet period set to 0 in the job?

@tomasbjerre that seems to have done the trick, together with the tips above.

Although I was unclear which variables I have to add in the "parameterize" part of the job, the one I chose seems to work.

Thanks you!
