### ISSUE TITLE
Can you save the entire payload to a file?

### ISSUE THREAD

**Issue by mcred** [jenkinsci/generic-webhook-trigger-plugin#66]
I'm using plugin v 1.41 and I'd like to know how to save the entire payload to a file. I see it output in the job log, but I'm not sure how to take that and save the output into a file to be parsed by some deployment scripts. Any suggestions?

**Comment by tomasbjerre** [comment]
Within a pipeline? Perhaps [writeFile](https://jenkins.io/doc/pipeline/steps/workflow-basic-steps/#writefile-write-file-to-workspace):

```
writeFile file: 'whateverfile.json', text: theVariableYouResolvedTo
```

**Comment by mcred** [comment]
What do you mean by `theVariableYouResolvedTo`? How would I reference the entire payload?

**Comment by tomasbjerre** [comment]
That variable is available if you configure the plugin with a variable named `theVariableYouResolvedTo` with JSONPath expression like `$`.

**Comment by mcred** [comment]
I follow what you're suggesting. I added the following config to my job and added the following stage:

```
        stage('checkout repo') {
            steps {
                script {
                    def scmVars = checkout scm
                    env.GIT_COMMIT = scmVars.GIT_COMMIT
                    GIT_COMMIT = scmVars.GIT_COMMIT
                    env.GIT_BRANCH = scmVars.GIT_BRANCH
                    GIT_BRANCH = scmVars.GIT_BRANCH
                }
                writeFile file: 'payload.json', text: $payload
                sh "printenv"
            }
        }
```

<img width="909" alt="screen shot 2018-08-13 at 11 47 51 am" src="https://user-images.githubusercontent.com/4326032/44042644-c357031a-9eee-11e8-8528-9bfe617b8b1c.png">


But when the job runs, it has the following error:
`groovy.lang.MissingPropertyException: No such property: $payload for class: groovy.lang.Binding`

**Comment by tomasbjerre** [comment]
change `writeFile file: 'payload.json', text: $payload` to `writeFile file: 'payload.json', text: payload`

**Comment by mcred** [comment]
That did it. Thank you for the help!
