### ISSUE TITLE
How to build merge request in scripted multibranch pipeline

### ISSUE THREAD

**Issue by peterloron** [jenkinsci/generic-webhook-trigger-plugin#67]
Hello, Tomas. First, thank you very much for your work on this plugin!

I’m working on integrating this with our multibranch pipeline jobs which pull from our local GitLab. The Jenkinsfiles are scripted. The code which is checked out and built is based on the BRANCH_NAME environment variable.

When I create a merge request between two branches (e.g. 'feature' being merged into 'development'), the build which is built is the source branch of the merge request. In this case, since we’re testing the merge would I need to add logic to the Jenkinsfile to detect that this is a MR build, checkout the target branch and do the merge manually? Or is there a feature or flag I'm missing?

Thanks!

**Comment by tomasbjerre** [comment]
You have to do the merge yourself. The plugin only parses the json in the webhook to gather whatever values you need to do that.

You may have a look at the docs here: https://wiki.jenkins.io/display/JENKINS/Violation+Comments+to+GitLab+Plugin

**Comment by peterloron** [comment]
Thanks!
