### ISSUE TITLE
How to specify the TOKEN using Job DSL?

### ISSUE THREAD

**Issue by sdiepend** [jenkinsci/generic-webhook-trigger-plugin#70]
I saw your example in the readme on how to use the job dsl to create the configure, but not how to set the token. Thanks already for the work on this plugin!

**Comment by tomasbjerre** [comment]
Should be possible by just adding `token('abc123')`. I updated the example DSL. Make sure you have latest version of the plugin as this is a new feature.

**Comment by sdiepend** [comment]
@tomasbjerre that worked! thanks!
