### ISSUE TITLE
Can only parse the first query param?

### ISSUE THREAD

**Issue by mks-d** [jenkinsci/generic-webhook-trigger-plugin#74]
Hi @tomasbjerre,

* Jenkins version: **2.129**
* Plugin version: **1.43**
* My configuration.
  * Extracting those query params
    * `param1`
    * `param2`

![image|10%](https://user-images.githubusercontent.com/12812196/44923984-36994680-ad4a-11e8-9b80-bd3751a9baae.png)

Here is what happens:

```bash
$ curl -v http://localhost:8080/generic-webhook-trigger/invoke?param1=value1&param2=value2

{"status":"ok","data":{"triggerResults":{"test-webhook":{"id":96,"regexpFilterExpression":"","regexpFilterText":"","resolvedVariables":{"param1":"value1","param1_0":"value1"},"triggered":true,"url":"queue/item/96/"}}}}
```
The above response already suggests that there is nothing about `param2`, and indeed, it's nowhere to be found.

This means that when using a token parameter, there is no way to parse even one single further parameter.

Is this a known issue, or am I missing something?

**Comment by tomasbjerre** [comment]
Very strange. I can reproduce it myself. Will continue investigation...

**Comment by tomasbjerre** [comment]
I asked in the Jenkins Developer mailing list here: https://groups.google.com/forum/#!topic/jenkinsci-dev/Z8QauBNepxU

As Daniel says. It has to be: `curl -v 'http://localhost:8080/generic-webhook-trigger/invoke?param1=value1&param2=value2'`

**Comment by mks-d** [comment]
Correct, thank you for asking around!
