### ISSUE TITLE
[Question] How to access the contributed variables in groovy script?

### ISSUE THREAD

**Issue by arshakanjum** [jenkinsci/generic-webhook-trigger-plugin#75]
I am receiving a JSON and setting a variable modified with expression ".commits" and the log shows contributed variables as expected. How do i access this in a build groovy script?

**Comment by tomasbjerre** [comment]
You access the variable by using its name.

If you see in the log:
```
Contributing variables:

    someVariableHere = a b c
```

You can have a pipeline like:
```
node {
 println "The value is: $someVariableHere"
}
```

**Comment by arshakanjum** [comment]
When I try to do that I get "No such property: someVariableHere for class: Script1

**Comment by arshakanjum** [comment]
I am a pretty beginner to jenkins, so bear me. I am trying to use this to trigger a job when a commit happens to github. I am getting the post from github hook and am setting it to a variable modified (in generic-webhook-trigger). I want to access that variable in a system groovy script (Build Job)
Could you provide an example groovy script that can print this variable to console?
