### ISSUE TITLE
Cannot access variable from groovy which is a JSON Array

### ISSUE THREAD

**Issue by arshakanjum** [jenkinsci/generic-webhook-trigger-plugin#76]
After setting a variable to a JSON array in generic-webhook-trigger, 
console output: 
```
Contributing Variables
 modified = ["sac_tests/lang/dontcall.properties"]
```
it cannot be accessed in groovy with 

`mod = build.getEnvironment(listener).get('modified')`

mod is an empty string after this

**Comment by tomasbjerre** [comment]
I gave you a complete example in https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/75

This is not a Jenkins support forum. You can ask that kind of general questions on Stackoverflow.
