### ISSUE TITLE
Auth/security: can the GWT end point be reached without authenticating?

### ISSUE THREAD

**Issue by mks-d** [jenkinsci/generic-webhook-trigger-plugin#77]
Hi @tomasbjerre ,

I am a little confused, I have tried three different restrictive security profiles in Jenkins:
1. Logged-in users can do anything (and anonymous **without** read access)
2. Matrix-based security (and nobody granted anything)
3. Project-based Matrix Authorization Strategy (and nobody granted anything)

And in all those cases the generic endpoint did return its usual response, whereas I was expecting something along the lines of a 403 (Forbidden) status code.

More details:
* Jenkins version: **2.141**
* Plugin version: **1.43**
* A `curl` command and its response:
```
curl -v -H "Content-Type: application/json" http://localhost:8080/generic-webhook-trigger/invoke
```
Of course this can also be observed using -say- Chrome in incognito.

This leads me to my _actual_ question anyway, is it possible to enable a project-based matrix security for those jobs that are triggered by GWT?

**Comment by tomasbjerre** [comment]
> And in all those cases the generic endpoint did return its usual response, whereas I was expecting something along the lines of a 403 (Forbidden) status code.

You are saying you can invoke the plugin and have jobs triggered. But you want to restrict that?

**Comment by mks-d** [comment]
What I really want in the end is to trigger the end point with basic auth. So providing the user/pass for a user whose credentials allow to trigger the webhook job.

But in the meantime I realised that the jobs could be triggered despite the security chosen and set globally in Jenkins. When disallowing for instance non-logged in users to do anything, I would not expect the GWT to be authorised anyway. I would expect the GWT to be subordinated to the security preferences that are set globally in Jenkins.

**Comment by tomasbjerre** [comment]
Ok. My idea is that users will always want to use the `token` feature. They will always want to have a unique `token` for each job so that they can invoke that, and only that, job.

The current implementation will use impersonation (`SYSTEM`) to find all jobs and trigger any jobs that have a matching `token`. A `token` matches if the job has the same or if no `token` was supplied and also the job has no `token` configured.

But I am not sure if this is the behavior most users want. Perhaps, when no `token` is supplied, impersonation should not be used at all.

**Comment by tomasbjerre** [comment]
Actually, I'm changing this so that when no `token` supplied the plugin will not impersonate.

It feels safer. And I think most users are using the `token` anyway.

Releasing it now as 1.44.

**Comment by tomasbjerre** [comment]
I'm closing this one. Open it again if anything is unclear.

**Comment by mks-d** [comment]
Perhaps this design of finding + triggering jobs through `SYSTEM` is an overreach, as it seems that `SYSTEM` is not subject to the global security settings? I'm not familiar enough with Jenkins' inside architecture to suggest an alternative. But the end result seems to create some sort of security loophole (without token), as I described in my first post.

We would be satisfied with the token if it could be set through an API endpoint. We rely on a secret management platform that will feed Jenkins with its secrets _after_ its been launched the first time. And the token is bugging us because it can be set like that.
Alternatively the token could be set through the credentials maybe? Those at least could be created/set through HTTP endpoints.

**Comment by tomasbjerre** [comment]
The impersonation was originally introduced with a pull request in this commit: https://github.com/jenkinsci/generic-webhook-trigger-plugin/commit/8a98d57c06952faba4a0e72b7f3013939c89b5ca

I'm assuming `SYSTEM` is correct. Have not had any issues reported regarding that.

The token can definitely be set through credentials. I'll have a look at that!

I don't know if Job DSL can help you in your case? You can contribute credentials as environment variables when a Job DSL script is running.

**Comment by tomasbjerre** [comment]
I had a look at the credentials docs. And it is a terrible API. I would like to keep it out of this plugin to avoid adding complexity.

And as I said. If you are using Job DSL you can just inject credentials when processing job DSL.

If you are using multibranch pipeline, you can inject credentials like this:
```

node {

withCredentials([string(credentialsId: 'mycredentialsid', variable: 'credentialsVariable')]) {
 properties([
  pipelineTriggers([
   [$class: 'GenericTrigger',
    genericVariables: [
     [key: 'reference', value: '$.ref'],
     [
      key: 'before',
      value: '$.before',
      expressionType: 'JSONPath', //Optional, defaults to JSONPath
      regexpFilter: '', //Optional, defaults to empty string
      defaultValue: '' //Optional, defaults to empty string
     ]
    ],
    genericRequestVariables: [
     [key: 'requestWithNumber', regexpFilter: '[^0-9]'],
     [key: 'requestWithString', regexpFilter: '']
    ],
    genericHeaderVariables: [
     [key: 'headerWithNumber', regexpFilter: '[^0-9]'],
     [key: 'headerWithString', regexpFilter: ''],
     [key: 'X-GitHub-Event', regexpFilter: '']
    ],
    token: credentialsVariable,
    printContributedVariables: true,
    printPostContent: true,
    regexpFilterText: '',
    regexpFilterExpression: ''
   ]
  ])
 ])
}


 stage("build") {
  sh '''
  echo Variables from shell:
  echo reference $reference
  echo before $before
  echo requestWithNumber $requestWithNumber
  echo requestWithString $requestWithString
  echo headerWithNumber $headerWithNumber
  echo headerWithString $headerWithString
  echo X_GitHub_Event $X_GitHub_Event
  '''
 }
}
```

**Comment by mks-d** [comment]
@tomasbjerre I think we can make it work with 1.44 and the project-based matrix authorization strategy.

So:
* No token, but
* The webhook job would require a certain user to be logged in.

**Comment by tomasbjerre** [comment]
Great!
