### ISSUE TITLE
Working Webhook is now returning "Did not find any jobs to trigger"

### ISSUE THREAD

**Issue by lcofre** [jenkinsci/generic-webhook-trigger-plugin#78]
I had a successful pipeline where the Bitbucket webhook is now returning
```javascript
{
  "status": "ok",
  "data": {
    "triggerResults": {
      "ANY": "Did not find any jobs to trigger! If the job you intend to trigger has a configured token, you need to pass it like ...trigger/invoke?token=TOKENHERE"
    }
  }
}
```
I updated this plugin along with others in Jenkins.

The pipeline is triggered only by this plugin in the Build Triggers section. I configured it to only trigger when there's a push to the develop branch:
```
Post content parameters
Variable: branch
Expression: $.push.changes[0].new.links.self.href
JSONPath
Text: $branch
Optional filter
Expression: ^.*(repositories/MY_COMPANY/MY_REPO/refs/branches/develop).*$

(All other properties were left as default. Only changed the company and repo names)
```

Bitbucket webhook sends this body in the request (I only kept the href property as the body has many other properties. I also changed the company and repo names):
```
{
   "push":{
      "changes":[
         {
            "new":{
               "links":{
                  "self":{
                     "href":"https://api.bitbucket.org/2.0/repositories/MY_COMPANY/MY_REPO/refs/branches/develop"
                  }
               }
            }
         }
      ]
   }
}
```

Thank you very much in advance for your help.

Environment info
 * Generic Webhook Trigger Plugin: 1.44
 * Jenkins ver. 2.121.3 (Windows, jre 64bit)
```

**Comment by lcofre** [comment]
Hi Tomas,

Thanks very much for your quick response.

When I downgrade the plugin to 1.43 and resend the post from bitbucket the pipeline is triggered. The response I get with 1.43 is:
```json
{
  "status": "ok",
  "data": {
    "triggerResults": {
      "MY_REPO develop": {
        "id": 159,
        "regexpFilterExpression": "^.*(repositories/MY_COMPANY/MY_REPO/refs/branches/develop).*$",
        "regexpFilterText": "https://api.bitbucket.org/2.0/repositories/MY_COMPANY/MY_REPO/refs/branches/develop",
        "resolvedVariables": {
          "branch": "https://api.bitbucket.org/2.0/repositories/MY_COMPANY/MY_REPO/refs/branches/develop"
        },
        "triggered": true,
        "url": "queue/item/159/"
      }
    }
  }
}
```
I didn't configure the webhook with a token, but I can do it if is needed.

Thanks very much again for your help.

**Comment by tomasbjerre** [comment]
Yes. This was the change in that version.

Den tis 11 sep. 2018 21:40Leandro Cofre <notifications@github.com> skrev:

**Comment by lcofre** [comment]
Great! I added a token and now it's working.

Under the token field still says "Optional token". Should now say that is required if there is no "security enabled"?

Thanks very much for your help.

**Comment by tomasbjerre** [comment]
I changed the response from the plugin. It should be clearer that one needs to use a token or provide credentials.

For the record, the change was made because of: https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/77

**Comment by lcofre** [comment]
That's grand! Is good to know the reasons for the change, thanks for all your work and for your quick response.
