### ISSUE TITLE
repo:push bitbucket JSON parcing for option to trigger

### ISSUE THREAD

**Issue by shadowXVll** [jenkinsci/generic-webhook-trigger-plugin#79]
Hi, have and issue i used plugin for webhook bitbucket, when dev's commit some change to the branch.  I've manage to trigger jenkins job with simple extensions thru curl like
 "curl -d '{"name":"development"}' -H "Content-Type: application/json" -X POST https://JENK_URL/jenkins/generic-webhook-trigger/invoke?token=usk7PLJQHYkhK66gtvu6pXvpQ0h1DU8D"

but when i try some extension with key more difficult then ($.name), in example $.push.changes.0.old.name from BitBucket repo:push JSON, i found a problem that my Variable isn't get any value from JSON. Could you please assist me with some advice. Thank you in advance

**Comment by tomasbjerre** [comment]
Does it work in this site? http://jsonpath.herokuapp.com/

I suspect you want expression like: `$.push.changes[0].old.name `

**Comment by shadowXVll** [comment]
@tomasbjerre Thanks it work:) problem was that i checked in https://jsonpath.curiousconcept.com/ and this expression $.push.changes.0.old.name show there 'development'.
