### ISSUE TITLE
Cannot find the token

### ISSUE THREAD

**Issue by jnazander** [jenkinsci/generic-webhook-trigger-plugin#81]
* Plugin version used. - 1.45
 * Jenkins version used. - 2.138.1

I just installed this plugin to be able to trigger jobs remotely. I've given one job a token as required:

![image](https://user-images.githubusercontent.com/4726607/46288953-36ca7300-c590-11e8-94b4-1c99839c71e8.png)

And tried to trigger the job using the curl request:

`curl -X POST -v -H jenkins.builder:*** https://jenkins.***.net/generic-webhook-trigger/invoke?token=accounts`

But the response was:

`{"status":"ok","data":{"triggerResults":{"ANY":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@jenkins/generic-webhook... "}}}`

It seems that it doesn't find the token in the query string. I've also tried to pass the token in header, using `-H "token: accounts"`, but it still doesn't seem to find it. Is this a bug?

**Comment by tomasbjerre** [comment]
Looks like correct usage.

If you also add username/password to the URL, does that work? It should not be required but interesting test

**Comment by jnazander** [comment]
I've tried it.... still same error.

Request:
`curl -X POST -v -H "token: accounts" https://jenkins.builder:***@jenkins.***.net/generic-webhook-trigger/invoke?token=accounts`
Response:
`{"status":"ok","data":{"triggerResults":{"ANY":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@jenkins/generic-webhook... "}}}`

If I remove authentication entirely, I _still_ get the same error. Is that normal?

**Comment by tomasbjerre** [comment]
With authentication and without token would be an interesting test also.

Yes if you remove both user credentials and token, then the message is normal.

**Comment by jnazander** [comment]
With authentication and without token gives the same error:

`curl -X POST -v -u jenkins.builder:*** https://jenkins.***.net/generic-webhook-trigger/invoke`

returns

`{"status":"ok","data":{"triggerResults":{"ANY":"Did not find any jobs with GenericTrigger configured! If you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE. If you are not using a token, you need to authenticate like http://user:passsword@jenkins/generic-webhook... "}}}`

**Comment by tomasbjerre** [comment]
Did you configure a job without a token when you did that test?

**Comment by tomasbjerre** [comment]
What kind of job did you configure with the plugin? Freestyle, Pipeline, Multipipeline?

Do you have any other trigger-plugin working?

If you try to create a simple parameterized freestyle project, without this plugin but with a token configured. Can you trigger that using that token?

**Comment by jnazander** [comment]
>Did you configure a job without a token when you did that test?

No

>What kind of job did you configure with the plugin?

Just a normal freestyle job

>Do you have any other trigger-plugin working?

Not as far as I remember

>If you try to create a simple parameterized freestyle project, without this plugin but with a token configured. Can you trigger that using that token?

I've tried that, created a simple freestyle project, checked "Trigger builds remotely (e.g., from scripts)", added a token, called it via `/build?token=mytoken` and `/buildWithParameters?token=myToken` (without authorization), and it returned `403 Authentication required`...

So I guess it's not related to your plugin after all... My bad. It's probably Jenkins itself, or something is up with our network rules.
I will close this ticket now.

**Comment by tomasbjerre** [comment]
Releasing 1.47 now with a fix. So that the plugin will print information when no jobs were found and not be silent.
