### ISSUE TITLE
The plugin stopped accepting unlogged requests after update

### ISSUE THREAD

**Issue by danieleratti** [jenkinsci/generic-webhook-trigger-plugin#84]
This plugin worked fine until yesterday when I updated both the plugins and Jenkins core.
Now, when I send a request without any cookie (as an unlogged user) the page /generic-webhook-trigger/invoke reply with an empty body and doesn't work.

Are there any settings to skip this check or is it a bug?

**Comment by tomasbjerre** [comment]
https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/78

**Comment by tomasbjerre** [comment]
This could also be https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/81 but i dont know what the problem was there.

**Comment by tomasbjerre** [comment]
@danieleratti Did you solve it? Can this be closed?

**Comment by tomasbjerre** [comment]
no response, closing.

**Comment by tomasbjerre** [comment]
Releasing 1.47 now with a fix. So that the plugin will print information when no jobs were found and not be silent.
