### ISSUE TITLE
cannot filter based on changed_files and ref

### ISSUE THREAD

**Issue by sbusetty-rythmos** [jenkinsci/generic-webhook-trigger-plugin#85]
Plugin version used in  1.43

variable: changed_files Expression: $.commits[*]. 
['modified','added','removed'][*]

variable: ref Expression: $.ref

In option filter i have this

text: $changed_files $ref
Expression:  localDev/gateway/[^"]+? refs/heads/testing_generic

The builds are not getting triggered. I am comitting to testing_generic branch.

If i remove branch from expression, the builds are getting triggered irrespective of branch.

**Comment by tomasbjerre** [comment]
Perhaps change `localDev/gateway/[^"]+?` to `"localDev/gateway/[^"]+?"``

Also this `$.commits[].['modified','added','removed'][]` may need to change to `$.commits[].['modified','added','removed'][*]`

**Comment by tomasbjerre** [comment]
I would need the received JSON in order to investigate this. 

There is an option to print post content in the build log.

**Comment by sbusetty-rythmos** [comment]
The JSON in the build log

{"ref":"refs/heads/testing_generic","before":"ae109a6a349e28faa316b921d648a7b68cae213b","after":"1da7e888221d97caffd807f1dcb7663990f34d2a","created":false,"deleted":false,"forced":false,"base_ref":null,"compare":"https://github.com/testcomp/amcdevops/compare/ae109a6a349e...1da7e888221d","commits":[{"id":"1da7e888221d97caffd807f1dcb7663990f34d2a","tree_id":"aed3b139af8d26a0dbc56e0085acad236e531b3c","distinct":true,"message":"testing generic 35","timestamp":"2018-10-15T20:03:44+05:30","url":"https://github.com/testcomp/amcdevops/commit/1da7e888221d97caffd807f1dcb7663990f34d2a","author":{"name":"Shankar Busetty","email":"sbusetty@rythmos.com","username":"sbusetty-rythmos"},"committer":{"name":"Shankar Busetty","email":"sbusetty@rythmos.com","username":"sbusetty-rythmos"},"added":[],"removed":[],"modified":["localDev/gateway/a"]}],"head_commit":{"id":"1da7e888221d97caffd807f1dcb7663990f34d2a","tree_id":"aed3b139af8d26a0dbc56e0085acad236e531b3c","distinct":true,"message":"testing generic 35","timestamp":"2018-10-15T20:03:44+05:30","url":"https://github.com/testcomp/amcdevops/commit/1da7e888221d97caffd807f1dcb7663990f34d2a","author":{"name":"Shankar Busetty","email":"sbusetty@rythmos.com","username":"sbusetty-rythmos"},"committer":{"name":"Shankar Busetty","email":"sbusetty@rythmos.com","username":"sbusetty-rythmos"},"added":[],"removed":[],"modified":["localDev/gateway/a"]},"repository":{"id":97985129,"node_id":"MDEwOlJlcG9zaXRvcnk5Nzk4NTEyOQ==","name":"amcdevops","full_name":"testcomp/amcdevops","private":true,"owner":{"name":"testcomp","email":"github-testcomp@loyal.com","login":"testcomp","id":22598057,"node_id":"MDQ6VXNlcjIyNTk4MDU3","avatar_url":"https://avatars3.githubusercontent.com/u/22598057?v=4","gravatar_id":"","url":"https://api.github.com/users/testcomp","html_url":"https://github.com/testcomp","followers_url":"https://api.github.com/users/testcomp/followers","following_url":"https://api.github.com/users/testcomp/following{/other_user}","gists_url":"https://api.github.com/users/testcomp/gists{/gist_id}","starred_url":"https://api.github.com/users/testcomp/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/testcomp/subscriptions","organizations_url":"https://api.github.com/users/testcomp/orgs","repos_url":"https://api.github.com/users/testcomp/repos","events_url":"https://api.github.com/users/testcomp/events{/privacy}","received_events_url":"https://api.github.com/users/testcomp/received_events","type":"User","site_admin":false},"html_url":"https://github.com/testcomp/amcdevops","description":"This covers all RCX devops CI/CD pipelines, deployment, AWS management scripts, etc.","fork":false,"url":"https://github.com/testcomp/amcdevops","forks_url":"https://api.github.com/repos/testcomp/amcdevops/forks","keys_url":"https://api.github.com/repos/testcomp/amcdevops/keys{/key_id}","collaborators_url":"https://api.github.com/repos/testcomp/amcdevops/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/testcomp/amcdevops/teams","hooks_url":"https://api.github.com/repos/testcomp/amcdevops/hooks","issue_events_url":"https://api.github.com/repos/testcomp/amcdevops/issues/events{/number}","events_url":"https://api.github.com/repos/testcomp/amcdevops/events","assignees_url":"https://api.github.com/repos/testcomp/amcdevops/assignees{/user}","branches_url":"https://api.github.com/repos/testcomp/amcdevops/branches{/branch}","tags_url":"https://api.github.com/repos/testcomp/amcdevops/tags","blobs_url":"https://api.github.com/repos/testcomp/amcdevops/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/testcomp/amcdevops/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/testcomp/amcdevops/git/refs{/sha}","trees_url":"https://api.github.com/repos/testcomp/amcdevops/git/trees{/sha}","statuses_url":"https://api.github.com/repos/testcomp/amcdevops/statuses/{sha}","languages_url":"https://api.github.com/repos/testcomp/amcdevops/languages","stargazers_url":"https://api.github.com/repos/testcomp/amcdevops/stargazers","contributors_url":"https://api.github.com/repos/testcomp/amcdevops/contributors","subscribers_url":"https://api.github.com/repos/testcomp/amcdevops/subscribers","subscription_url":"https://api.github.com/repos/testcomp/amcdevops/subscription","commits_url":"https://api.github.com/repos/testcomp/amcdevops/commits{/sha}","git_commits_url":"https://api.github.com/repos/testcomp/amcdevops/git/commits{/sha}","comments_url":"https://api.github.com/repos/testcomp/amcdevops/comments{/number}","issue_comment_url":"https://api.github.com/repos/testcomp/amcdevops/issues/comments{/number}","contents_url":"https://api.github.com/repos/testcomp/amcdevops/contents/{+path}","compare_url":"https://api.github.com/repos/testcomp/amcdevops/compare/{base}...{head}","merges_url":"https://api.github.com/repos/testcomp/amcdevops/merges","archive_url":"https://api.github.com/repos/testcomp/amcdevops/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/testcomp/amcdevops/downloads","issues_url":"https://api.github.com/repos/testcomp/amcdevops/issues{/number}","pulls_url":"https://api.github.com/repos/testcomp/amcdevops/pulls{/number}","milestones_url":"https://api.github.com/repos/testcomp/amcdevops/milestones{/number}","notifications_url":"https://api.github.com/repos/testcomp/amcdevops/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/testcomp/amcdevops/labels{/name}","releases_url":"https://api.github.com/repos/testcomp/amcdevops/releases{/id}","deployments_url":"https://api.github.com/repos/testcomp/amcdevops/deployments","created_at":1500669843,"updated_at":"2018-10-11T07:16:25Z","pushed_at":1539614036,"git_url":"git://github.com/testcomp/amcdevops.git","ssh_url":"git@github.com:testcomp/amcdevops.git","clone_url":"https://github.com/testcomp/amcdevops.git","svn_url":"https://github.com/testcomp/amcdevops","homepage":"","size":4690,"stargazers_count":1,"watchers_count":1,"language":"Shell","has_issues":true,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":false,"forks_count":0,"mirror_url":null,"archived":false,"open_issues_count":14,"license":null,"forks":0,"open_issues":14,"watchers":1,"default_branch":"develop","stargazers":1,"master_branch":"develop"},"pusher":{"name":"sbusetty-rythmos","email":"41578281+sbusetty-rythmos@users.noreply.github.com"},"sender":{"login":"sbusetty-rythmos","id":41578281,"node_id":"MDQ6VXNlcjQxNTc4Mjgx","avatar_url":"https://avatars3.githubusercontent.com/u/41578281?v=4","gravatar_id":"","url":"https://api.github.com/users/sbusetty-rythmos","html_url":"https://github.com/sbusetty-rythmos","followers_url":"https://api.github.com/users/sbusetty-rythmos/followers","following_url":"https://api.github.com/users/sbusetty-rythmos/following{/other_user}","gists_url":"https://api.github.com/users/sbusetty-rythmos/gists{/gist_id}","starred_url":"https://api.github.com/users/sbusetty-rythmos/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/sbusetty-rythmos/subscriptions","organizations_url":"https://api.github.com/users/sbusetty-rythmos/orgs","repos_url":"https://api.github.com/users/sbusetty-rythmos/repos","events_url":"https://api.github.com/users/sbusetty-rythmos/events{/privacy}","received_events_url":"https://api.github.com/users/sbusetty-rythmos/received_events","type":"User","site_admin":false}}


Contributing variables:

    changed_files = ["localDev/gateway/a"]
    changed_files_0 = localDev/gateway/a
    ref = refs/heads/testing_generic

**Comment by tomasbjerre** [comment]
I added a test case to show this feature: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github/github-push-trigger-when-specific-file-changes-to-branch.feature

Variable `changed_files` set to `$.commits[*].['modified','added','removed'][*]``
Variable `ref` set to `$.ref`

Filter text as `$ref $changed_files` and expression as `refs/heads/testing_generic .*"localDev/gateway/[^"]+?".*`

**Comment by sbusetty-rythmos** [comment]
this works fine.
