### ISSUE TITLE
Webhook changes job config, loses token

### ISSUE THREAD

**Issue by asc-adean** [jenkinsci/generic-webhook-trigger-plugin#86]
When reporting a bug, please **try** to provide as much information as possible.

 * Plugin version used
1.46
 * Jenkins version used.
2.147
 * Your configuration.
Simple Pipeline:

```
node('k8s') {
    properties([
	  pipelineTriggers([
	   [$class: 'GenericTrigger',
		genericVariables: [
		 [key: 'reference', value: '$.ref'],
		 [
		  key: 'number',
		  value: '$.number',
		  expressionType: 'JSONPath', //Optional, defaults to JSONPath
		  regexpFilter: '', //Optional, defaults to empty string
		  defaultValue: '' //Optional, defaults to empty string
		 ]
		],
		printContributedVariables: true,
		printPostContent: true,
		regexpFilterText: '',
		regexpFilterExpression: ''
	   ]
	  ])
	 ])
    
    checkout([
	  $class: 'GitSCM', 	  
	  userRemoteConfigs: [
		  [
			  url: 'git@github.com:projname/project.git', 
			  credentialsId: '0efef577-d3f0-4ff4-80fa-5a14f1837223',
			  name: 'origin',
			  refspec: '+refs/pull/$number/*:refs/remotes/origin/pr/$number/*'
		  ]
	  ],
	  branches: [[ name: "*/**" ]]
	])
	
    stage('Build'){
        container('android-build') {
            sh './gradlew assembleDebug'
        }
    }
}

```

* Config:
I have set a Token to trigger this build
* Problem:
Once triggered, the webhook CHANGES MY JOB CONFIGURATION and removes the token, effectively making the job work ONCE and only ONCE until I go back into the config and re-paste the token, then rinse and repeat.  Why is my config being changed?

Here's to show the difference in my config:

> cp config.xml goodconfig.xml

I trigger the webhook, then check the diff:

diff config.xml goodconfig.xml
```
26a27
>               <expressionType>JSONPath</expressionType>
28a30,31
>               <regexpFilter></regexpFilter>
>               <defaultValue></defaultValue>
40c43
<           <printPostContent>true</printPostContent>
---
>           <printPostContent>false</printPostContent>
41a45,46
>           <causeString>PR Trigger</causeString>
>           <token>kJhBlvuu87jDriR43AVNHamh</token>
```

**Comment by tomasbjerre** [comment]
The `token` has to be in the pipeline script or it will not stick. Any property that is not defined in the pipeline will be removed. Not something implemented in this plugin, this is just how pipelines work.

```
    properties([
	  pipelineTriggers([
	   [$class: 'GenericTrigger',
		...
                token
                ...
	   ]
	  ])
	 ])
```

**Comment by asc-adean** [comment]
@tomasbjerre Thank you for the reply, that makes sense.  I am new to pipeline usage and this is helpful.

I am experiencing a problem with this though -- if I paste the Token in the input field and hit Apply or Save, then the build works once (posting payload with Postman) but adding the ```token: 'abc123'``` does not trigger the build with the same payload.

The difference in Postman is that if the token is in the input box, I get a 200OK with content and the build runs fine:
```
{
    "status": "ok",
    "data": {
        "triggerResults": {
            "projname/project": {
                "id": 618,
                "regexpFilterExpression": "",
                "regexpFilterText": "",
                "resolvedVariables": {
                    "number": "1"
                },
                "triggered": true,
                "url": "queue/item/618/"
            }
        }
    }
}
```

but when I have the token in the pipeline, I get a 200 OK with no return content and the build does not run.  Am I doing this correctly?

**Comment by asc-adean** [comment]
Strike my previous comment, if I have the token in the input box AND in the pipeline, it sticks and builds work.

Thanks 👍
