### ISSUE TITLE
Enable triggering multibranch pipeline scan

### ISSUE THREAD

**Issue by andreasgalek** [jenkinsci/generic-webhook-trigger-plugin#89]
The plugin can't be used in Jenkins GUI when attempting to set the trigger for build jobs of type 'Multibranch Pipeline'.

Extend the GUI for
- build job type: Multibranch Pipeline
- section: Scan Multibranch Pipeline Triggers
and insert the option 'Generic Webhook Trigger' there.
![image](https://user-images.githubusercontent.com/6794296/48614222-07c85f00-e98e-11e8-95a7-c5b574196452.png)

My Jenkins reference installation used when writing this issue:
 * Plugin version used: 1.48
 * Jenkins version used: 2.138.3

**Comment by tomasbjerre** [comment]
Would be a nice feature.

I'm having trouble finding docs on how to do it for Multibranch Pipeline. The plugins that have this feature seems to just return `true` here: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/GenericTrigger.java#L44

Also this plugin did show up there in early versions. But was removed because it was not really supported: https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/6

**Comment by andreasgalek** [comment]
Hi Tomas,

that’s a pity you removed it.
It would be great to have the option in multibranch pipeline jobs again. The kind of jobs is very powerful and we usually use it for building of all changed branches of a project.

Thanks and Regards,
Andreas Galek

**Comment by tomasbjerre** [comment]
You just want to trigger a scan right? No need to extract variables? And
filtering based on a regexp is just nice to have right?

Perhaps it is easier to extend the multibranch plugin with ability to
trigger a scan from a URL invocation.

Den fre 16 nov. 2018 kl 11:16 skrev andreasgalek <notifications@github.com>:

**Comment by andreasgalek** [comment]
Hi Tomas,

that’s right.
Assuming I have a Git repository in Bitbucket with a webhook like:
https://my-jenkins-server.com/generic-webhook-trigger/invoke/?token=test-token-2
that is called every time a commit is done to a branch in the repository.

Then, on the Jenkins side, the corresponding Multibranch Pipeline build job, with defined “Generic Webhook Trigger” / “Token = test-token-2”, should be executed which, in case of this kind of job, means executing the action “Scan Multibranch Pipeline Now”.

If your plugin would allow for it then it would be a perfect solution!


Thanks and Regards,
Andreas Galek

**Comment by tomasbjerre** [comment]
You should open an issue in that plugin to get such a feature implemented.
I think they want a Jira created:
https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Multibranch+Plugin

Den fre 16 nov. 2018 15:01 skrev andreasgalek <notifications@github.com>:

**Comment by tomasbjerre** [comment]
To clearify. This plugin can trigger "jobs". The multibranch can create
jobs and does so by scanning jenkinsfiles.

If you want to trigger the actual scanning, then that is a feature to
implement in the [Pipeline Multibranch Plugin](
https://wiki.jenkins-ci.org/display/JENKINS/Pipeline+Multibranch+Plugin).

If you want to trigger the jobs created by scanning, then you can use this
plugin and configure it in the Jenkinsfile as described in the readme.

Den fre 16 nov. 2018 kl 15:19 skrev Tomas Bjerre <tomas.bjerre85@gmail.com>:

**Comment by andreasgalek** [comment]
How can the Multibranch Pipeline Plugin know anything about “Generic Webhook Trigger”? Therefore I’m afraid the change can’t be done there.
For my understanding the “Generic Webhook Trigger” Plugin should embed the corresponding option box into the configuration page of a Multibranch Pipeline build job, shouldn’t it?

Thanks and Regards,
Andreas Galek

**Comment by tomasbjerre** [comment]
They dont need anything from this plugin in order to implement that feature.

Den fre 16 nov. 2018 15:37 skrev andreasgalek <notifications@github.com>:

**Comment by igalg** [comment]
I had the same problem.
decided to solve this issue
https://github.com/jenkinsci/multibranch-scan-webhook-trigger-plugin

**Comment by AmarettoSlim** [comment]
> I had the same problem.
> decided to solve this issue
> https://github.com/jenkinsci/multibranch-scan-webhook-trigger-plugin

@igalg 
Any chance you can add functionality to run a "Build Now" when a pr:open or pr:merged web hook payload comes in for a branch?

Right now the multi-branch scan will invoke when the payload is sent, but it quickly sees there are no changes to the branch (since you push to origin, which initiates a scan, and then open a pr, which initiates a scan but the commit hasn't changed since the previous push so nothing is built).

Asking here because I can't seem to open an issue on the repo itself.

Thanks!

**Comment by igalg** [comment]
Hi. 
It’s look like what you are trying to do supported with generic Webhook plugin. 
You can create a Webhook for pr:open and pr:merged events. 

In the multibranch pipeline you should select suppress scm triggering  

Look in the generic Webhook plugin documentation how to configure multibranch pipeline. 

Let me know if it’s solve your problem.
