### ISSUE TITLE
Enhancement: allow request headers to be set as variables too

### ISSUE THREAD

**Issue by juanpablo-santos** [jenkinsci/generic-webhook-trigger-plugin#9]
it would be useful to also set variables from request headers, f.ex., 
* Gogs' webhooks are capable of sending a custom header, `secret`, which can be used at jenkins' side to see if the request cames from that webhook (is legit), or not
* also Gogs' webhooks send the event that triggered the webhook on a request header. Different events produce different payloads

On the UI side, as headers and request parameters would be treated essentially the same, maybe the current request parameter variable field could be reused? that is, if the variable isn't found as a request parameter, then look for it on the request headers? Or maybe is better to clearly separate one from another?

**Comment by tomasbjerre** [comment]
I think I would prefer it to be separated.

**Comment by tomasbjerre** [comment]
I released this in 1.12 now. Open issue again if any problems!

**Comment by juanpablo-santos** [comment]
that was pretty fast, thank you!
