### ISSUE TITLE
Jenkins doesn't catch webhook

### ISSUE THREAD

**Issue by mrtnvrga** [jenkinsci/generic-webhook-trigger-plugin#90]
Plugin version: 1.48
Jenkins version: 2.89.4

After we restructured our Pipeline as Multibranch, we can't get past this issue:

```
pipeline {
    agent none
    environment {
        COMPLIANCEENABLED = true
        NAME = "some-project"
    }
    triggers{
        GenericTrigger(
            genericVariables: [
                [expressionType: 'JSONPath', key: 'ref', value: '$.ref'],
                [expressionType: 'JSONPath', key: 'before', value: '$.before']
            ],
            causeString: 'Triggered on $ref',
            token: 'abc123',
            printContributedVariables: true,
            printPostContent: true,
            silentResponse: false,
            regexpFilterText: '$ref',
            regexpFilterExpression: 'refs/heads/' + BRANCH_NAME
        )
    }
stage('Build'){
   echo "$ref"
}
```

When the webhook in GitHub is triggered (https://JENKINSLINK/generic-webhook-trigger/invoke, with application/json setting + a valid Secret (GitHub shows the webhooks is OK, and we can trigger it with curl correctly too), I get this error message: 
_No such property: ref for class: groovy.lang.Binding_

I checked similiar issues about this, tried all of them, but none worked. I checked the full log, but I couldn't find ContributedVariables or PostContent printed anywhere. I suspect my Jenkins job doesn't catch the webhook we send. Any ideas how to proceed?

**Comment by tomasbjerre** [comment]
What post content do you trigger with?

**Comment by tomasbjerre** [comment]
The response from that curl command tells you there are no jobs configured with an expression like `refs/heads/develop` and no jobs were triggered. Are you saying that is what you expected or is that your problem?

Are you saying it does not work with GitHub but does work with curl?

**Comment by tomasbjerre** [comment]
no response, closing
