### ISSUE TITLE
Ability to include the result from value filter

### ISSUE THREAD

**Issue by petromir** [jenkinsci/generic-webhook-trigger-plugin#91]
Thanks for the great plugin!

Would it be possible to include the result from value filter instead of removing it. Most of the time it's easier to construct positive matching.

**Comment by tomasbjerre** [comment]
Do you have an example of that situation? The json and the jsonpath.

**Comment by petromir** [comment]
Thanks for the quick response!

I have monorepo with the following structure:
```
books/
authors/
common/
docker-compose.yml
```
where `books` and `authors` are separate modules (web services) and `common` is just a shared module used by `books` and `authors`. The root directory may contain different number of files.

We have separate Jenkins jobs for each of the web services, which should be triggered when a file is added, removed or modified in the specific module (`books` or `authors`), `common` module or root directory, all of them under specific branch. Here is a stripped example of GitHub JSON:
```json
{
  "ref": "refs/heads/master",
  "commits": [
    {
      "added": [
        "books/src/test/java/com/example/books/services/BookSercive.java",
        "authors/src/test/java/com/example/AuthorsServiceTest.java"
      ],
      "removed": [
        "test.sh"
      ],
      "modified": [
        "run.sh",
        "books/src/test/java/com/example/books/services/BookSercive.java",
        "authors/src/test/java/com/example/users/services/AuthorsService.java"
        "common/src/test/java/com/example/validation/EmailValidator.java"
      ]
    }
  ]
}
```

In order to cover my case I have to write 3 variables in each Jenkins job:

Variable | JSONPath Expression | Value filter 
-------- | ----------------------| -----------
`$changed_dir_files` | `$.commits[*].['modified','added','removed'][?(@ =~ /^books\/.*/i)]` (`books` is replace with author in the other job) | `\b(?!legal-values).*` (this was the most problematic part)
`$ref` | `$.ref`  | `^(refs/heads/|refs/remotes/origin/)`
`$changed_root_files` | `$.commits[*].['modified','added','removed'][?(!(@ =~ /^.*(?=\/).*$/i))]` (that one made me sick) |  None yet

I haven't specified `Optional filter`, because I'm still trying to reduce the content using `Variable filter`.
I personally see several things as improvments:
1. Option to choose inclusion or exclusion in Variable filter - this way the user will spend less time finding the right regex.
2. Multiple `Optional filter`s. It's easier to focus on single result instead of think how to combine several variable and then write complex regex to cover the combination. That's why I voted for #54 

Let me know if you need more details.

**Comment by tomasbjerre** [comment]
Can you not just do `[^a-z]` if `a-z` is your legal characters?

Did you see this test case? https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github/github-push-get-changed-files.feature
Can you not have `$changed_root_files` like `$.commits[*].['modified','added','removed'][*]`?

I will need to see that complex regexp before I'm convinced.

**Comment by petromir** [comment]
I don't find JSONPath as a problematic part, only the filtering after that. I tried your suggestion and now I can say that following configuration works:
### Variables
Variable | JSONPath Expression | Value filter 
-------- | ----------------------| -----------
`$changed_dir_files` | `$.commits[*].['modified','added','removed'][*]` | None
`$ref` | `$.ref`  | <code>^(refs/heads/\|refs/remotes/origin/)</code>

### Optional filter

Expression | Text
--- | ---
<code>master\s((.\*"(books/\|common/\|sqs/\|security/\|common-test/\|db/)[^"]+?".*)\|(.*"[^/"]+".*))</code> | `$ref $changed_files`

Thanks a lot! So the biggest issue is in finding the working regex, which is our responsibility, not yours. I still think that the above improvements might help when a person start dealing with JSONPath and regexes

It would be awesome if you can add my case as separate `.feature` file in https://github.com/jenkinsci/generic-webhook-trigger-plugin/tree/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github, so we will have an example of monorepo changes.

**Comment by tomasbjerre** [comment]
Test case added now.

I don't want to implement the changes because I don't feel it is worth the effort. It would make the plugin more complex and need more documentation. Issues are easier to report and understand if it is just a simple regexp. With one single regexp, the filtering condition can easily be visualized, like yours: https://jex.im/regulex/#!flags=&re=master%5Cs((.*%22(books%2F%7Ccommon%2F%7Csqs%2F%7Csecurity%2F%7Ccommon-test%2F%7Cdb%2F)%5B%5E%22%5D%2B%3F%22.)%7C(.%22%5B%5E%2F%22%5D%2B%22.*))

**Comment by petromir** [comment]
Thanks!

**Comment by tomasbjerre** [comment]
No problem. Thanks for your feedback!
