### ISSUE TITLE
Ability to view evaluated text and regex matches from Optional filter

### ISSUE THREAD

**Issue by petromir** [jenkinsci/generic-webhook-trigger-plugin#93]
I have the following options:
### Variables
Variable | JSONPath Expression | Value filter 
-------- | ----------------------| -----------
`$changed_dir_files` | `$.commits[*].['modified','added','removed'][*]` | None
`$ref` | `$.ref`  | <code>^(refs/heads/\|refs/remotes/origin/)</code>

### Optional filter

Expression | Text
--- | ---
<code>master\s((.\*"(books/\|common/\|sqs/\|security/\|common-test/\|db/)[^"]+?".*)\|(.*"[^/"]+".*))</code> | `$ref $changed_files`

Would it be possible to view the following `Optional filter` data within Jenkins (not only in the response of the request to `https://<JENKINS_URL>/generic-webhook-trigger/invoke)`:
1. Expression -  same as in the response, e.g.
```
"regexpFilterExpression": "master\\s((.*\"(legal-values/|common/|sqs/|security/|common-test/|db/)[^\"]+?\".*)|(.*\"[^/\"]+\".*))"
```
2. Evaluated text when variables are used in `Text` field, same as in the response
```
"regexpFilterText": "master [\"README.md\"]"
```
3. Regex matches. It would help us to see what the given regex matches and why might not work.

**Comment by tomasbjerre** [comment]
When you say "within Jenkins", do you mean the build log? So only for jobs that are triggered?

**Comment by petromir** [comment]
The information can be presented in the job console, when the regex matches, but I don't know where the content goes when doesn't match.

**Comment by tomasbjerre** [comment]
It can be logged to the global Jenkins log. And you would need access to that.

**Comment by petromir** [comment]
The access is not an issue.
I already have few log recorders for hooks:

![screenshot 2018-11-27 at 14 08 46](https://user-images.githubusercontent.com/1680908/49081073-48f22600-f24e-11e8-8129-59d9f7431c02.png)

Here is `Github Pull Request Hook`
![screenshot 2018-11-27 at 14 10 45](https://user-images.githubusercontent.com/1680908/49081126-7343e380-f24e-11e8-9682-6343ca2bb3ee.png)

**Comment by tomasbjerre** [comment]
Ok.

I think most users are able to invoke the Jenkins instance with `curl`. And will get a clear response from that.

The downside of implementing this is the risk of spamming logs. And it would probably require an extra checkbox in the GUI to enable/disable this logging.

So it would add some complexity that I don't feel is needed as you can do the same thing with `curl`.

**Comment by spidey** [comment]
What about doing something similar to what the Multibranch Pipeline plugin does? Add an even log link that lists requests coming in and triggered jobs if any.

**Comment by tomasbjerre** [comment]
Feel free to submit a PR.

**Comment by petromir** [comment]
Well I don't use Jenkins anymore, so feel free to close this issue 😄
