### ISSUE TITLE
DSL script unexpected char GenericTrigger

### ISSUE THREAD

**Issue by freidenker** [jenkinsci/generic-webhook-trigger-plugin#94]
------------------------------------
         pipelineJob(job_name) {
                      triggers {
                        GenericTrigger {
                            genericVariables {
                                genericVariable {
                                    key("MERGE_REQUEST_TO_BRANCH")
                                    value("\$.merge_request.target_branch")
                                    expressionType("JSONPath")
                                    regexpFilter("")
                                }
                                genericVariable {
                                    key("MERGE_REQUEST_FROM_BRANCH")
                                    value("\$.merge_request.source_branch")
                                    expressionType("JSONPath")
                                    regexpFilter("")
                                }
                                genericVariable {
                                    key("MERGE_REQUEST_STATUS")
                                    value("\$.merge_request.merge_status")
                                    expressionType("JSONPath")
                                    regexpFilter("")
                                }                                
                                genericVariable {
                                    key("MERGE_REQUST_IID")
                                    value("\$.merge_request.iid")
                                    expressionType("JSONPath")
                                    regexpFilter("")
                                }
                                genericVariable {
                                    key("MR_OBJECT_KIND")
                                    value("\$.object_kind")
                                    expressionType("JSONPath")
                                    regexpFilter("")
                                }
                                genericVariable {
                                    key("MR_TITLE")
                                    value("\$.merge_request.title")
                                    expressionType("JSONPath")
                                    regexpFilter("")
                                }
                            }
                        }
                                                      
                      }                       
                       definition {
                           cpsScm {
                               scm {
                                   git {
                                       remote {
                                           credentials(git_credentials)
                                           url(git_url)                                           
                                       }
                                       //branch('master')
                                       branch(git_branch)
                                   }
                               }
                               scriptPath("jenkinsfile-ci.groovy")

                           }
                       }

                   } 

--------------------------
the log

Processing provided DSL script
ERROR: startup failed:
script: 201: unexpected char: 0xA0 @ line 201, column 1.
                           GenericTrigger {
   

1 error

Finished: FAILURE

**Comment by tomasbjerre** [comment]
I guess you copy/pasted the code from somewhere. And ended up with a crazy character.

**Comment by freidenker** [comment]
> I guess you copy/pasted the code from somewhere. And ended up with a crazy character.

you are right, i just found the cause. the spaces is not correct. thank you!
