### ISSUE TITLE
triggered:false

### ISSUE THREAD

**Issue by forestfsl** [jenkinsci/generic-webhook-trigger-plugin#96]
* Generic Webhook Trigger Plugin 1.5.0.
 * Jenkins version 2.155
 * mac.
   * Variables configured, names, expressions...
   * Pipeline script
 * Build job log
 * Post content received. It can be found in the job execution log. People using GitHub often forget to set the content type in "Manage webhook" when configuring the webhook at GitHub.
 * A `curl` command and its response.
 * Expected result and actual result.

You may also have a look at the test cases as they should answer the most common questions:
 
  https://github.com/jenkinsci/generic-webhook-trigger-plugin/tree/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd

If you are fiddling with expressions, you may want to checkout:

* [This JSONPath site](http://jsonpath.herokuapp.com/)
* [This XPath site](http://www.freeformatter.com/xpath-tester.html)
* [This regexp site](https://jex.im/regulex/)

log:
```
curl -vs -H "Content-Type:application/json" -X POST -d '{
  "ref": "refs/heads/master",
  "before": "530136eed1ecb23a03101485f25fecd8e10d2a19",
  "after": "530136eed1ecb23a03101485f25fecd8e10d2a19"}' http://192.168.31.172:8080/jenkins/generic-webhook-trigger/invoke\?token\=cherrySDK 2>&1
*   Trying 192.168.31.172...
* TCP_NODELAY set
* Connected to 192.168.31.172 (192.168.31.172) port 8080 (#0)
> POST /jenkins/generic-webhook-trigger/invoke?token=cherrySDK HTTP/1.1
> Host: 192.168.31.172:8080
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type:application/json
> Content-Length: 142
>
* upload completely sent off: 142 out of 142 bytes
< HTTP/1.1 403 No valid crumb was included in the request
< Date: Tue, 11 Dec 2018 03:01:55 GMT
< X-Content-Type-Options: nosniff
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=iso-8859-1
< Content-Length: 419
< Server: Jetty(9.4.z-SNAPSHOT)
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 No valid crumb was included in the request</title>
</head>
<body><h2>HTTP ERROR 403</h2>
<p>Problem accessing /jenkins/generic-webhook-trigger/invoke. Reason:
<pre>    No valid crumb was included in the request</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
* Connection #0 to host 192.168.31.172 left intact
```
A Curl command can look something like this:
```
curl -vs -H "Content-Type:application/json" -X POST -d {
  "ref": "refs/heads/master",
  "before": "530136eed1ecb23a03101485f25fecd8e10d2a19",
  "after": "530136eed1ecb23a03101485f25fecd8e10d2a19"} http://192.168.31.172:8080/jenkins/generic-webhook-trigger/invoke\?token\=cherrySDK 2>&1
```

I can't trigger jenkins

**Comment by tomasbjerre** [comment]
Is your Jenkins reachable at `http://192.168.31.172:8080/jenkins/` or is it `http://192.168.31.172:8080/` ?

If it is the later one, you should do it like: `http://192.168.31.172:8080/generic-webhook-trigger/invoke\?token\=cherrySDK 2>&1`

**Comment by tomasbjerre** [comment]
no response, closing.

**Comment by saquibtmf** [comment]
Has this been resolved? I am facing this issue and have tried every possible solution that I could find.
The webhook trigger works with 'GitHub' plugin, but does not work with 'Generic Webhook Trigger'.

Any ideas?
