### ISSUE TITLE
Avoid calling getLogFile

### ISSUE THREAD

**Issue by martinmosegaard** [jenkinsci/generic-webhook-trigger-plugin#97]
Setup is a job with a generic webhook trigger. After running the job once, the trigger disappears from the job configuration. The Jenkins log contains this:

```
Avoid calling getLogFile on <jobname> #<buildnumber>
java.lang.UnsupportedOperationException
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.getLogFile(WorkflowRun.java:1087)
	at org.jenkinsci.plugins.gwt.GenericWebhookEnvironmentContributor.notLogged(GenericWebhookEnvironmentContributor.java:56)
	at org.jenkinsci.plugins.gwt.GenericWebhookEnvironmentContributor.buildEnvironmentFor(GenericWebhookEnvironmentContributor.java:31)
	at hudson.model.Run.getEnvironment(Run.java:2373)
```

 * Plugin version used:
  * generic-webhook-trigger 1.51
  * workflow-job (Pipeline Job) 2.31 (change about `getLogFile` is mentioned in release 2.29: https://wiki.jenkins.io/display/JENKINS/Pipeline+Job+Plugin )
 * Jenkins version used: 2.150.1

**Comment by martinmosegaard** [comment]
I am not sure that the trigger disappearing is related to the above stack trace. If I modify the trigger to not print contributed variables and not print post content, the stack trace is not logged, but the trigger still disappears after a run.

Cf. the code to call `notLogged` at: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gwt/GenericWebhookEnvironmentContributor.java#L30

**Comment by tomasbjerre** [comment]
What kind of job? Freestyle? pipeline?

If pipeline, can you provide the pipeline code?

**Comment by martinmosegaard** [comment]
Thanks! If I can relate the other issue to the this plugin, I will reopen a new issue with more details.
