### ISSUE TITLE
Does this plugin support https

### ISSUE THREAD

**Issue by xjparkerx** [jenkinsci/generic-webhook-trigger-plugin#98]
* Plugin version used.
1.50
 * Jenkins version used.
2.138.2
 * Your configuration.
We just converted the jenkins master from no SSL to using SSL.  Now we're getting no webhooks.

**Comment by tomasbjerre** [comment]
Yes

**Comment by xjparkerx** [comment]
Ah I found the error.  I couldn't find it before.  It's an issue with artifactory getting pissy with the jenkins cert.  Thanks for the quick response.
