### ISSUE TITLE
GenericWebhook Trigger plugin environment variables on regexpfilterexpression

### ISSUE THREAD

**Issue by thomasbinny1989** [jenkinsci/generic-webhook-trigger-plugin#99]
Trying to implement trigger using generic webhook trigger, the regexpFilterExpression option is not interpolating the environment variables set.

The plugin has been used on a declarative pipeline template.

pipeline {
 agent {
        label 'xxxx'
   }

  parameters {
      string(name: 'BRAND', defaultValue: 'xxx', description: 'xxx')
      string(name: 'ID', defaultValue: 'xxx', description: 'xxx)
  }
  environment {
   BRANCH_NAME = "cdf"
    GIT_USER = "abc"
     }

  triggers {
    GenericTrigger(
     genericVariables: [
      [key: 'ref', value: '$.ref'],
      [key: 'changed_files', value: '$.commits[0].[\'modified\',\'added\',\'removed\'][*]'],
      [key: 'commit_user', value: '$.commits[0].committer.username']
     ],
     causeString: 'Triggering build for files $changed_files on $ref from user: $commit_user',
     token: 'abcd',
     printContributedVariables: true,
     printPostContent: true,
     silentResponse: false,
     regexpFilterText: '$ref $changed_files $commit_user',
     regexpFilterExpression: "^refs/heads/${env.BRANCH_NAME}\\s(.*\"(${params.BRAND}\\/params.yml).*\"|.*\"(${params.BRAND}\\/.*\\.properties).*\")[^\\s]+?\\s((?!${env.GIT_USER}))"
    )
  }
stages {
        steps {
          deleteDir()
          echo "${env.GIT_USER}"
          echo "${env.BRANCH_NAME}"
          echo "${params.BRAND}"
          //the value substitutes here but not on triggers
}

Output received 
^refs/heads/null\s(.*"(xxxx\/params.yml).*"|.*"(xxx\/.*\.properties).*")[^\s]+?\s((?!null))
its substituting environment variables as null.

screenshot:
![screenshot 2019-01-23 at 5 30 57 pm](https://user-images.githubusercontent.com/29627315/51625297-b8c21b80-1f34-11e9-933a-e4212045a734.png)

Output expected should be
^refs/heads/cdf\s(.*"(xxxx\/params.yml).*"|.*"(xxx\/.*\.properties).*")[^\s]+?\s((?!abc))

@tomasbjerre  would be great if you could suggest on the same.

**Comment by tomasbjerre** [comment]
The `regexpFilterExpression` can only use variables that you defined in `genericVariables: [...]`.

**Comment by thomasbinny1989** [comment]
it was able to substitute this ${params.BRAND} and the problem is when i try to substitute value as environment variable i still get null.

genericVariables: [
[key: 'ref', value: '$.ref'],
[key: 'changed_files', value: '$.commits[0].['modified','added','removed'][]'],
[key: 'commit_user', value: '$.commits[0].committer.username'],
[key: 'branch_name', value: "${env.BRANCH_NAME}"],
[key: 'git_user', value: "${env.GIT_USER}"],
],
causeString: 'Triggering build for files $changed_files on $ref from user: $commit_user',
token: 'abcd',
printContributedVariables: true,
printPostContent: true,
silentResponse: false,
regexpFilterText: '$ref $changed_files $commit_user',
regexpFilterExpression: "^refs/heads/$branch_name\s(."(${params.BRAND}\/params.yml)."|."(${params.BRAND}\/.\.properties).")[^\s]+?\s((?!$git_user))"
)
}

It still outputs null

**Comment by tomasbjerre** [comment]
This will not work:
```
[key: 'branch_name', value: "${env.BRANCH_NAME}"],
[key: 'git_user', value: "${env.GIT_USER}"],
```
Because the value must be a JSONPath that resolves to a value from the webhook JSON.

**Comment by thomasbinny1989** [comment]
But these values that i would like to pass are not from the JSON PATH, can i not substitute from the environment variable directly on the regexpFilterExpression @tomasbjerre

**Comment by tomasbjerre** [comment]
No not possible. The triggering happens before the job runs. So no environment exists.

**Comment by thomasbinny1989** [comment]
I will try to explain the issue, my job runs of master and my job should trigger only when its "master" but thats something i can not derive from the webhook. Any suggestions how i can sort it.

**Comment by tomasbjerre** [comment]
Looks like you might be using GitHub. Perhaps this example: https://github.com/jenkinsci/generic-webhook-trigger-plugin/blob/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd/github/github-push-trigger-when-master-and-specific-folders-or-root.feature

You should be able to figure it out from the examples here: https://github.com/jenkinsci/generic-webhook-trigger-plugin/tree/master/src/test/resources/org/jenkinsci/plugins/gwt/bdd

**Comment by thomasbinny1989** [comment]
worst thing is if i try using it manually on the job. since the template doesnt have the generic webhook plugin configured on the template after one run, it would remove it from the ui. such a deadlock.

**Comment by thomasbinny1989** [comment]
@tomasbjerre saw this link https://github.com/tomasbjerre/sandbox/blob/master/Jenkinsfile
from where have you got BRANCH_NAME??

**Comment by thomasbinny1989** [comment]
im using a single repo with multiple folders to trigger a build. now the difference is known through a value that is on folder properties of the job. i should be able to get the a=b from the folder properties to the triggers based on file changes in the 'b/' folder be it add remove modify.

**Comment by thomasbinny1989** [comment]
> No not possible. The triggering happens before the job runs. So no environment exists.

@tomasbjerre  Im trying to rewrite the plugin, would you be able to tell me if i could use parameters or the folder properties to be initiated before the plugin is initialised.
